# Findings for original-02 (Ketubot 62b:6). Loaded by build_dossier.py, which supplies ev().
# All translations labelled translation_by_this_dossier are this dossier's own brief renderings.

EXTRA = {
    "scope_note": (
        "Checked: Bavli Ketubot 62b in the Sefaria William Davidson Aramaic, vocalized and English versions, Wikisource "
        "Hebrew and Daf Shevui English; Rashi, Tosafot, Steinsaltz, Maharam Schiff and Maharsha (Chidushei Agadot) "
        "on 62b; the Yerushalmi parallel at Bikkurim 3:3 (Venice, Guggenheimer, Mechon-Mamre, Guggenheimer English) "
        "with Penei Moshe and Sirilio; Bavli Sanhedrin 38a; Seder HaDorot entry 1659. Not checked: Bavli manuscripts, "
        "other commentaries in the Sefaria links list (e.g. Yisrael Kedoshim, Tur, Sha'arei Torat Eretz Yisrael), "
        "and modern prosopographies. Conclusions are scoped to these sources."
    ),
    "local_people": [
        {"local_id": "P1", "label": "Yehuda son of R. Hiyya", "mentions_62b6": ["יהודה בריה דרבי חייא", "יהודה (in R. Yannai's speech)"],
         "note": "story protagonist; dies at the end of the segment"},
        {"local_id": "P2", "label": "R. Hiyya (father of P1)", "mentions_62b6": ["רבי חייא (inside the patronymic)"],
         "note": "local parent placeholder kept from the patronymic; does not act or speak in 62b:6; historical identification separate"},
        {"local_id": "P3", "label": "R. Yannai (father-in-law of P1)", "mentions_62b6": ["רבי ינאי (inside חתניה דרבי ינאי)", "רבי ינאי (speaker)"],
         "note": "the same local person in both mentions; the Hebrew uses the full name twice with no change of referent signalled"},
        {"local_id": "P4", "label": "unnamed wife of P1, daughter of P3", "mentions_62b6": [],
         "note": "never mentioned by a word of her own; implied by חתניה (son-in-law) and by עונתו (his conjugal time). Local placeholder only"},
        {"local_id": "G1", "label": "unnamed addressees of R. Yannai (להו, 'to them')", "mentions_62b6": ["להו"],
         "note": "an unnamed group; translations supply 'the family' or 'those around him'"},
    ],
    "pronoun_map_62b6": [
        {"words": "הוה אזיל ויתיב בבי רב", "referent": "P1", "basis": "text: continues the subject יהודה", "confidence": "high"},
        {"words": "הוה אתי לביתיה", "referent": "P1 comes to his (P1's) house", "basis": "text; Steinsaltz לביתו; Davidson 'his house'. Whether the house is shared with P3 is not stated", "confidence": "high"},
        {"words": "הוה קא חזי", "referent": "unstated observer: P3 (Davidson, Steinsaltz) or 'the people' (Daf Shevui)", "basis": "interpretation; see F5", "confidence": "medium"},
        {"words": "קמיה", "referent": "P1 (the pillar goes before the one coming home)", "basis": "Davidson 'preceding him'; Daf Shevui 'going before him'", "confidence": "medium"},
        {"words": "משכתיה שמעתא", "referent": "P1", "basis": "text", "confidence": "high"},
        {"words": "כיון דלא חזי", "referent": "P3", "basis": "named as speaker in the same sentence; Steinsaltz and Davidson", "confidence": "high"},
        {"words": "אמר להו", "referent": "speaker P3; addressee G1", "basis": "text names the speaker; addressee unnamed", "confidence": "high"},
        {"words": "מטתו / עונתו", "referent": "P1's bed / P1's conjugal time", "basis": "text: 'if Yehuda were alive he would not have missed his time'", "confidence": "high"},
        {"words": "הואי", "referent": "R. Yannai's utterance (the error of 'the ruler')", "basis": "Steinsaltz הדבר הזה שאמר; Davidson 'What he said'", "confidence": "high"},
        {"words": "ונח נפשיה", "referent": "P1 died", "basis": "Steinsaltz, Davidson and Daf Shevui all name Yehuda", "confidence": "high"},
    ],
    "narrated_sequence_62b6": [
        "1 habitual: P1 goes and sits in the study house (בבי רב)",
        "2 habitual: at every twilight (weekly Friday reading supplied from context) P1 comes home",
        "3 habitual: when he comes, a pillar of fire is seen before him",
        "4 once: P1 is held by his study and does not come",
        "5 once: P3 does not see the sign and tells G1 to overturn P1's bed, reasoning P1 would not miss his conjugal time if alive",
        "6 narrator: the utterance became 'like an error that proceeds from a ruler' (Ecclesiastes 10:5)",
        "7 P1 dies",
    ],
    "graph_status": "provisional; no historical identity, date or cross-passage merge is approved by this dossier",
}

FINDINGS = [
    {
        "finding_id": "F1",
        "claim": "Yehuda is literally the son of R. Hiyya. The patronymic בריה means 'his son'. Keep R. Hiyya as a local parent placeholder even though he does not act or speak in this segment.",
        "kind": "textual",
        "evidence": [
            ev("S1", "יהודה בריה דרבי חייא חתניה דרבי ינאי",
               "Yehuda, son of Rabbi Hiyya, son-in-law of Rabbi Yannai (translation_by_this_dossier)"),
            ev("S1W", "יהודה בריה דר' חייא חתניה דר' ינאי"),
            ev("S1E", "<b>Yehuda, son of Rabbi Ḥiyya</b> and <b>son-in-law of Rabbi Yannai"),
        ],
        "reasoning": "בריה is the ordinary Aramaic word for 'his son'. It is not a title here. The two Hebrew editions agree on the wording. The English is built on the same editorial work as the Davidson Aramaic, so it is not separate corroboration.",
        "confidence": "high",
        "graph_effect": "Add child_of(P1 -> P2 'R. Hiyya', local). Evidence type: name-embedded kinship. Historical identity of P2 is decided separately (see F13).",
    },
    {
        "finding_id": "F2",
        "claim": "Yehuda is R. Yannai's son-in-law. The marriage is stated by the passage through the kinship word חתניה, not narrated as an event. It implies an unnamed wife, a daughter of R. Yannai, who is never mentioned directly.",
        "kind": "textual",
        "evidence": [
            ev("S1", "יהודה בריה דרבי חייא חתניה דרבי ינאי"),
            ev("S7", "<b>ר' חייא, חתניה</b> <small>[חתנו]</small> של <b>ר' ינאי"),
            ev("S12", "יהודה בר חייה הוה יליף סליק ושאיל בשלמיה דרבי ינאי חמוה מערב שבת לערב שבת",
               "Yehuda bar Hiyya used to go up and greet Rabbi Yannai, his father-in-law, every Sabbath eve (translation_by_this_dossier)"),
        ],
        "reasoning": "חתן of a named man means the husband of his daughter. The Yerushalmi parallel uses the converse term חמוה ('his father-in-law'). That is a second compilation giving the same relation, but it tells the story differently (F8) and may come from a shared tradition. It is a parallel attestation, not proof of historical independence. Neither text names the daughter, says when they married or mentions children.",
        "confidence": "high",
        "graph_effect": "Add one directed relation son_in_law_of(P1 -> P3). Displaying father_in_law_of(P3 -> P1) is the inverse, not a second observation. Add local P4 (unnamed daughter of P3, wife of P1) with child_of(P4 -> P3) and spouse(P1, P4), both marked 'implied by kinship term' rather than 'narrated marriage'.",
    },
    {
        "finding_id": "F3",
        "claim": "The wife is also implied by 'his bed' and 'his conjugal time' (עונתו), which assume a wife waiting at home. The text does not say she is R. Yannai's daughter. That is the natural reading because R. Yannai watches for the homecoming, but it is inference.",
        "kind": "interpretation",
        "evidence": [
            ev("S1", "כפו מטתו שאילמלי יהודה קיים לא ביטל עונתו",
               "Overturn his bed, for if Yehuda were alive he would not have cancelled his conjugal time (translation_by_this_dossier)"),
            ev("S1", "עונה של תלמידי חכמים אימת אמר רב יהודה אמר שמואל מערב שבת לערב שבת"),
            ev("S8", "כ\"ש שקיים זה עונה אחת לז\"א כפו מטתו",
               "all the more so that this one would keep one conjugal time; therefore he said 'overturn his bed' (translation_by_this_dossier)"),
        ],
        "reasoning": "The preceding segment (62b:5) sets scholars' conjugal time as Friday night. R. Yannai's inference only works if Yehuda had a wife at home. The passage never uses a word for wife in 62b:6. Maharam Schiff explains R. Yannai's certainty: even when ill, David kept his conjugal obligation (Sanhedrin), so Yehuda would not have missed one; therefore he must be dead.",
        "confidence": "medium",
        "graph_effect": "Attach the conjugal-time evidence to spouse(P1, P4) as supporting context. Do not create a second unnamed wife. Mark 'wife = daughter of R. Yannai' as a reading with medium confidence, not text.",
    },
    {
        "finding_id": "F4",
        "claim": "The academic journey is habitual and weekly. Yehuda 'would go and sit in the study house' and come home at twilight. The study house, its place and any teacher are not named, so no teacher edge follows.",
        "kind": "textual",
        "evidence": [
            ev("S1", "הוה אזיל ויתיב בבי רב וכל בי שמשי הוה אתי לביתיה",
               "he would go and sit in the study house, and every twilight he would come to his house (translation_by_this_dossier)"),
            ev("S7", "וכל בי שמשי</b> <small>[בין השמשות]</small> של ערב שבת"),
            ev("S1E", "every</b> Shabbat eve <b>at twilight he would come to his house."),
        ],
        "reasoning": "The Hebrew says only 'every twilight'. Steinsaltz (Hebrew) and the Davidson English (not in bold) both add 'of Shabbat eve', drawing on 62b:5. That is a strong contextual reading, but it is editorial. בי רב here is the generic 'study house', not 'the house of Rav'. The passage gives no distance and no city.",
        "confidence": "high",
        "graph_effect": "Record a habitual scene: P1 studies at an unnamed study house; P1 travels home weekly (weekly = editorial reading from context). No teacher_of edge. No place node.",
    },
    {
        "finding_id": "F5",
        "claim": "The grammar does not say who sees the pillar of fire. Davidson and Steinsaltz supply R. Yannai. Daf Shevui says 'the people saw'. Maharsha writes that the pillar signalled 'to them'.",
        "kind": "interpretation",
        "evidence": [
            ev("S1", "וכי הוה אתי הוה קא חזי קמיה עמודא דנורא",
               "and when he would come, [someone] would see before him a pillar of fire (translation_by_this_dossier)"),
            ev("S1E", "When he would come,</b> Rabbi Yannai <b>would see a pillar of fire preceding him</b> due to his sanctity."),
            ev("S7", "<small>[וכאשר היה בא, היה רואה</small> ר' ינאי <small>לפניו עמוד של אש]</small> מפני קדושתו"),
            ev("S1D", "When he would arrive the people saw a pillar of light going before him."),
            ev("S9", "אפשר שהיה העמוד דנורא רומז להם על זמן קבלת שבת",
               "perhaps the pillar of fire hinted to them the time of receiving Shabbat (translation_by_this_dossier)"),
        ],
        "reasoning": "חזי is a singular participle with no stated subject. The next clause (כיון דלא חזי ההוא סימנא אמר להו רבי ינאי) makes R. Yannai the one who fails to see the sign, which supports reading him as the habitual observer too. Davidson and Steinsaltz share editorial work, so they count as one line of interpretation. Daf Shevui's 'the people' and Maharsha's 'to them' keep a wider set of observers open. Daf Shevui also says 'light' where the Aramaic has fire (נורא).",
        "confidence": "medium",
        "graph_effect": "Scene 'sees pillar' has observer P3 in reading A and an unnamed group in reading B. Do not use it as evidence that P1 and P3 lived in the same house.",
    },
    {
        "finding_id": "F6",
        "claim": "R. Yannai speaks to an unnamed group (להו, 'to them'). The group is not named. Translations fill it in as 'the family' or 'those around him'. The instruction is a mourning rite.",
        "kind": "textual",
        "evidence": [
            ev("S1", "כיון דלא חזי ההוא סימנא אמר להו רבי ינאי כפו מטתו"),
            ev("S7", "<b>אמר להו</b> <small>[להם]</small> <b>ר' ינאי</b> חותנו לבני המשפחה"),
            ev("S1E", "<b>he said to</b> the family: <b>Turn his bed over,</b>"),
            ev("S1D", "R. Yannai said to those [around him]"),
            ev("S5", "כפו מטתו - כדת המתאבלים דחייבין בכפיית המטה:",
               "Overturn his bed: according to the practice of mourners, who are obliged to overturn the bed (translation_by_this_dossier)"),
        ],
        "reasoning": "The speaker is named. The addressee is a plural pronoun only. 'The family' could include Yehuda's wife, but no source I checked says so. The Yerushalmi parallel has R. Yannai's students present (F8), a different setting.",
        "confidence": "high",
        "graph_effect": "Speech edge P3 -> G1 (unnamed group). Do not create P3 -> P4 speech. Mourning instruction concerns P1.",
    },
    {
        "finding_id": "F7",
        "claim": "The narrator treats R. Yannai's words as a ruler's mistaken decree that came true: Yehuda died. The death and its narrated cause are literary claims inside the Bavli story.",
        "kind": "textual",
        "evidence": [
            ev("S1", "הואי כשגגה שיוצא מלפני השליט ונח נפשיה",
               "it became 'like an error that goes out from before the ruler' (Eccl. 10:5), and he died (translation_by_this_dossier)"),
            ev("S7", "<b>ונח נפשיה</b> <small>[ונפטר]</small> יהודה בר' חייא."),
            ev("S1E", "<b>and</b> Yehuda, son of Rabbi Ḥiyya, <b>died.</b>"),
            ev("S1D", "and he [Judah] died."),
            ev("S9", "מפורש במסכת מ\"ק דברית כרותה לשפתים",
               "explained in tractate Moed Katan: a covenant is made with the lips (translation_by_this_dossier)"),
        ],
        "reasoning": "All three translations make Yehuda the one who died. The verse casts R. Yannai as 'the ruler' whose mistaken statement takes effect. Maharsha links this to the idea that spoken words can come true. The Yerushalmi parallel has no such cause (F8).",
        "confidence": "high",
        "graph_effect": "Event: death of P1 (in the Bavli story). Narrative causal link: P3's utterance -> P1's death, labelled literary/narrated, not historical. Relative time: P1 dies within P3's lifetime in this story.",
    },
    {
        "finding_id": "F8",
        "claim": "The Yerushalmi (Bikkurim 3:3) tells a different version. Yehuda goes up each Sabbath eve to greet his father-in-law R. Yannai. R. Yannai sits on a raised spot to see him coming and rise for him. His students object, and he answers that one does not sit before Sinai. Once Yehuda does not come, and R. Yannai concludes he has died. There is no study house, no conjugal time, no overturned bed and no ruler's error.",
        "kind": "textual",
        "evidence": [
            ev("S12", "והוה יתיב ליה על אתר תלי בגין מיחמיניה ומקים לי' מן קומוי",
               "and he would sit on a raised spot in order to see him and rise before him (translation_by_this_dossier)"),
            ev("S12", "אמרי' ליה תלמידוי לא כן אלפן ר' לזקן ד' אמו' אמר לון אין ישיבה לפני סיני",
               "His students said to him: did not our master teach us, for an elder, four cubits? He said to them: there is no sitting before Sinai (translation_by_this_dossier)"),
            ev("S12", "חד זמן עני מסיק אמר לית איפשר דיהודה ברי משני מנהגיה",
               "Once he was late coming up. He said: it is impossible that Yehuda my son would change his habit (translation_by_this_dossier)"),
            ev("S12E", "Jehudah bar Ḥiyya used to go and greet his father-in-law Rebbi Yannai every Sabbath eve. He used to sit on a hilly place in order to see him and get up before him."),
            ev("S12E", "It is reasonable that we lost the great Jehudah."),
            ev("S15", "והיה ר' ינאי יושב במקום אחד ותולה עיניו לראותו ולקום מפניו",
               "and R. Yannai would sit in one place and lift his eyes to see him and rise before him (translation_by_this_dossier)"),
        ],
        "reasoning": "The journey's direction and purpose differ between the two versions. In the Bavli, Yehuda comes home from the study house. In the Yerushalmi, he goes up to greet R. Yannai. Both agree on the kinship, the weekly Sabbath-eve pattern, the one missed visit and R. Yannai inferring the death. This is a parallel tradition, not two historical events and not independent corroboration. The Yerushalmi adds R. Yannai's unnamed students and treats Yehuda as 'Sinai', a figure owed honour.",
        "confidence": "high",
        "graph_effect": "Add a separate passage reading for Yerushalmi Bikkurim 3:3:13 linked as a parallel. Its own claims: son_in_law_of(P1, P3) again (same relation, different compilation); honour scene P3 rises for P1; P3 teacher of an unnamed student group (G2) who addresses P3. Do not merge the two scenes into one event.",
    },
    {
        "finding_id": "F9",
        "claim": "In the Yerushalmi, R. Yannai calls Yehuda 'my son' (ברי). This is how a father-in-law addresses a son-in-law, not biological kinship.",
        "kind": "interpretation",
        "evidence": [
            ev("S12", "לית איפשר דיהודה ברי משני מנהגיה"),
            ev("S12E", "He said it is impossible that my son Jehudah should change his habits"),
        ],
        "reasoning": "The same segment calls R. Yannai Yehuda's חמוה (father-in-law), and the Bavli gives Yehuda's father as R. Hiyya. A form of address is not a patronymic.",
        "confidence": "high",
        "graph_effect": "No child_of(P1 -> P3). Record 'addresses as my son' as an address form on the speech event only.",
    },
    {
        "finding_id": "F10",
        "claim": "The Yerushalmi ends with יהודה ב\"ר. It is unclear whether ב\"ר is an honorific or 'son of Rabbi'. Guggenheimer vocalizes בְּרִיבִי and translates 'the great Jehudah'. Penei Moshe writes ברבי. The same form is used for Hizqiah at the start of the segment.",
        "kind": "uncertainty",
        "evidence": [
            ev("S12", "מסתברא שאין לנו יהודה ב\"ר"),
            ev("S12G", "מִסְתַּבְּרָא שֶׁאֵין לָנוּ יְהוּדָה בְּרִיבִי."),
            ev("S12E", "It is reasonable that we lost the great Jehudah."),
            ev("S15", "דומה שאין לנו יהודה ברבי שנפטר"),
            ev("S12G", "חִזְקִיָּה בְּרִיבִי"),
        ],
        "reasoning": "Read as a title, it adds no kinship. Read as 'son of Rabbi', it would at most repeat the known father (R. Hiyya is called Rabbi). It must not create a new parent. Penei Moshe elsewhere in the same comment writes בר' חייה, so its ברבי may mean the same father.",
        "confidence": "medium",
        "graph_effect": "Save ב\"ר as a name-form alternative (title vs patronymic). Never add a second father from it.",
    },
    {
        "finding_id": "F11",
        "claim": "Commentators on the Yerushalmi read it through the Bavli. Penei Moshe adds the 'error from the ruler' ending, and Sirilio cites the Bavli story. The Yerushalmi witnesses also differ slightly: Venice and Guggenheimer read עני, Sirilio's lemma reads שני, and Mechon-Mamre repeats a sentence.",
        "kind": "textual",
        "evidence": [
            ev("S15", "שנפטר והיה כשגגה היוצא מלפני השליט:"),
            ev("S11", "<b>חד זמן שני מסיק.</b> פעם אחת שינה מלעלות על אותו מקום גבוה ובפ' אע\"פ קאמר חד זמן משכא שמעתיה ואמר כפו מטתו",
               "Once he changed [his habit] of going up to that high place; and in chapter Af al pi (Ketubot ch. 5) it says: once his study held him, and he said 'overturn his bed' (translation_by_this_dossier)"),
            ev("S12", "חד זמן עני מסיק"),
            ev("S12M", "יהודה בר חייה הוה יליף סליק ושאל בשלמיה דרבי ינאי חמוי מערב שבת לערב שבת והוה יתיב ליה על אתר תלי בגין מיחמוניה ומיקם ליה מן קומיהון. יהודה בר חייה"),
        ],
        "reasoning": "The ruler's-error ending belongs to the Bavli. When Penei Moshe adds it, that is harmonizing commentary, not Yerushalmi text. The Mechon-Mamre repetition (and its plural מן קומיהון in the first copy) looks like a transmission or typing duplication. It must not be read as a second visit. The עני/שני variant changes the wording (late vs changed), not who the participants are.",
        "confidence": "medium",
        "graph_effect": "Keep commentary harmonization as commentary evidence. Save the variant as a source-variant evidence type. Do not add a second visit event.",
    },
    {
        "finding_id": "F12",
        "claim": "Yehuda's brother Hizqiah does not appear in Ketubot 62b:6. He appears elsewhere. Bavli Sanhedrin 38a names 'Yehuda and Hizqiyya, sons of R. Hiyya' at Rabbi's meal. The Yerushalmi segment opens with a separate Hizqiah anecdote. Guggenheimer's note and Seder HaDorot call them twins.",
        "kind": "interpretation",
        "evidence": [
            ev("S13", "יהודה וחזקיה בני רבי חייא הוו יתבי בסעודתא קמי רבי",
               "Yehuda and Hizqiyya, sons of Rabbi Hiyya, were sitting at a meal before Rabbi (translation_by_this_dossier)"),
            ev("S12E", "Ḥizqiah ben R. Ḥiyya the elder, twin brother of Jehudah ben Ḥiyya."),
            ev("S10", "יהודה וחזקיה בני ר' חייא נולדו מטיפה אחת"),
        ],
        "reasoning": "Sanhedrin 38a states a sibling relation through a shared father. Linking that Yehuda to the Ketubot Yehuda rests on the matching name and father's name in the same corpus. That is plausible but it is an identity decision. The twin claim comes from later commentary and chronicle, not from these Talmud passages.",
        "confidence": "medium",
        "graph_effect": "No sibling edge from Ketubot 62b:6. If identity packs later accept P1 = Yehuda of Sanhedrin 38a, siblings(Yehuda, Hizqiyya) comes from Sanhedrin 38a. The twin claim stays chronicle/commentary evidence.",
    },
    {
        "finding_id": "F13",
        "claim": "The passage does not say which R. Hiyya or which R. Yannai is meant. Seder HaDorot and Guggenheimer treat the father as R. Hiyya the elder, the associate of Rabbi. The next Bavli segment (62b:7) has Rabbi dealing with R. Hiyya's household, but adjacency is not identity.",
        "kind": "uncertainty",
        "evidence": [
            ev("S12E", "Ḥizqiah ben R. Ḥiyya the elder"),
            ev("S1", "רבי איעסק ליה לבריה בי רבי חייא כי מטא למיכתב כתובה נח נפשה דרביתא",
               "Rabbi arranged a match for his son with the household of Rabbi Hiyya; when it came to writing the ketubah, the girl died (translation_by_this_dossier)"),
            ev("S10", "חתנו של ר' ינאי."),
        ],
        "reasoning": "Shared names do not establish historical identity. The later identifications are reasonable scholarly positions and are saved here as commentary or chronicle evidence.",
        "confidence": "medium",
        "graph_effect": "Keep P2 and P3 as local persons. Proposing P2 = R. Hiyya the elder goes to an identity pack with this evidence, not to the text layer.",
    },
    {
        "finding_id": "F14",
        "claim": "62b:6 belongs to a chain of stories illustrating a warning. Rava says the Sages who relied on a lenient ruling about leaving home to study 'paid with their lives'. The Rav Rehumi story (62b:4) uses the same formula. The order of the chain is thematic, not chronological.",
        "kind": "textual",
        "evidence": [
            ev("S1", "התלמידים יוצאין לתלמוד תורה שתים ושלש שנים שלא ברשות"),
            ev("S1", "אמר רבא סמכו רבנן אדרב אדא בר אהבה ועבדי עובדא בנפשייהו"),
            ev("S5", "בנפשייהו - והוא בא להם ליטול מהם נפשות שנענשים ומתים:",
               "with their lives: and it came to take lives from them, for they are punished and die (translation_by_this_dossier)"),
            ev("S1", "יומא חד משכתיה שמעתא הוה מסכיא דביתהו"),
        ],
        "reasoning": "The Rav Rehumi story is set before Rava in Mahoza, a later generation. It comes before the R. Yannai story, and Rabbi's family follows. So the order of segments cannot supply 'before' relations between the people. The shared formula יומא חד משכתיה שמעתא shows a literary template, which is a reason not to treat the details as independent reports.",
        "confidence": "high",
        "graph_effect": "Do not derive temporal 'before/after' edges from segment order. Tag 62b:4 and 62b:6 as template-sharing illustrative stories under Rava's remark.",
    },
    {
        "finding_id": "F15",
        "claim": "In the next segments, one marriage is only arranged and one is completed. Rabbi's match for his son with R. Hiyya's household ends when the girl dies at the ketubah stage. His son's match with R. Yosei b. Zimra's household leads to marriage: the son says 'I will marry and then go', and later the text speaks of 'his wife'. Neither woman is named.",
        "kind": "textual",
        "evidence": [
            ev("S1", "רבי איעסק ליה לבריה בי רבי חייא כי מטא למיכתב כתובה נח נפשה דרביתא"),
            ev("S5", "איעסק לבריה - להשיא בתו של רבי חייא:",
               "arranged for his son: to marry him to the daughter of Rabbi Hiyya (translation_by_this_dossier)"),
            ev("S1E", "<b>arranged for his son</b> to marry a daughter of <b>the household of Rabbi Ḥiyya."),
            ev("S1", "אזיל איעסק ליה לבריה בי רבי יוסי בן זימרא פסקו ליה תרתי סרי שנין למיזל בבי רב"),
            ev("S1", "אמר להו איכניס והדר איזיל הוה קא מכסיף מאבוה אמר ליה בני דעת קונך יש בך"),
            ev("S1", "אזיל יתיב תרתי סרי שני בבי רב עד דאתא איעקרא דביתהו"),
        ],
        "reasoning": "The Hebrew says בי רבי חייא, 'R. Hiyya's household'. Rashi makes the girl R. Hiyya's daughter, which would make her Yehuda's sister. That sibling link would rest on Rashi's reading plus an identity decision, not on the text. The son of Rabbi is unnamed in these segments and in the commentaries checked. In 62b:8, 'they agreed for him' has an unstated subject. Rashi says it was 'before he marries'. In 'he was ashamed before his father' and 'he said to him: my son', the speaker is Rabbi and the addressee his son.",
        "confidence": "high",
        "graph_effect": "Wider-context proposals (not 62b:6): arranged_match(son-of-Rabbi, girl of R. Hiyya's household) status=not completed, girl died. Married(son-of-Rabbi, woman of R. Yosei b. Zimra's household) status=completed (62b:10 דביתהו). The son's 12-year study journey after marriage. No sibling edge between P1 and the girl without an explicit decision.",
    },
    {
        "finding_id": "F16",
        "claim": "The 62b:7 inquiry reports biblical descent for both families: Rabbi from Shefatya son of Avital (David's son), R. Hiyya from Shim'i, David's brother. Rashi and Maharsha disagree on what the 'disqualification' was.",
        "kind": "interpretation",
        "evidence": [
            ev("S1", "רבי אתי משפטיה בן אביטל ורבי חייא אתי משמעי אחי דוד"),
            ev("S9", "וק\"ק לפירושו וכי מלכי בית דוד היו נושאין נשים דוקא מבת מלכים",
               "his [Rashi's] explanation is a little difficult: did the kings of David's house marry only daughters of kings? (translation_by_this_dossier)"),
            ev("S9", "ומצאו שאינו אבל היו ממשפחה אחת מישי",
               "and they found that there was not [a disqualification], but they were of one family, from Jesse (translation_by_this_dossier)"),
        ],
        "reasoning": "The ancestry is reported by the Talmud as the result of the families' inquiry. That makes it a genealogical claim in the text, not a verified lineage. Rashi reads it as a mismatch of rank. Maharsha rejects that and reads it as the two families being related through Jesse. Who says what stays attributed.",
        "confidence": "medium",
        "graph_effect": "Optional descent claims (P2's family -> Shim'i; Rabbi -> Shefatya), marked 'reported genealogy, 62b:7'. Rashi and Maharsha readings kept as competing explanations. Not relevant to P1's relations except through the identity of P2.",
    },
    {
        "finding_id": "F17",
        "claim": "The passage says nothing about ages, dates, children or whether R. Hiyya was still alive when Yehuda died. The only relative chronology is that Yehuda dies during R. Yannai's lifetime. Seder HaDorot's statement that the brothers were not ordained is a later chronicle claim.",
        "kind": "uncertainty",
        "evidence": [
            ev("S1", "הואי כשגגה שיוצא מלפני השליט ונח נפשיה"),
            ev("S10", "ולא נסמכו."),
        ],
        "reasoning": "Both the Bavli and the Yerushalmi have R. Yannai alive and reacting to Yehuda's absence. Nothing else in these segments fixes time.",
        "confidence": "high",
        "graph_effect": "Relative-time claim: death(P1) during lifetime(P3), scoped to both story versions. No calendar date, no age, no statement about P2.",
    },
]

ALTERNATIVE_EVID = None

ALTERNATIVES = [
    {"alt_id": "A1", "topic": "observer of the pillar of fire (הוה קא חזי)",
     "readings": [
         {"reading": "R. Yannai sees it", "held_by": "Davidson English; Steinsaltz (one editorial line)"},
         {"reading": "people generally / 'them' see it", "held_by": "Daf Shevui ('the people saw'); Maharsha ('רומז להם')"},
     ],
     "evidence": [ev("S1D", "When he would arrive the people saw a pillar of light going before him.")]},
    {"alt_id": "A2", "topic": "addressee of אמר להו",
     "readings": [
         {"reading": "the family", "held_by": "Davidson English; Steinsaltz לבני המשפחה"},
         {"reading": "those around him (unspecified)", "held_by": "Daf Shevui"},
     ]},
    {"alt_id": "A3", "topic": "frequency of the homecoming (כל בי שמשי)",
     "readings": [
         {"reading": "every Friday twilight", "held_by": "Steinsaltz, Davidson (from 62b:5 context); Yerushalmi parallel says מערב שבת לערב שבת explicitly"},
         {"reading": "literally 'every twilight' (daily)", "held_by": "bare wording only; no source checked adopts it"},
     ]},
    {"alt_id": "A4", "topic": "cause and setting of the death",
     "readings": [
         {"reading": "Bavli: R. Yannai's mourning order, framed as a ruler's error that takes effect; Yehuda absent because held by study", "held_by": "Ketubot 62b:6"},
         {"reading": "Yerushalmi: R. Yannai infers the death from the missed greeting; no causal words; suffering reached the righteous body", "held_by": "Bikkurim 3:3 (Venice, Guggenheimer)"},
         {"reading": "harmonized: Yerushalmi read with the Bavli ending", "held_by": "Penei Moshe; Sirilio cites the Bavli"},
     ]},
    {"alt_id": "A5", "topic": "יהודה ב\"ר in the Yerushalmi",
     "readings": [
         {"reading": "honorific 'beribbi' (the great)", "held_by": "Guggenheimer vocalization and translation"},
         {"reading": "'son of Rabbi' (i.e., of R. Hiyya)", "held_by": "possible reading of Penei Moshe's ברבי; not explicit"},
     ]},
    {"alt_id": "A6", "topic": "meaning of אתר תלי (where R. Yannai sat)",
     "readings": [
         {"reading": "a high place", "held_by": "Sirilio (מקום גבוה); Guggenheimer 'hilly place'"},
         {"reading": "sitting in one place, lifting his eyes (תולה עיניו)", "held_by": "Penei Moshe"},
     ]},
    {"alt_id": "A7", "topic": "the girl of R. Hiyya's household (62b:7)",
     "readings": [
         {"reading": "R. Hiyya's daughter", "held_by": "Rashi; Davidson English 'a daughter of the household'"},
         {"reading": "a girl of his household, relation unspecified", "held_by": "bare Hebrew בי רבי חייא / רביתא"},
     ]},
    {"alt_id": "A8", "topic": "the 'disqualification' in 62b:7",
     "readings": [
         {"reading": "rank mismatch: royal line vs Shim'i's line", "held_by": "Rashi"},
         {"reading": "no disqualification; both families from Jesse", "held_by": "Maharsha"},
     ]},
]

UNRESOLVED = [
    "Whether Yehuda lived in R. Yannai's household or nearby. The Bavli says 'his house', and the Yerushalmi has him 'go up' to R. Yannai, which points to separate homes in that version. Not settled for the Bavli.",
    "The name of R. Yannai's daughter, the date of the marriage and any children. None of the sources checked give these.",
    "Where the study house was and who taught there. The Bavli gives only בי רב.",
    "Which son of Rabbi is meant in 62b:7-10. He is unnamed in the text and in Rashi, Tosafot and Maharsha as checked. Other sources were not searched.",
    "Whether the Bavli and Yerushalmi versions come from one tradition reshaped or from two traditions. This affects how much the shared kinship counts, not whether it is attested.",
    "Bavli manuscript readings of 62b:6 were not checked (for example whether any witness names the observer of the pillar or the addressee).",
    "Other linked commentaries (Yisrael Kedoshim, Tur Orach Chayim 280, Sha'arei Torat Eretz Yisrael, Tosefta Kifshutah) were listed by Sefaria but not read.",
]

CORRECTIONS = [
    {"existing_claim_id": "bavli|Ketubot|62b|6|0|27",
     "change": "Keep kind=kin but set direction: a (Yehuda son of R. Hiyya) is son_in_law_of b (R. Yannai). Display the converse only as an inverse view.",
     "why": "F2: חתניה ד[B] is directional; direction is currently null."},
    {"existing_claim_id": None,
     "change": "Add child_of(Yehuda -> R. Hiyya) from the patronymic, with a local placeholder for R. Hiyya.",
     "why": "F1: a relationship embedded in the name is evidence even if the parent does not act."},
    {"existing_claim_id": None,
     "change": "Add a local unnamed woman P4 (daughter of R. Yannai, wife of Yehuda), with child_of(P4 -> R. Yannai) and spouse(Yehuda, P4), marked 'implied by kinship term', not 'narrated marriage'.",
     "why": "F2, F3: the passage mentions the marriage only through חתניה and עונתו."},
    {"existing_claim_id": None,
     "change": "Add speech R. Yannai -> unnamed group (להו); habitual study scene at an unnamed study house; death of Yehuda; narrated causal link (utterance -> death) flagged literary.",
     "why": "F4, F6, F7."},
    {"existing_claim_id": None,
     "change": "Do not create child_of(Yehuda -> R. Yannai) from Yerushalmi יהודה ברי, a sibling edge from 62b:6, or temporal edges from segment order.",
     "why": "F9, F12, F14."},
]

LESSONS = [
    "Kinship terms like חתן/חמוה state a marriage without narrating it. The graph needs a spouse-edge provenance value 'implied by kinship term', separate from 'narrated wedding' and from 'marriage inferred from another passage'.",
    "An implied spouse needs a local placeholder even with zero mentions. The pronoun map should record the words that imply her (עונתו, מטתו) even though they refer to the husband.",
    "Unstated subjects of participles (הוה קא חזי) should be stored as an observer slot with competing fillers and who supplies each, not resolved silently.",
    "Forms of address (ברי 'my son', בניי 'my children') must be kept apart from kinship. Honorifics like בריבי must be kept apart from patronymics.",
    "A parallel in another Talmud is a separate passage reading. It can re-attest a relation but not merge scenes. Commentaries that harmonize one version with the other are commentary evidence, not text.",
    "Story chains ordered by theme (Rava's era before Rabbi's) must not generate before/after edges.",
    "Shared narrative formulas (יומא חד משכתיה שמעתא) are a signal of literary shaping and should be tagged.",
    "Arranged-but-unfinished matches (62b:7) need a status value distinct from marriage.",
]
