/**
 * Phase 3 (step 1) — generation as a Cloudflare Workflow.
 *
 * The cold-daf OOMs come from one invocation doing too much: a generation job
 * resolves a producer's whole dependency tree (and regenerates cold deps) in a
 * single 128 MB isolate. A Workflow decomposes that into checkpointed STEPS —
 * each `step.do(...)` is its own invocation with its own memory budget, so the
 * pile can't build up. This first step proves the model on an ADDITIVE warming
 * path (a new admin trigger) that warms a daf's whole-daf pieces one step each,
 * reusing the EXACT same generation function (`runEnrichmentOnce`) so it writes
 * byte-identical cache keys — it can't force a re-warm and doesn't touch the live
 * queue / run / reader paths.
 *
 * This module holds the pure, testable selection logic; the WorkflowEntrypoint
 * class lives in index.ts (where the generation internals are in scope).
 */

export interface MarkLike {
  id: string;
  anchor?: string;
}
export interface EnrichmentLike {
  id: string;
  scope?: string;
  target_mark?: string;
  /** Computed only on demand (e.g. a user-question `.qa`, or the lazy homonym
   *  pin) — never proactively warmed, so the warm Workflow skips it. */
  demand_driven?: boolean;
}

/**
 * The whole-daf enrichment ids a warm pass generates: those whose target mark is
 * whole-daf (or which declare no target mark). Same bucketing rule the daf-view
 * uses to separate whole-daf from per-instance pieces, so the two stay in sync.
 * Per-instance enrichments are intentionally excluded here (step 1 warms the
 * whole-daf surface; per-instance fan-out is a later step). Demand-driven
 * enrichments are skipped — they're generated only when a reader asks.
 */
export function wholeDafEnrichmentIds(marks: MarkLike[], enrichments: EnrichmentLike[]): string[] {
  const anchorById = new Map(marks.map((m) => [m.id, m.anchor]));
  return enrichments
    .filter((e) => e.scope === 'local' && !e.demand_driven)
    .filter((e) => !e.target_mark || anchorById.get(e.target_mark) === 'whole-daf')
    .map((e) => e.id);
}

/**
 * Per-instance local enrichments (one cached entry per target-mark instance):
 * scope local, target mark is NOT whole-daf, and NOT `argument` (its dual
 * display/synth instance shape needs separate handling — the same exclusion the
 * daf-view and /api/daf-runs carry). DEMAND-DRIVEN enrichments are skipped: a
 * user-question `.qa` or the lazy homonym pin is generated only when the reader
 * asks, so warming it Shas-wide is pure waste (and it can't be keyed without the
 * question). The warm Workflow generates one step per (enrichment, instance) for
 * what remains. Returns {id, targetMark} so the caller can read the instances.
 */
export function perInstanceEnrichments(
  marks: MarkLike[],
  enrichments: EnrichmentLike[],
): { id: string; targetMark: string }[] {
  const anchorById = new Map(marks.map((m) => [m.id, m.anchor]));
  return enrichments
    .filter((e) => e.scope === 'local' && !e.demand_driven)
    .filter(
      (e) =>
        !!e.target_mark &&
        e.target_mark !== 'argument' &&
        anchorById.get(e.target_mark) !== 'whole-daf',
    )
    .map((e) => ({ id: e.id, targetMark: e.target_mark as string }));
}

/** Params passed to the warm Workflow. */
export interface DafWarmParams {
  tractate: string;
  page: string;
  lang: 'en' | 'he';
}

/**
 * The single-flight sentinel key for /api/daf-generate. N concurrent readers of
 * the same daf+lang must compute the SAME key so they coalesce onto one in-flight
 * Workflow instead of starting N. Versioned (`v1`) so the format can evolve
 * without colliding with stale entries. Per (tractate, page, lang) — language is
 * part of the key because EN and HE generate distinct pieces. Kept byte-stable by
 * the test suite: a silent prefix/format change would break single-flight.
 */
export function dafGenSentinelKey(tractate: string, page: string, lang: 'en' | 'he'): string {
  return `dafgen:v1:${tractate}:${page}:${lang}`;
}

/**
 * Partition producer ids into dependency TIERS for parallel generation: tier 0 =
 * ids with no (in-set) dependency, tier 1 = ids whose deps are all in tier 0,
 * etc. Running a tier's steps concurrently is safe because every dependency is
 * already generated by an earlier tier — so parallelism never makes two steps
 * regenerate the same uncached dep. `depsOf(id)` returns that id's dependency
 * producer-ids; deps outside `ids` are ignored (satisfied by an earlier phase —
 * marks before whole-daf before per-instance). Self-deps are ignored. A cycle (or
 * an unresolved remainder) is emitted as a final tier rather than looping
 * forever. Deterministic (input order preserved within a tier) so Workflow step
 * names replay identically.
 */
export function topoTiers(ids: string[], depsOf: (id: string) => string[]): string[][] {
  const inSet = new Set(ids);
  const deps = new Map(
    ids.map((id) => [id, depsOf(id).filter((d) => inSet.has(d) && d !== id)] as const),
  );
  const done = new Set<string>();
  const tiers: string[][] = [];
  let remaining = ids.slice();
  while (remaining.length > 0) {
    const tier = remaining.filter((id) => (deps.get(id) ?? []).every((d) => done.has(d)));
    if (tier.length === 0) {
      tiers.push(remaining); // cycle / unresolved dep — don't loop forever
      break;
    }
    for (const id of tier) done.add(id);
    tiers.push(tier);
    remaining = remaining.filter((id) => !done.has(id));
  }
  return tiers;
}

/**
 * Expand dependency ids for the warm DAG: a dep the pool KNOWS passes through
 * unchanged, but a dep on a producer the warm never generates (today: the
 * excluded `argument` per-instance family) is replaced by that producer's
 * in-graph TRANSITIVE inputs — its target mark plus its own declared deps,
 * recursively. The dependent's run resolves the excluded producer INLINE
 * (regenerating it if uncached), and that inline walk reads the expanded
 * inputs; gating on them preserves the old phase-barrier guarantee (inline
 * regeneration only ever consumes already-cached pieces, so it can never race
 * a scheduled step over the same uncached dependency). Unknown non-producer
 * ids (source ids like 'gemara') expand to nothing, as before.
 */
export function expandInlineDeps(
  deps: string[],
  known: (id: string) => boolean,
  producerMeta: (id: string) => { targetMark?: string; deps: string[] } | undefined,
): string[] {
  const out: string[] = [];
  const seen = new Set<string>();
  const visit = (id: string): void => {
    if (seen.has(id)) return;
    seen.add(id);
    if (known(id)) {
      out.push(id);
      return;
    }
    const meta = producerMeta(id);
    if (!meta) return; // a source id — read from caches inline, nothing to gate
    if (meta.targetMark) visit(meta.targetMark);
    for (const d of meta.deps) visit(d);
  };
  for (const id of deps) visit(id);
  return out;
}

/**
 * Bounded-width dependency-DAG scheduler — the warm Workflow's step pump.
 *
 * Replaces the phase barriers (marks → whole-daf → per-instance) and the
 * per-tier chunked fan-out with ONE pool: every node starts the moment its OWN
 * declared dependencies are done and a slot is free, so no slot ever idles at a
 * batch, tier, or phase boundary. The width cap is unchanged (the caller passes
 * STEP_CONCURRENCY) — concurrent steps share the workflow isolate's 128 MB, so
 * the cap is a memory ceiling, not a scheduling choice.
 *
 * Semantics (strict — ordering is preserved exactly where a dependency exists):
 * - `add(id, deps, run)` registers a runnable node. Deps referencing ids the
 *   pool does not know (source ids like 'gemara', producers the warm never
 *   generates) are dropped — the same out-of-set rule topoTiers used; the
 *   runtime dependency walk resolves those inline as before.
 * - `declare(id)` registers a FUTURE node: anything depending on it waits until
 *   a later `add` fulfills it. Used for per-instance work that can only be
 *   enumerated after its target mark runs — a static node that depends on a
 *   per-instance enrichment (e.g. biyun.essay ← pesukim.synthesis) then waits
 *   for ALL of its units instead of regenerating them inline in one step.
 * - `add` with no `run` is a completion marker (a "group" node): it completes,
 *   without occupying a slot, once its deps are done.
 * - `add` may be called while draining (from inside a node's run) — that is how
 *   a mark fans out its per-instance units.
 * - A node failure stops new starts; in-flight nodes settle; drain() rejects.
 *   Dependents of a failed node never run.
 * - Deterministic: nodes are scanned in insertion order, names never depend on
 *   completion timing (Workflow replay caches steps by name).
 */
export interface DagPool {
  declare(id: string): void;
  add(id: string, deps: string[], run?: () => Promise<unknown>): void;
  /** Drain the pool; resolves when every declared+added node is done. Call once,
   *  after the static nodes are added. */
  drain(): Promise<void>;
}

interface DagNode {
  deps: string[];
  run?: () => Promise<unknown>;
  status: 'declared' | 'pending' | 'running' | 'done';
}

/**
 * Collapse a mark's instances to one entry per instance id (the value
 * `instanceIdOf` derives, which IS the per-instance cache key). The SAME
 * instance id legitimately surfaces more than once on a daf — e.g. a pasuk cited
 * by two different sections yields two `pesukim` instances that both resolve to
 * `leviticus_22_27`. They map to one cache key / one artifact, so the warm DAG
 * must fan out ONE node for them: a second `pool.add("<eid>::<iid>")` throws
 * `dag: duplicate node` and aborts the entire daf's generation (observed live on
 * Chullin 81, where every warm errored at DAG build before any AI ran).
 *
 * First-wins: the deduped instance drives the single node, matching the existing
 * cache-key semantics (both would have written the same key regardless).
 */
export async function dedupeInstancesByIid<T>(
  insts: readonly T[],
  iidOf: (inst: T) => Promise<string>,
): Promise<{ inst: T; iid: string }[]> {
  const out: { inst: T; iid: string }[] = [];
  const seen = new Set<string>();
  for (const inst of insts) {
    const iid = await iidOf(inst);
    if (seen.has(iid)) continue;
    seen.add(iid);
    out.push({ inst, iid });
  }
  return out;
}

export function createDagPool(limit: number): DagPool {
  const nodes = new Map<string, DagNode>();
  let inFlight = 0;
  let failure: unknown;
  let settle: { resolve: () => void; reject: (e: unknown) => void } | undefined;

  const isDone = (id: string): boolean => nodes.get(id)?.status === 'done';

  function declare(id: string): void {
    if (!nodes.has(id)) nodes.set(id, { deps: [], status: 'declared' });
  }

  function add(id: string, deps: string[], run?: () => Promise<unknown>): void {
    const existing = nodes.get(id);
    if (existing && existing.status !== 'declared') throw new Error(`dag: duplicate node ${id}`);
    const gated = deps.filter((d) => d !== id && nodes.has(d));
    nodes.set(id, { deps: gated, run, status: 'pending' });
    pump();
  }

  function start(n: DagNode): void {
    n.status = 'running';
    inFlight++;
    void (n.run as () => Promise<unknown>)().then(
      () => {
        n.status = 'done';
        inFlight--;
        pump();
      },
      (err: unknown) => {
        failure = failure ?? err ?? new Error('dag: node failed');
        inFlight--;
        pump();
      },
    );
  }

  function pump(): void {
    if (!settle) return; // not draining yet — pre-drain adds just register
    if (failure) {
      if (inFlight === 0) settle.reject(failure);
      return;
    }
    // Scan until a full pass makes no progress: complete free "group" markers,
    // start runnable nodes while a slot is open. Insertion order = determinism.
    let progressed = true;
    while (progressed) {
      progressed = false;
      for (const n of nodes.values()) {
        if (n.status !== 'pending' || !n.deps.every(isDone)) continue;
        if (!n.run) {
          n.status = 'done';
          progressed = true;
        } else if (inFlight < limit) {
          start(n);
          progressed = true;
        }
      }
    }
    if (inFlight > 0) return; // completions will re-pump
    const stuck: string[] = [];
    for (const [id, n] of nodes) if (n.status !== 'done') stuck.push(id);
    if (stuck.length === 0) settle.resolve();
    // Nothing running, nothing ready, nodes remain: an unfulfilled declare() or
    // an unsatisfiable dep. Fail loudly rather than hang the workflow.
    else
      settle.reject(
        new Error(
          `dag: stalled with ${stuck.length} unrunnable node(s): ${stuck.slice(0, 8).join(', ')}`,
        ),
      );
  }

  function drain(): Promise<void> {
    if (settle) return Promise.reject(new Error('dag: drain() called twice'));
    return new Promise<void>((resolve, reject) => {
      settle = { resolve, reject };
      pump();
    });
  }

  return { declare, add, drain };
}
