"""Frozen checks for contract source-investigation-v1.

Do not edit this file after a release names it. Changed behaviour belongs in a
new contract file, registered in followup_store.CONTRACTS."""

import hashlib
import html
import json
import re
from pathlib import PurePosixPath


def sha(data):
    return hashlib.sha256(data).hexdigest()


def leaves(value, pointer=""):
    if isinstance(value, str):
        yield pointer, value
    elif isinstance(value, list):
        for n, child in enumerate(value):
            yield from leaves(child, f"{pointer}/{n}")
    elif isinstance(value, dict):
        for key, child in value.items():
            part = str(key).replace("~", "~0").replace("/", "~1")
            yield from leaves(child, f"{pointer}/{part}")


def plain(text):
    return html.unescape(re.sub(r"<[^>]*>", "", text))


def spaces(text):
    return " ".join(plain(text).split())


def unpointed(text):
    return re.sub(r"[\u0591-\u05bd\u05bf-\u05c2\u05c4-\u05c5\u05c7]", "", spaces(text))


TRANSFORMS = (
    ("exact", lambda text: text),
    ("html_removed", plain),
    ("whitespace_normalized", spaces),
    ("hebrew_marks_removed", unpointed),
)


def is_binary(data):
    try:
        data.decode("utf-8")
        return False
    except UnicodeDecodeError:
        return True


def quote_matches(data, quote):
    raw = None
    try:
        candidates = list(leaves(json.loads(data)))
        raw = data.decode("utf-8")
    except (ValueError, UnicodeDecodeError):
        if is_binary(data):
            # An image or other binary source cannot hold a quotation.
            return {"mode": "not_found", "locations": []}
        candidates = [("", data.decode("utf-8"))]
    for mode, transform in TRANSFORMS:
        needle = transform(quote)
        if not needle:
            continue
        matches = []
        for pointer, text in candidates:
            target = transform(text)
            start = target.find(needle)
            while start >= 0:
                matches.append({"pointer": pointer, "start": start, "end": start + len(needle)})
                start = target.find(needle, start + 1)
        if matches:
            return {"mode": mode, "locations": matches,
                    "offset_scope": "Unicode characters in the named JSON string after the stated transformation; end exclusive."}
    if raw is not None:
        # The quote may span JSON structure, such as a search result's hit count.
        matches, start = [], raw.find(quote)
        while start >= 0:
            matches.append({"pointer": "", "start": start, "end": start + len(quote)})
            start = raw.find(quote, start + 1)
        if matches:
            return {"mode": "raw_file_text", "locations": matches,
                    "offset_scope": "Unicode characters in the whole saved file; end exclusive."}
    return {"mode": "not_found", "locations": []}


VISUAL_READING = "researcher_visual_reading_of_page_image"


def check(dossier, read_source):
    errors, warnings, citations = [], [], []
    if not isinstance(dossier, dict):
        return {"job_id": None, "valid": False, "errors": ["Dossier must be an object"], "warnings": [], "citations": []}
    for name in ("job_id", "focal_ref", "status", "question", "sources", "findings",
                 "alternative_readings", "unresolved", "proposed_corrections", "ontology_lessons"):
        if name not in dossier:
            errors.append(f"Missing field: {name}")
    sources = dossier.get("sources", [])
    findings = dossier.get("findings", [])
    if dossier.get("status") not in ("researched", "needs_more_context"):
        errors.append("Unknown research status")
    for name in ("job_id", "focal_ref", "question"):
        if not isinstance(dossier.get(name), str) or not dossier[name].strip():
            errors.append(f"Missing or non-text field: {name}")
    if not isinstance(sources, list) or not sources:
        errors.append("Sources must be a nonempty list")
        sources = []
    if not isinstance(findings, list) or not findings:
        errors.append("Findings must be a nonempty list")
        findings = []
    saved = {}
    for source in sources:
        if not isinstance(source, dict):
            errors.append("Source must be an object")
            continue
        sid = source.get("source_id")
        if not isinstance(sid, str) or not sid or sid in saved:
            errors.append(f"Missing or duplicate source ID: {sid}")
            continue
        if not any(isinstance(source.get(field), str) and source[field].strip() for field in ("url", "url_or_path", "url_or_input_path", "input_path", "source_url")):
            errors.append(f"Source has no address: {sid}")
        if not isinstance(source.get("edition"), str) or not source["edition"].strip():
            errors.append(f"Source has no edition: {sid}")
        if not isinstance(source.get("saved_file"), str) or not source["saved_file"]:
            errors.append(f"Source has no saved filename: {sid}")
        elif "\\" in source["saved_file"] or PurePosixPath(source["saved_file"]).is_absolute():
            errors.append(f"Source saved filename must be a relative path: {sid}")
        try:
            data = read_source(source)
            if sha(data) != source.get("sha256"):
                errors.append(f"Source hash differs: {sid}")
            saved[sid] = data
        except (OSError, ValueError, KeyError, TypeError) as error:
            errors.append(f"Cannot read source {sid}: {error}")
    ids = set()
    for finding in findings:
        if not isinstance(finding, dict):
            errors.append("Finding must be an object")
            continue
        fid = finding.get("finding_id")
        if not isinstance(fid, str) or not fid or fid in ids:
            errors.append(f"Missing or duplicate finding ID: {fid}")
            continue
        ids.add(fid)
        for field in ("claim", "kind", "reasoning", "confidence", "graph_effect"):
            if not isinstance(finding.get(field), str) or not finding[field].strip():
                errors.append(f"Finding {fid} has no {field}")
        if finding.get("kind") not in ("textual", "interpretation", "uncertainty"):
            errors.append(f"Finding {fid} has an unknown kind")
        if finding.get("confidence") not in ("high", "medium", "low"):
            errors.append(f"Finding {fid} has an unknown confidence label")
        evidence = finding.get("evidence", [])
        if not isinstance(evidence, list) or not evidence:
            errors.append(f"Finding {fid} has no quoted evidence")
            continue
        for n, item in enumerate(evidence):
            if not isinstance(item, dict):
                errors.append(f"Evidence must be an object: {fid}/{n}")
                continue
            sid, quote = item.get("source_id"), item.get("exact_quote")
            if not isinstance(sid, str) or sid not in saved or not isinstance(quote, str) or not quote:
                errors.append(f"Missing source or quote: {fid}/{n}")
                continue
            if len("".join(quote.split())) < 3:
                errors.append(f"Quotation is too short to locate: {fid}/{n}")
                continue
            match = quote_matches(saved[sid], quote)
            if match["mode"] == "not_found" and item.get("evidence_type") == VISUAL_READING and is_binary(saved[sid]):
                # A reader's transcription of a page photograph is recorded as such, never as a checked quote.
                match = {"mode": "visual_reading_unchecked", "locations": []}
                warnings.append(f"Visual reading of an image is not machine-checked: {fid}/{n}")
                if any(field in item for field in ("start", "end", "occurrences_in_segment", "occurrence", "source_pointer")):
                    errors.append(f"A visual reading cannot declare text offsets or counts: {fid}/{n}")
            citations.append({"finding_id": fid, "evidence_index": n, "source_id": sid,
                              "exact_quote": quote, **match})
            if match["mode"] == "visual_reading_unchecked":
                continue
            if match["mode"] == "not_found":
                errors.append(f"Quotation not found: {fid}/{n} in {sid}")
            elif match["mode"] == "hebrew_marks_removed":
                warnings.append(f"Quotation matches after removing Hebrew marks: {fid}/{n}")
            locations = match["locations"]
            if "source_pointer" in item:
                locations = [loc for loc in locations if loc["pointer"] == item["source_pointer"]]
                if not locations:
                    errors.append(f"Declared source field differs: {fid}/{n}")
            exact = None
            if "start" in item or "end" in item:
                if type(item.get("start")) is not int or type(item.get("end")) is not int or item["start"] < 0 or item["end"] <= item["start"]:
                    errors.append(f"Invalid quote offsets: {fid}/{n}")
                exact = [loc for loc in locations if loc["start"] == item.get("start") and loc["end"] == item.get("end")]
                if match["mode"] != "exact" or not exact:
                    errors.append(f"Declared quote offsets differ: {fid}/{n}")
                pointers = {loc["pointer"] for loc in exact}
                if len(pointers) == 1:
                    locations = [loc for loc in locations if loc["pointer"] in pointers]
            declared_occurrence = any(field in item for field in ("start", "end", "occurrences_in_segment", "occurrence"))
            if declared_occurrence and len({loc["pointer"] for loc in locations}) > 1:
                errors.append(f"Declared occurrence needs one source field; provide source_pointer: {fid}/{n}")
            if "occurrences_in_segment" in item:
                count = item["occurrences_in_segment"]
                if type(count) is not int or count < 1 or count != len(locations):
                    errors.append(f"Declared quotation count differs: {fid}/{n}")
            if "occurrence" in item:
                occurrence = item["occurrence"]
                if type(occurrence) is not int or occurrence < 1 or occurrence > len(locations) or (exact is not None and locations[occurrence-1] not in exact):
                    errors.append(f"Declared quote occurrence differs: {fid}/{n}")
    return {"job_id": dossier.get("job_id"), "valid": not errors, "errors": errors,
            "warnings": warnings, "source_count": len(sources), "finding_count": len(findings),
            "citations": citations,
            "limit": "Checks saved bytes and quotation matches. Does not establish the intended occurrence, correct interpretation, independent witnesses or historical truth."}
