"""Build dossier.json for challenge-11 from the saved sources, then check every quotation."""
import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).parent
sys.path.insert(0, str(HERE.parents[1]))
from validate import check_case  # noqa: E402

LOG = {e["saved_file"]: e for e in json.load(open(HERE / "sources/fetch_log.json")) if "saved_file" in e}
SEF = "https://www.sefaria.org/api/v3/texts/"


def src(sid, file, edition, note=None):
    path = HERE / file
    entry = LOG.get(file, {})
    item = {"source_id": sid, "url": entry.get("url"), "edition": edition,
            "fetched_at": entry.get("fetched_at"), "saved_file": file,
            "sha256": hashlib.sha256(path.read_bytes()).hexdigest()}
    if entry.get("post_body"):
        item["post_body"] = entry["post_body"]
    if note:
        item["note"] = note
    return item


PILOT = "../../../pilot/inputs/challenge-11.json"
sources = [
    {"source_id": "input", "input_path": "research/sage-network/pilot/inputs/challenge-11.json",
     "url_or_path": "research/sage-network/pilot/inputs/challenge-11.json",
     "edition": "Wikisource Talmud Bavli (frozen lake snapshot 2, as supplied to the pilot)",
     "saved_file": PILOT, "sha256": hashlib.sha256((HERE / PILOT).read_bytes()).hexdigest(),
     "note": "Frozen pilot input, read in place and not modified."},
    src("bavli_27b", "sources/sefaria_v3_berakhot_27b_all.json",
        "Sefaria v3, all versions of Berakhot 27b: William Davidson Edition (Aramaic, vocalized Aramaic, English); Wikisource Talmud Bavli; A. Cohen, Tractate Berakot, Cambridge 1921",
        "Davidson Aramaic, vocalized Aramaic and English, and the Steinsaltz Hebrew commentary, all come from one editorial project. They are not independent witnesses."),
    src("bavli_27a", "sources/sefaria_v3_berakhot_27a_all.json", "Sefaria v3, all versions of Berakhot 27a (same editions as bavli_27b)"),
    src("links_27b3", "sources/sefaria_links_berakhot_27b_3.json", "Sefaria links API for Berakhot 27b:3"),
    src("rashi_27b3", "sources/rashi_berakhot_27b_3.json", "Rashi on Berakhot 27b:3, Vilna Edition (Sefaria)"),
    src("tosafot_27b", "sources/tosafot_berakhot_27b.json", "Tosafot on Berakhot 27b, Vilna Edition (Sefaria)"),
    src("steinsaltz_27b", "sources/steinsaltz_berakhot_27b_1-4.json", "Steinsaltz on Berakhot 27b:1-4, William Davidson Edition - Hebrew (Sefaria)"),
    src("cohen_notes", "sources/cohen_footnotes_berakhot_27b_1-4.json", "A. Cohen, footnotes to Tractate Berakot, Cambridge 1921 (Sefaria)"),
    src("soncino", "sources/soncino_halakhah_com_berakoth_27.html", "Soncino English translation of Berakoth 27, as posted at halakhah.com"),
    src("jastrow", "sources/jastrow_chaver_1.json", "Jastrow, Dictionary, London 1903, entry חָבֵר (Sefaria)"),
    src("gilyon", "sources/gilyon_hashas_berakhot_27b.json", "Gilyon HaShas on Berakhot 27b, Vilna Edition (Sefaria)"),
    src("hag", "sources/halakhot_gedolot_1_25.json", "Halakhot Gedolot 1:25, Warsaw 1874 (Sefaria)",
        "A Geonic code that quotes the passage. Evidence type: early quotation, printed edition; not a manuscript of the Talmud."),
    src("sekhel_tov", "sources/sekhel_tov_shemot_16_29_272.json", "Midrash Sekhel Tov, Shemot 16:29, Berlin 1900-1901 (Sefaria)",
        "A medieval work that quotes the exchange for a legal point. Evidence type: later quotation."),
    src("rif", "sources/rif_berakhot_18b.json", "Rif Berakhot 18b, Vilna Edition (Sefaria)"),
    src("rosh_ber", "sources/rosh_berakhot_4_5.json", "Rosh on Berakhot 4:5, Vilna Edition (Sefaria)"),
    src("rosh_shab", "sources/rosh_shabbat_2_26.json", "Rosh on Shabbat 2:26, Vilna Edition (Sefaria)"),
    src("kol_bo", "sources/kol_bo_31_7.json", "Kol Bo 31:7, Venice 1547 (Sefaria)"),
    src("ramban_pes", "sources/ramban_pesachim_54b_1.json", "Chiddushei HaRamban on Pesachim 54b, Jerusalem 1928-29 (Sefaria)"),
    src("rambam", "sources/mishneh_torah_torah_study_5.json", "Mishneh Torah, Torah Study 5 (Torat Emet, Wikisource, Touger, Hyamson and other versions on Sefaria)"),
    src("sa_oc90", "sources/shulchan_arukh_oc_90_24-25.json", "Shulchan Arukh, Orach Chayim 90:24-25 (several Hebrew editions and a community English translation on Sefaria)"),
    src("taz", "sources/taz_yd_242_14.json", "Turei Zahav on Shulchan Arukh, Yoreh De'ah 242:14, Lemberg 1888 (Sefaria)"),
    src("bach", "sources/bach_yd_242_8.json", "Bach, Yoreh De'ah 242:8, Vilna 1923 (Sefaria)"),
    src("tzlach", "sources/tzlach_berakhot_27b.json", "Tziyyun LeNefesh Chayyah on Berakhot 27b, Prague 1791 (Sefaria)"),
    src("penei_y", "sources/penei_yehoshua_berakhot_27b.json", "Penei Yehoshua on Berakhot 27b, Warsaw 1861 (Sefaria)"),
    src("tos_kid", "sources/tosafot_kiddushin_46a_1_1.json", "Tosafot on Kiddushin 46a, Vilna Edition (Sefaria)"),
    src("tos_pes", "sources/tosafot_pesachim_106b_3_2.json", "Tosafot on Pesachim 106b, Vilna Edition (Sefaria)"),
    src("ritva_kid", "sources/ritva_kiddushin_46a_1.json", "Chiddushei HaRitva on Kiddushin 46a, Munkatch 1908 (Sefaria)"),
    src("rivash", "sources/rivash_271_4.json", "Teshuvot HaRivash 271, Vilna 1879 (Sefaria)"),
    src("kid_45b", "sources/sefaria_v3_kiddushin_45b_all.json", "Sefaria v3, all versions of Kiddushin 45b"),
    src("kid_46a", "sources/sefaria_v3_kiddushin_46a_all.json", "Sefaria v3, all versions of Kiddushin 46a"),
    src("pes_106b", "sources/sefaria_v3_pesachim_106b_all.json", "Sefaria v3, all versions of Pesachim 106b"),
    src("rashi_pes", "sources/rashi_pesachim_106b.json", "Rashi on Pesachim 106b, Vilna Edition (Sefaria)"),
    src("eruv_40b", "sources/sefaria_v3_eruvin_40b_all.json", "Sefaria v3, all versions of Eruvin 40b"),
    src("rashi_eruv", "sources/rashi_eruvin_40b.json", "Rashi on Eruvin 40b, Vilna Edition (Sefaria)"),
    src("rashash_ber", "sources/rashash_berakhot_27b.json", "Rashash on Berakhot 27b, Vilna Edition (Sefaria)"),
    src("bb_158b", "sources/sefaria_v3_bava_batra_158b_6.json", "Sefaria v3, all versions of Bava Batra 158b:6"),
    src("eruv_63a", "sources/sefaria_v3_eruvin_63a_3-4.json", "Sefaria v3, all versions of Eruvin 63a:3-4"),
    src("marit", "sources/marit_haayin_bava_batra_158b_1.json", "Marit HaAyin on Bava Batra 158b, Jerusalem 1960 (Sefaria)"),
    src("halakhot_ket", "sources/halakhot_ketanot_2_13_2.json", "Halakhot Ketanot, Part II 13:2, Krakow 1897 (Sefaria)"),
    src("maadaney", "sources/maadaney_yom_tov_berakhot_587.json", "Maadaney Yom Tov on Berakhot 587, Vilna Edition (Sefaria)"),
    src("search_mar", "sources/search_all_badil_mar.json", "Sefaria search API, exact phrase בדיל מר, all corpora (17 hits)",
        "Search index result. Shows where the phrase appears in Sefaria's indexed texts only."),
]

E = lambda sid, q: {"source_id": sid, "exact_quote": q}  # noqa: E731

findings = [
    {"finding_id": "f1", "kind": "textual", "confidence": "high",
     "claim": "The segment holds three different speech items. Rabbi Yirmiya bar Abba asks Rav a question. Someone, Rav by context, answers. Then the anonymous Talmud remarks that he did not say the formal wording 'has the Master separated'. Only the first two are reported utterances. The third reports a wording that was not used.",
     "evidence": [E("bavli_27b", "והיינו דקאמר ליה רבי ירמיה בר אבא לרב מי בדלת"),
                  E("bavli_27b", "אמר ליה אין בדילנא"),
                  E("bavli_27b", "ולא אמר מי בדיל מר"),
                  E("bavli_27b", "And Rabbi Yirmeya did not say to him: Did the Master distance himself, as would have been appropriate had he merely been Rav’s student."),
                  E("soncino", "and he did not say to him, Has the Master laid aside")],
     "reasoning": "My translation: 'And this is what Rabbi Yirmiya bar Abba said to Rav: Have you separated? He said to him: Yes, I have separated. And he did not say: Has the Master separated?' The question uses the second person (בדלת). The reply is first person (בדילנא). The third clause is negative and introduces a counterfactual wording in the third-person form of address (מר). All the checked witnesses share this three-part shape: the Wikisource Bavli, the Davidson Aramaic and English, the Cohen English and the Soncino English. The unsaid wording is content inside a negative report, not an event.",
     "graph_effect": "Keep the asks claim (Yirmiya to Rav, content 'have you separated') and the answer claim (Rav to Yirmiya, content 'yes, I have separated'). Add a third, separate record for the remark that the formal wording was not said. Mark it negative, give it the anonymous Talmud as voice, and make the counterfactual wording its content. Never turn the formal wording into an asks edge or into an 'addressed as Master' edge."},
    {"finding_id": "f2", "kind": "textual", "confidence": "high",
     "claim": "The student-colleague status comes from the anonymous Talmud, not from a narrator. It answers a difficulty ('Rabbi Yirmiya bar Abba is different'). The Talmud supports it by citing the exchange ('and this is why he said to him'). Rashi reads the missing formal wording as the proof.",
     "evidence": [E("bavli_27b", "שאני רבי ירמיה בר אבא דתלמיד חבר הוה"),
                  E("bavli_27a", "ורבי ירמיה היכי עביד הכי והא אמר רב יהודה אמר רב לעולם אל יתפלל אדם"),
                  E("rashi_27b3", "ולא אמר ליה מי בדיל מר – שמע מינה תלמיד חבר הוי ליה"),
                  E("bavli_27b", "he was not a mere student of Rav. Rather, he was a disciple-colleague")],
     "reasoning": "My translation: 'Rabbi Yirmiya bar Abba is different, for he was a student-colleague.' The word שאני marks an answer to the difficulty raised at 27a:17-27b:2. Rashi's translation (mine): 'And he did not say to him, has the Master separated: learn from this that he was a student-colleague to him.' So in the text the relation is a claim with its evidence attached. The narrator of the prayer story does not report it.",
     "graph_effect": "Change the voice of the student-colleague claim (earlier c14) from narrator to the anonymous Talmud's resolution. Record its basis as explicit statement plus a proof from the form of address. Link it to the negative speech record from f1 with a 'supported by' link. The inverse display (Rav as teacher-colleague of Yirmiya) is not a second observation."},
    {"finding_id": "f3", "kind": "textual", "confidence": "medium",
     "claim": "In the printed Talmud the other party is not named in the status sentence. Context supplies Rav. The Halakhot Gedolot quotation names Rav explicitly ('in relation to Rav'). Some later authors quote the sentence with Rav added.",
     "evidence": [E("bavli_27a", "והוה מצלי רבי ירמיה בר אבא לאחוריה דרב"),
                  E("hag", "שאני רב ירמיה בר אבא דתלמיד חבר הוה לגבי רב"),
                  E("bach", "דקמשני תלמודא שאני ר' ירמיה בר אבא דתלמיד חבר דרב הוה"),
                  E("jastrow", "who was a fellow (under Rab)")],
     "reasoning": "The difficulty is about praying behind one's teacher, and the only teacher in the scene is Rav, so the object is clear from context. Halakhot Gedolot is an early quotation carried in a printed code. It is a different kind of evidence from the Talmud editions. It is not a manuscript. The Bach and Taz quotations may be paraphrases. Jastrow's parenthesis is a lexicographer's gloss.",
     "graph_effect": "Keep Rav as the object. Mark it as supplied by context in the printed text, and as explicit in the Halakhot Gedolot quotation (a separate evidence type). Do not count the later quotations as more witnesses."},
    {"finding_id": "f4", "kind": "interpretation", "confidence": "medium",
     "claim": "The Talmud uses the status only to explain why Yirmiya could pray behind Rav. The later authorities who give its scope do not agree. Tosafot extends it to everything in Rabbi Eliezer's list. Maimonides defines it as someone who did not learn most of his wisdom from that teacher; such a person still stands up for him and tears his garment when he dies. The Shulchan Arukh codifies only the prayer permission. The Taz and the Bach draw a rule of speech from it: a student-colleague need not call the teacher 'Master'.",
     "evidence": [E("tosafot_27b", "ובתלמיד חבר דשרי ככל הני דלקמן"),
                  E("rambam", "אבל אם לא למד ממנו רוב חכמתו הרי זה תלמיד חבר ואינו חייב בכבודו בכל אלו הדברים"),
                  E("sa_oc90", "תלמיד חבר מותר להתפלל אחורי רבו"),
                  E("taz", "ובתלמיד חבר אין מוטל עליו להזכירו בשם מר כשמדבר עמו"),
                  E("penei_y", "והיינו משום דמסתמא תלמיד חבר רשאי לחלוק על רבו")],
     "reasoning": "These are later readings in their authors' own voices. Maimonides' definition, 'did not learn most of his wisdom from him', is not stated in Berakhot 27b. The relation still keeps a teacher side: the codes go on calling the other party רבו, 'his teacher'. Hyamson renders Maimonides as 'a junior to a senior fellow-student'. That is a translator's phrasing.",
     "graph_effect": "Keep the subtype student_colleague with fixed roles: Yirmiya is the student-colleague and Rav is the teacher. Do not flatten it to plain colleague or plain student. Do not add 'learned most of his wisdom from' or 'did not learn most of his wisdom from' as textual facts. Attach the Tosafot and Maimonides scopes as commentary notes, each under its own author."},
    {"finding_id": "f5", "kind": "interpretation", "confidence": "medium",
     "claim": "One commentator gives a further reason why the formal wording was not used. The Tziyyun LeNefesh Chayyah says Yirmiya cut his words short because he wanted to know at once whether Rav had accepted the Sabbath. It also says that addressing a full student's teacher this way would be real disrespect, so the proof still holds.",
     "evidence": [E("tzlach", "ור' ירמי' שלא אמר מר היינו משום שרצה לידע אם קיבל רב שבת בתפלתו"),
                  E("tzlach", "אבל בתלמיד גמור הוא אפקרותא ממש אם אומר לנוכח מי בדלת ושפיר הוכיח דר' ירמי' תלמיד חבר הוה")],
     "reasoning": "My translation: 'Rabbi Yirmiya did not say Master because he wanted to know whether Rav had accepted the Sabbath in his prayer'; 'but for a full student it is real disrespect to say to his face: have you separated; so the proof that Rabbi Yirmiya was a student-colleague is sound.' The same commentator says a student-colleague should still ideally say 'rabbi' when greeting. This softens how much the omission shows. It does not remove the proof.",
     "graph_effect": "Attach this as a commentary note on the negative speech record. It does not change any edge."},
    {"finding_id": "f6", "kind": "textual", "confidence": "medium",
     "claim": "Midrash Sekhel Tov quotes the question with the formal wording: 'Rabbi Yirmiya bar Abba said to Rav: Has the Master separated from work?' That is the opposite of the printed Talmud. Its quotation also places the exchange at Rav's visit to Geniva and does not mention the student-colleague point.",
     "evidence": [E("sekhel_tov", "תא שמע דרב איקלע לגבי גניבא צלי של שבת בערב שבת. אמר ליה ר' ירמי' בר אבא לרב מי בדיל מר ממלאכה אמר ליה בדילנא"),
                  E("hag", "ולא קאמר ליה מי בדיל מר"),
                  E("bavli_27b", "ולא אמר מי בדיל מר")],
     "reasoning": "Sekhel Tov quotes the story for a different legal point (whether one may make havdala early when the Ninth of Av falls on Sunday). It may paraphrase. The printed Talmud and the older Halakhot Gedolot quotation both have the negative remark. One later quotation cannot overturn them. Still, it is a real, different wording and should be kept as a separate evidence type.",
     "graph_effect": "No change to the Bavli reading. Record a quotation variant on the asks claim: 'Sekhel Tov quotes the question with the formal address.' Do not create a 'Yirmiya addressed Rav as Master' edge from it."},
    {"finding_id": "f7", "kind": "textual", "confidence": "high",
     "claim": "The questioner's title varies between Rabbi and Rav. The printed Berakhot has Rabbi Yirmiya bar Abba. The parallel citation in Eruvin 40b and the Halakhot Gedolot quotation have Rav Yirmiya bar Abba. Tosafot reports that most copies of Berakhot read Rav Yirmiya.",
     "evidence": [E("bavli_27b", "שאני רבי ירמיה בר אבא דתלמיד חבר הוה"),
                  E("eruv_40b", "דהאמר ליה רב ירמיה בר אבא לרב מי בדלת ואמר ליה אין בדילנא"),
                  E("hag", "דא\"ל רב ירמיה בר אבא לרב מי בדלת וא\"ל אין בדילנא"),
                  E("tos_pes", "בברכות גרסינן ברוב ספרים רב ירמיה ובקדושין רבי ירמיה")],
     "reasoning": "Tosafot's remark reports the manuscripts it knew. It is not a manuscript itself. Eruvin 40b is a parallel inside the Talmud that cites the same exchange for a different point. It lacks the negative remark about the formal wording, which says nothing about the Berakhot text.",
     "graph_effect": "Add 'רב ירמיה בר אבא' as an attested name form (alias) of the local Yirmiya entity. Keep the patronymic child_of claim and the local Abba placeholder unchanged. The title variant does not settle his historical identity."},
    {"finding_id": "f8", "kind": "uncertainty", "confidence": "medium",
     "claim": "Medieval authors did not agree on who this Yirmiya was, or on who his teacher was. In Kiddushin 46a a Rav Yirmiya bar Abba is called 'the student' next to Rav Huna. Tosafot raises the clash with Berakhot and suggests there were two sages called Rav Yirmiya. On Pesachim 106b Rashi takes 'his teacher' as Rav, while Tosafot considers Rav Huna. The Rivash calls Rabbi Yirmiya bar Abba a student of Rabbi Yochanan and says Rav was not his main teacher.",
     "evidence": [E("kid_46a", "נראין דברי תלמיד"),
                  E("kid_45b", "רב הונא אמר אינה אוכלת רב ירמיה בר אבא אמר אוכלת"),
                  E("tos_kid", "ונראה דתרי רב ירמיה הוו"),
                  E("ritva_kid", "לאו היינו רבי ירמיה דאמרי' בברכות"),
                  E("gilyon", "שם דתלמיד חבר הוה. עיין קדושין ד' מ\"ו ע\"א תוס' ד\"ה נראין"),
                  E("pes_106b", "שבקיה כרביה סבירא ליה"),
                  E("rashi_pes", "כרב דרב הונא משמיה דרב הוה אמר שמעתתיה"),
                  E("rivash", "דרבי ירמיה בר אבא תלמיד של רבי יוחנן"),
                  E("rivash", "אלא שלא היה רבו מובהק של רבי ירמיה בר אבא")],
     "reasoning": "These are identification hypotheses in their authors' voices. The Ritva on Kiddushin also says the Kiddushin figure is not the Yirmiya of Berakhot. His wording, as printed, is partly unclear. The Gilyon HaShas on Berakhot sends the reader to the Tosafot on Kiddushin. The Rivash's claim about Rabbi Yochanan is a later historical statement. I did not check it against the passage he cites. The Davidson English of Kiddushin 46a ('was like a student compared with Rav Huna') and of Pesachim 106b ('was a student of Rav') adds interpretations to the translation.",
     "graph_effect": "Do not merge the Berakhot Yirmiya bar Abba with the Kiddushin or Pesachim figure on the name alone. List these as provisional identity candidates with their proposers. Do not add a 'student of Rabbi Yochanan' or 'student of Rav Huna' edge from this passage."},
    {"finding_id": "f9", "kind": "interpretation", "confidence": "medium",
     "claim": "The Talmud does not say when the exchange happened. It only cites it ('and this is what he said to him'). Rashi on Berakhot puts it on the day Rav prayed the Sabbath prayer early. Rashi on Eruvin 40b puts it on a day when the sky was clouded over. The Rashash objects to that, because Rav's early prayer was deliberate. Sekhel Tov ties the exchange to the Geniva visit.",
     "evidence": [E("rashi_27b3", "אותו היום שהתפלל רב של שבת בערב שבת אמר ליה רבי ירמיה מי בדלת מן המלאכה"),
                  E("rashi_eruv", "פעם אחת נתקשרו שמים בעבים והתפלל רב של שבת מבעוד יום"),
                  E("rashash_ber", "ומעשה דרב הוה במתכוון"),
                  E("bavli_27b", "on one occasion, when Rav prayed the Shabbat prayer early")],
     "reasoning": "My translation of Rashi on Berakhot: 'that day on which Rav prayed the Sabbath prayer on Friday, Rabbi Yirmiya said to him...'. Rashi does not say explicitly that 'that day' is the Geniva visit. Soon after (27b), Rav Chiya bar Avin reports that Rav used to pray the Sabbath prayer early, so there may have been more than one such day. The Davidson English adds its framing without brackets.",
     "graph_effect": "Keep the exchange as its own event, separate from 'Rav arrives at Geniva's house' and from the prayer event. At most, add a provisional 'possibly same occasion' link, citing Sekhel Tov and possibly Rashi. Do not place the exchange at Geniva's house as a text fact."},
    {"finding_id": "f10", "kind": "textual", "confidence": "high",
     "claim": "The earlier inference 'a student may pray behind his teacher' (27a:15) is later narrowed. The objection from Rav's own rule, as taught by Rav Yehuda, is answered by making Yirmiya a special case. The codes forbid a student to pray behind his teacher but allow a student-colleague to do so.",
     "evidence": [E("bavli_27a", "ושמע מינה מתפלל תלמיד אחורי רבו"),
                  E("bavli_27b", "לא כנגד רבו ולא אחורי רבו"),
                  E("rambam", "ולא יתפלל לא לפני רבו ולא לאחר רבו ולא בצד רבו"),
                  E("sa_oc90", "תלמיד חבר מותר להתפלל אחורי רבו")],
     "reasoning": "The Talmud does not withdraw the inference outright, but the answer at 27b:3 limits it to a student-colleague. The earlier review noted that the three inferences were not tied to Rav's conduct. This is the link that ties the 'behind' inference to its qualification.",
     "graph_effect": "Link the 'a student may pray behind his teacher' statement to the scene as an inference, and mark it as qualified by the student-colleague resolution. Do not show it as a standing general rule in the Talmud's final voice."},
    {"finding_id": "f11", "kind": "interpretation", "confidence": "high",
     "claim": "Inferring student-colleague status from a form of address happens elsewhere too. In Bava Batra 158b Rabbi Shamlai infers that ben Azzai was Rabbi Akiva's student-colleague because he spoke to him in the second person. Later authors link that passage to ours. The Maadaney Yom Tov uses the same method to propose that Abaye was Rav Yosef's student-colleague. In Eruvin 63a Ravina claims the status for himself.",
     "evidence": [E("bb_158b", "אמר רבי שמלאי עדא אמרה בן עזאי תלמיד חבר דרבי עקיבא הוה דקאמר ליה שבאת"),
                  E("marit", "וכי האי גוונא אמרו פרק תפלת השחר"),
                  E("halakhot_ket", "ודייקינן התם מדלא א\"ל מי בדיל מר ש\"מ תלמיד חבר הוה"),
                  E("maadaney", "יש לי להוכיח מכאן דאביי תלמיד חבר דרב יוסף הוה"),
                  E("eruv_63a", "ואורי בשני דרב חסדא דתלמיד חבר דיליה הוה ואנא נמי תלמיד חבר דמר אנא")],
     "reasoning": "In Bava Batra a named sage makes the inference. In Berakhot the anonymous Talmud makes it. In Eruvin a party claims the status for himself. These are three different kinds of evidence for the same relation type. The Maadaney Yom Tov extension is a later author's inference about other people. Those relations belong to other passages.",
     "graph_effect": "For ontology only: treat 'status inferred from form of address' as a recognised basis. Add no edges for ben Azzai, Abaye or Ravina from this case."},
    {"finding_id": "f12", "kind": "textual", "confidence": "medium",
     "claim": "Halakhot Gedolot also quotes an extra detail: Yirmiya prayed a weekday prayer behind Rav. The Rif's digest leaves out the Geniva story and the exchange. It moves straight from the rule against praying behind one's teacher to Rav Chiya bar Avin's report.",
     "evidence": [E("hag", "וצלי רב ירמיה בר אבא אחוריה תפלה של חול"),
                  E("rif", "אמר רב יהודה אמר רב לעולם אל יתפלל תלמיד לא לפני רבו ולא אחורי רבו ולא כנגד רבו"),
                  E("rif", "אמר רב חייא בר אבין רב צלי של שבת בערב שבת")],
     "reasoning": "The Rif abridges for legal purposes, so leaving the story out is not evidence that his text lacked it. The 'weekday prayer' detail in Halakhot Gedolot belongs to the quotation, not to the printed Talmud.",
     "graph_effect": "Optional: add a note on Yirmiya's prayer event that one early quotation calls it a weekday prayer. The Rif's silence has no graph effect."},
    {"finding_id": "f13", "kind": "uncertainty", "confidence": "low",
     "claim": "Ramban's novellae on Pesachim 54b quote the exchange with different people: 'Rav said to Rabbi Chanina, who prayed the Sabbath prayer on Friday: Have you separated?'",
     "evidence": [E("ramban_pes", "אמר ליה רב לר' חנינא דצלי של שבת בערב שבת אמר מי בדלת אמר ליה אין בדילנא")],
     "reasoning": "This does not match any other witness I checked. It is probably a garbled quotation or a printing problem in that edition, but I cannot show that. It is a quotation variant, not a Talmud witness.",
     "graph_effect": "None. Keep only as a recorded quotation variant. Do not create a Rav and Chanina edge."},
    {"finding_id": "f14", "kind": "uncertainty", "confidence": "medium",
     "claim": "The modern vocalized edition and the Steinsaltz Hebrew both end 'and he did not say: has the Master separated' with a question mark, which may make it a rhetorical question. The Davidson English turns it into a plain statement. On either reading the formal wording was not said.",
     "evidence": [E("bavli_27b", "וְלָא אֲמַר ״מִי בְּדֵיל מָר״?"),
                  E("steinsaltz_27b", "ולא אמר אליו בלשון \"מי בדיל מר\" [\"האם בדל אדוני\"]? כדרך שהיה צריך לומר אם היה תלמידו.")],
     "reasoning": "The punctuation is a modern editorial choice, and all three renderings come from one editorial project. The unvocalized text has no punctuation.",
     "graph_effect": "None beyond f1. The negative polarity holds either way."},
    {"finding_id": "f15", "kind": "textual", "confidence": "medium",
     "claim": "In the surrounding text the names vary between witnesses and translations. At 27b:2 the teacher of the warning is Rabbi Eliezer (printed), Rabbi Elazar ben Chisma (Rif, Halakhot Gedolot), Rabbi Eliezer ben Chisma (Rosh) or R. Eleazar (Soncino). At 27b:4 the printed text has Rabbi Avin reporting about Rabbi (Rabbi Judah the Prince), with Rava answering. The Rosh quotes Rabbi Abbahu. The Soncino English has 'Rab' where the text has Rabbi. The Cohen English has 'Rab said' where the text has Rava.",
     "evidence": [E("bavli_27b", "ותניא רבי אליעזר אומר המתפלל אחורי רבו"),
                  E("rif", "תניא רבי אלעזר בן חסמא אומר"),
                  E("rosh_ber", "רבי אליעזר בן חסמא אומר"),
                  E("cohen_notes", "M. adds : b. Hisma ; but the correct form of the name is Eliezer Hisma."),
                  E("bavli_27b", "ומי בדיל והאמר רבי אבין פעם אחת התפלל רבי של שבת בערב שבת"),
                  E("rosh_shab", "והא אמר ר' אבהו פעם אחת התפלל ר' של שבת מערב שבת"),
                  E("soncino", "Has not R. Abin related that once Rab said the Sabbath Tefillah on the eve of Sabbath"),
                  E("bavli_27b", "Rab said : He must have gone into the bath-house only to perspire")],
     "reasoning": "Cohen's footnote reports that the Munich manuscript adds 'b. Hisma'. That is a report of a manuscript, which I did not see myself. The English variants may be translator or typesetting errors. They are not evidence about the Aramaic.",
     "graph_effect": "Record these as name variants on the existing Eliezer, Avin, Rabbi and Rava mentions. Do not move attributions on the strength of an English translation. These segments sit outside the focal question, so this is flagged for the wider episode."},
]

alternative_readings = [
    {"reading": "The printed Talmud (standard reading): Yirmiya asked in the second person, and the anonymous Talmud notes that he did not use the formal 'Master', which proves his student-colleague status.",
     "held_by": ["Rashi on Berakhot 27b:3", "Tosafot on Kiddushin 46a", "Halakhot Gedolot quotation", "Taz and Bach", "Davidson, Cohen and Soncino translations"],
     "evidence_source_ids": ["bavli_27b", "rashi_27b3", "tos_kid", "hag", "taz", "bach", "soncino"]},
    {"reading": "The question itself used the formal wording (Sekhel Tov's quotation).",
     "held_by": ["Midrash Sekhel Tov, Shemot 16:29 (a quotation, possibly a paraphrase)"],
     "evidence_source_ids": ["sekhel_tov"]},
    {"reading": "The formal wording was dropped partly out of haste to learn whether Rav had accepted the Sabbath. For a full student the short form would still be disrespect, so the proof holds.",
     "held_by": ["Tziyyun LeNefesh Chayyah"], "evidence_source_ids": ["tzlach"]},
    {"reading": "The exchange took place on the day of the Geniva visit, or on that same kind of day.",
     "held_by": ["Midrash Sekhel Tov (explicitly Geniva)", "Rashi on Berakhot ('that day'; he does not name Geniva)"],
     "evidence_source_ids": ["sekhel_tov", "rashi_27b3"]},
    {"reading": "The exchange took place on a cloudy day when Rav prayed early.",
     "held_by": ["Rashi on Eruvin 40b"], "challenged_by": ["Rashash on Berakhot 27b"],
     "evidence_source_ids": ["rashi_eruv", "rashash_ber"]},
    {"reading": "The Yirmiya who is Rav's student-colleague differs from the Yirmiya called Rav Huna's student in Kiddushin.",
     "held_by": ["Tosafot on Kiddushin 46a (two sages called Rav Yirmiya)"], "evidence_source_ids": ["tos_kid"]},
    {"reading": "Yirmiya bar Abba's main teacher was Rabbi Yochanan, and Rav was a teacher but not his main one.",
     "held_by": ["Rivash 271"], "evidence_source_ids": ["rivash"]},
]

unresolved = [
    "I did not see any manuscript of Berakhot 27b directly: not Munich 95, not the Genizah fragments, and not the Dikdukei Soferim or Hachi Garsinan collations. The name-title variant and the Sekhel Tov wording therefore stay unchecked against manuscripts. Cohen's footnotes report no Munich variant for 27b:3. A missing footnote does not show there is no variant.",
    "Whether Sekhel Tov's 'מי בדיל מר ממלאכה' reflects a different text or is a paraphrase.",
    "Whether 'that day' in Rashi means the Geniva visit.",
    "Whether the Berakhot, Eruvin 40b, Kiddushin 45b-46a and Pesachim 106b figures called Rav or Rabbi Yirmiya bar Abba are one person. This is a historical identification. Neither the shared name nor the title settles it.",
    "Whether Ramban's quotation at Pesachim 54b ('Rav said to Rabbi Chanina') has any textual basis.",
    "The Davidson Aramaic Berakhot has 'רבא' at 27b:4, while Cohen's English has 'Rab said'. I could not tell whether Cohen's base text differs or the English is an error.",
    "This research covers the Sefaria texts, links and search results that I saved, plus the Soncino page. It does not survey all rabbinic literature.",
]

proposed_corrections = [
    {"existing_claim_id": "c14", "change": "Keep predicate student_of, subtype student_colleague, subject Yirmiya and object Rav. Change the voice from narrator to the anonymous Talmud's resolution, answering the difficulty raised at 27a:17-27b:2. Change the basis to explicit statement plus a proof from the form of address. Mark the object as supplied by context in the printed text, and as explicit in the Halakhot Gedolot quotation. Add a 'supported by' link to the new negative speech record.",
     "why": "See f2 and f3. The status is argued, not narrated, and its proof is the missing formal wording."},
    {"existing_claim_id": None, "change": "New speech record: not_said. Speaker: Yirmiya (implied by the subject of ולא אמר). Addressee: Rav. Content: a new statement node for the counterfactual wording 'מי בדיל מר', 'has the Master separated?' (my translation). Polarity negative. Voice: the anonymous Talmud. Evidence: 'ולא אמר מי בדיל מר'. Function: evidence for c14. Notes: the Tziyyun LeNefesh Chayyah's haste explanation, and the Sekhel Tov variant wording.",
     "why": "See f1, f5 and f6. This negative speech evidence is the one the earlier review found missing."},
    {"existing_claim_id": "c15", "change": "Keep. Add notes: the Talmud cites this exchange as proof; the occasion is not dated (see f9); Eruvin 40b cites the same exchange with 'רב ירמיה'; Sekhel Tov's quotation has the formal wording. Keep the exchange as its own event, not merged into the Geniva visit.",
     "why": "See f6, f7 and f9."},
    {"existing_claim_id": "c16", "change": "Keep. Note that the speaker of 'אמר ליה אין בדילנא' is not named and is taken to be Rav from context. Every checked translation, Rashi and the Eruvin parallel agree.",
     "why": "See f1. The speaker is identified by inference, not named."},
    {"existing_claim_id": None, "change": "Tie the statement 'behind' ('a student may pray behind his teacher') to the scene as an inference. Mark it as qualified by c14: the permission is limited to a student-colleague. Do the same for 'early' (the Sabbath prayer on Friday). Its later challenge at 27b:4 is outside this case.",
     "why": "See f10. The earlier review noted these inferences were not tied to the scene."},
    {"existing_claim_id": None, "change": "Add the attested name form 'רב ירמיה בר אבא' (Eruvin 40b parallel, Halakhot Gedolot, Tosafot's report on most copies) to the local Yirmiya entity. Keep c1 (child_of Abba) and the Abba placeholder as they are.",
     "why": "See f7. The title variant is textual evidence. It does not decide identity."},
]

ontology_lessons = [
    "Model an expressly unsaid utterance ('X did not say W') as its own speech record with negative polarity and counterfactual content. It is neither an utterance nor mere silence. Its usual job in the Talmud is to serve as proof.",
    "A relation can be claimed with its proof attached. Store the resolving voice (here the anonymous Talmud) separately from the voice of the story. Store 'basis: proof from the form of address' separately from 'basis: narrated'.",
    "Student-colleague is a relation of its own, with fixed roles: the student-colleague and the teacher. It keeps a teaching side, since the codes still call the other party 'his teacher'. Collapsing it into plain student or plain colleague loses exactly what the passage turns on.",
    "Later scopes of a relation belong to the authors who give them, not to the passage. Examples: Tosafot's 'all the items in the list', Maimonides' 'did not learn most of his wisdom', the Taz's 'need not say Master'.",
    "An exchange that the Talmud cites as proof is not automatically the same occasion as the nearby story. Keep separate event nodes and let 'same occasion' be a sourced, provisional link.",
    "Quotations in later works (Halakhot Gedolot, Sekhel Tov, Ramban, Bach) are their own evidence type. They are neither manuscripts nor extra witnesses to the printed text. They can preserve a real variant, or they can paraphrase.",
    "Translations from one editorial project (Davidson Aramaic, vocalized text, English and Steinsaltz Hebrew) count as one witness to the edition, not three.",
]

dossier = {
    "job_id": "challenge-11",
    "focal_ref": "Berakhot 27b:3",
    "status": "researched",
    "question": "Preserve expressly unsaid speech: ולא אמר מי בדיל מר. Separate a formal question not asked from the exchange that actually occurs. Research student-colleague claims and their limits.",
    "scope": "Berakhot 27a:15-27b:4 in the Sefaria editions, the linked and quoted commentaries and codes saved in sources/, Talmudic parallels found by Sefaria exact-phrase search, and the Soncino English. No manuscripts were consulted directly.",
    "translation_note": "Translations marked 'My translation' in the reasoning fields are this dossier's own brief renderings. Published translations are quoted as published.",
    "sources": sources,
    "findings": findings,
    "alternative_readings": alternative_readings,
    "unresolved": unresolved,
    "proposed_corrections": proposed_corrections,
    "ontology_lessons": ontology_lessons,
}

out = HERE / "dossier.json"
out.write_text(json.dumps(dossier, ensure_ascii=False, indent=2) + "\n")
result = check_case(out)
print(json.dumps({"valid": result["valid"], "errors": result["errors"], "warnings": result["warnings"]}, ensure_ascii=False, indent=1))
