/**
 * Whole-daf geography map — two region cards (Eretz Yisrael + Bavel) drawn
 * from REAL projected geography (see geoShapes.ts, generated by
 * scripts/build-geo-shapes.ts): Natural Earth coastline, rivers (the
 * Euphrates/Tigris for Bavel, the Jordan + Kinneret + Dead Sea for Israel),
 * with city dots projected from real lat/lon.
 *
 * Data comes in pre-assembled as a DafGeoModel (geographyData.ts):
 * cached-only per-rabbi geography + the daf's `places` mark mentions. This
 * component never fetches and never spins — the caller renders it only when
 * the model has content.
 *
 * Visual language: city dots are gray and sized by on-daf mention count;
 * rabbi markers are generation-colored (GENERATION_BY_ID, same palette as
 * the timeline) and cluster sunflower-style around their city.
 */

import { createSignal, For, type JSX, Show } from 'solid-js';
import type {
  CityDot,
  DafGeoModel,
  GeoRabbi,
  MoveDirection,
  RabbiTrajectory,
  TrajectoryStop,
} from '../lib/geographyModel';
import { GENERATION_BY_ID, type GenerationId } from './generations';
import {
  BAVEL_SHAPE,
  GEO_CITIES,
  type GeoCity,
  type GeoRegionId,
  type GeoRegionShape,
  ISRAEL_SHAPE,
} from './geoShapes';
import { t } from './i18n';

export interface GeographyMapProps {
  model: DafGeoModel;
  /** Active city/region key ('_Israel' / '_Bavel' / a city name) — drives
   *  the active ring on dots. */
  activeLocation: string | null;
  onHighlightLocation: (cityName: string | null, rabbiNames: string[]) => void;
  /** Clicking a single rabbi dot highlights that rabbi (instead of everyone
   *  at the city). The registry slug rides along when known so the handler
   *  can open the RIGHT same-name homonym. */
  onHighlightSingleRabbi?: (rabbiName: string, slug?: string) => void;
  /** Transient hover highlight — rabbi name on mouseenter, null on leave. */
  onHoverRabbi?: (rabbiName: string | null) => void;
  /** Rabbi → generation map (the timeline palette) for dot coloring. */
  generationByName?: Map<string, GenerationId> | null;
  /** Clicking a mentioned-city dot highlights its name in the daf body. */
  onHighlightPlace?: (cityName: string | null) => void;
  activePlace?: string | null;
  /** 'row' (default) puts Israel + Bavel side-by-side; 'column' stacks. */
  layout?: 'row' | 'column';
}

const GEN_FALLBACK_COLOR = '#9ca3af';
const LAND_COLOR = '#6b7280';
const WATER_COLOR = '#3b82f6';
const WATER_FILL = 'rgba(96, 165, 250, 0.25)';
const CITY_COLOR = '#6b7280';

// Both region shapes share the same projected HEIGHT (180) but differ in WIDTH
// (Israel ~98.7, Bavel ~153.8). With one viewBox per shape + meet, the narrower
// Israel card rendered small and letterboxed. To make a MATCHED PAIR — equal
// box, comparable fill — every card uses ONE common aspect ratio (the widest
// shape's), and each shape is centered horizontally within it. City dots /
// rabbi markers are in shape-local coords, so this viewBox change is
// transparent to them. PAD is the breathing room around the bounds.
const PAD = 4;
const SHARED_HEIGHT = Math.max(ISRAEL_SHAPE.height, BAVEL_SHAPE.height);
const SHARED_WIDTH = Math.max(ISRAEL_SHAPE.width, BAVEL_SHAPE.width);

/** The viewBox for a shape, padded to the common aspect ratio with the shape
 *  centered (so both cards fill their equal boxes the same way). */
function sharedViewBox(shape: GeoRegionShape): string {
  const x0 = -PAD - (SHARED_WIDTH - shape.width) / 2;
  const y0 = -PAD - (SHARED_HEIGHT - shape.height) / 2;
  return `${x0} ${y0} ${SHARED_WIDTH + PAD * 2} ${SHARED_HEIGHT + PAD * 2}`;
}

// Stroke weights are in screen px (vector-effect: non-scaling-stroke) so the
// line weight is IDENTICAL across both cards regardless of each shape's local
// scale — without this, the smaller-rendered shape's strokes looked thinner.
const LAND_STROKE_PX = 1.2;
const RIVER_STROKE_PX = 0.9;
// City + rabbi dot radii are likewise normalized to apparent screen size. The
// shapes render at slightly different scales, so a shape-local radius would
// look bigger on one card; divide by the per-card render scale to keep dots the
// same apparent size on both. (The scale is the rendered px per viewBox unit;
// since the viewBox is shared, both cards scale identically, so a constant
// works — kept as named values for the renderer.)
const CITY_DOT_BASE = 1.6;
const CITY_DOT_PER_MENTION = 0.4;
const CITY_DOT_RABBI_ONLY = 1.3;
const RABBI_DOT_R = 2.6;

/**
 * N points around (cx, cy) in a sunflower spiral so co-located rabbi dots
 * don't overlap. Ring starts OFF-center (the city dot owns the center).
 */
function clusterOffsets(n: number, cx: number, cy: number): Array<{ x: number; y: number }> {
  const out: Array<{ x: number; y: number }> = [];
  const GOLDEN = Math.PI * (3 - Math.sqrt(5));
  const scale = 2.6;
  for (let i = 1; i <= n; i++) {
    const r = scale * Math.sqrt(i);
    const theta = i * GOLDEN;
    out.push({ x: cx + r * Math.cos(theta), y: cy + r * Math.sin(theta) });
  }
  return out;
}

/** Centroid of a region's cities — where the "region known, city unknown"
 *  cluster lands. */
function regionCentroid(region: 'israel' | 'bavel'): { x: number; y: number } {
  const cities = GEO_CITIES.filter((c) => c.region === region);
  let x = 0;
  let y = 0;
  for (const c of cities) {
    x += c.x;
    y += c.y;
  }
  return { x: x / cities.length, y: y / cities.length };
}

const CITY_BY_NAME = new Map<string, GeoCity>(GEO_CITIES.map((c) => [c.name, c]));

// Trajectory drill-down visuals: a numbered path the selected rabbi walked.
const TRAJ_COLOR = '#7c3aed'; // violet — distinct from the gen-colored dots
const DIMMED_OPACITY = 0.18;

/** Region tint for the inline trajectory list (matches the daf-count colors:
 *  Bavel amber, Eretz Yisrael dark, unknown gray). */
function regionTint(r: GeoRegionId | null): string {
  if (r === 'bavel') return '#92400e';
  if (r === 'israel') return '#1f2937';
  return '#6b7280';
}

/** Shape-local position of a trajectory stop: its city coords when the place
 *  matched a known city, else the region centroid (the same place the
 *  "city unknown" cluster sits), else null (no region → unplottable). */
function stopPosition(stop: TrajectoryStop): { x: number; y: number } | null {
  if (stop.cityName) {
    const c = CITY_BY_NAME.get(stop.cityName);
    if (c) return { x: c.x, y: c.y };
  }
  if (stop.region === 'israel' || stop.region === 'bavel') return regionCentroid(stop.region);
  return null;
}

/** A positioned, numbered stop (the index in the full ordered trajectory). */
interface PlacedStop {
  stop: TrajectoryStop;
  num: number;
  pos: { x: number; y: number } | null;
}

export function GeographyMap(props: GeographyMapProps): JSX.Element {
  const [hoveredMoverRow, setHoveredMoverRow] = createSignal<string | null>(null);
  // Drill-down: the rabbi whose life path is being traced. Clicking a rabbi
  // dot or a migration row selects them (and still fires the daf-text
  // highlight); clicking the same one again, or [clear], or a region, resets.
  const [selected, setSelected] = createSignal<{ name: string; slug: string | null } | null>(null);

  const selectedTrajectory = (): RabbiTrajectory | null => {
    const sel = selected();
    if (!sel) return null;
    const trs = props.model.trajectories ?? [];
    // A slugged selection matches ONLY by slug (homonym-safe — never fall back
    // to a name match, which could draw a same-name rabbi's path). Only the
    // ungrounded case (no slug) keys on the display name, as the dots do.
    if (sel.slug) return trs.find((tr) => tr.slug === sel.slug) ?? null;
    return trs.find((tr) => tr.name === sel.name) ?? null;
  };

  /** The selected rabbi's stops, numbered in life order, each positioned.
   *  Consecutive stops that resolve to the SAME spot (e.g. studied AND was a
   *  notable authority in Sura) collapse to one numbered node so badges don't
   *  stack illegibly; a later RETURN to an earlier place stays a distinct node. */
  const placedStops = (): PlacedStop[] => {
    const tr = selectedTrajectory();
    if (!tr) return [];
    const out: PlacedStop[] = [];
    let lastKey: string | null = null;
    let num = 0;
    for (const stop of tr.stops) {
      const pos = stopPosition(stop);
      const key = pos ? `${Math.round(pos.x * 10)},${Math.round(pos.y * 10)}` : `np:${stop.place}`;
      if (key === lastKey && out.length > 0) continue;
      lastKey = key;
      out.push({ stop, num: ++num, pos });
    }
    return out;
  };

  // Active drill-down only when the selected rabbi has at least one stop we can
  // actually plot — otherwise selecting would dim the maps with nothing drawn.
  const drilling = (): boolean => placedStops().some((p) => p.pos !== null);

  const pickRabbi = (name: string, slug?: string) => {
    const cur = selected();
    const same = cur && cur.name === name && (cur.slug ?? null) === (slug ?? null);
    setSelected(same ? null : { name, slug: slug ?? null });
    props.onHighlightSingleRabbi?.(name, slug);
  };

  const onCityClick = (d: CityDot) => {
    const isActive = props.activeLocation === d.city.name;
    props.onHighlightLocation(
      isActive ? null : d.city.name,
      d.rabbis.map((r) => r.name),
    );
  };

  const onRegionClick = (region: 'israel' | 'bavel') => {
    const m = props.model;
    const list = m.dots
      .filter((d) => d.city.region === region)
      .flatMap((d) => d.rabbis.map((r) => r.name));
    list.push(
      ...(region === 'israel' ? m.unspecifiedIsrael : m.unspecifiedBavel).map((r) => r.name),
    );
    const key = region === 'israel' ? '_Israel' : '_Bavel';
    const isActive = props.activeLocation === key;
    setSelected(null); // region highlight is a different mode than tracing one rabbi
    props.onHighlightLocation(isActive ? null : key, list);
  };

  const rabbiDot = (rabbi: GeoRabbi, x: number, y: number, cityLabel: string): JSX.Element => {
    const name = rabbi.name;
    const gen = props.generationByName?.get(name);
    const genInfo = gen ? GENERATION_BY_ID[gen] : undefined;
    const activate = () => pickRabbi(name, rabbi.slug ?? undefined);
    return (
      // biome-ignore lint/a11y/useSemanticElements: native <button> cannot be used inside an SVG map
      <circle
        cx={x}
        cy={y}
        r={RABBI_DOT_R}
        fill={genInfo?.color ?? GEN_FALLBACK_COLOR}
        stroke="rgba(0,0,0,0.3)"
        stroke-width={0.8}
        vector-effect="non-scaling-stroke"
        style={{ cursor: props.onHighlightSingleRabbi ? 'pointer' : 'default' }}
        role="button"
        tabindex={0}
        onClick={(e) => {
          e.stopPropagation();
          activate();
        }}
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault();
            activate();
          }
        }}
        onMouseEnter={() => props.onHoverRabbi?.(name)}
        onMouseLeave={() => props.onHoverRabbi?.(null)}
      >
        <title>{`${name} · ${cityLabel}${genInfo ? ` · ${genInfo.label}` : ''}`}</title>
      </circle>
    );
  };

  const renderCityDot = (d: CityDot): JSX.Element => {
    const activeCity = () => props.activeLocation === d.city.name;
    // The daf's .city-marker spans carry the RAW mark name (data-city), so
    // active-state + click must use d.mentionNames, not the canonical name
    // (a daf saying "Sepphoris" lights the Tzipori dot).
    const activeMention = () =>
      props.activePlace !== null &&
      props.activePlace !== undefined &&
      d.mentionNames.includes(props.activePlace);
    const mentioned = d.mentions > 0;
    // City dot sized by on-daf mention count; a rabbi-only city gets a small
    // anchor dot. (Radii are shape-local; both cards share one viewBox scale,
    // so a given radius reads the same apparent size on both.)
    const r = mentioned
      ? CITY_DOT_BASE + CITY_DOT_PER_MENTION * Math.min(d.mentions, 6)
      : CITY_DOT_RABBI_ONLY;
    const cityLabel = `${d.city.name} (${d.city.nameHe})${d.city.approx ? ' ~' : ''}`;
    const offsets = clusterOffsets(d.rabbis.length, d.city.x, d.city.y);
    const clickCity = () => {
      // A mentioned city's dot drives the in-text place highlight (the
      // rabbis at the city stay reachable through their own dots and the
      // region hit-box); a rabbi-only city highlights its rabbis.
      if (d.mentionNames.length > 0 && props.onHighlightPlace) {
        props.onHighlightPlace(activeMention() ? null : d.mentionNames[0]);
      } else {
        onCityClick(d);
      }
    };
    return (
      <g>
        {/* biome-ignore lint/a11y/useSemanticElements: native <button> cannot be used inside an SVG map */}
        <circle
          cx={d.city.x}
          cy={d.city.y}
          r={r}
          fill={mentioned ? CITY_COLOR : '#9ca3af'}
          stroke={activeCity() || activeMention() ? '#000' : 'rgba(0,0,0,0.25)'}
          stroke-width={activeCity() || activeMention() ? 1.6 : 0.8}
          vector-effect="non-scaling-stroke"
          style={{ cursor: 'pointer' }}
          role="button"
          tabindex={0}
          onClick={(e) => {
            e.stopPropagation();
            clickCity();
          }}
          onKeyDown={(e) => {
            if (e.key === 'Enter' || e.key === ' ') {
              e.preventDefault();
              clickCity();
            }
          }}
        >
          <title>{mentioned ? `${cityLabel} · ${t('geography.mentionedInDaf')}` : cityLabel}</title>
        </circle>
        <For each={d.rabbis}>
          {(rabbi, i) => {
            const off = offsets[i()];
            return rabbiDot(rabbi, off.x, off.y, cityLabel);
          }}
        </For>
      </g>
    );
  };

  const renderUnspecified = (region: 'israel' | 'bavel', rabbis: GeoRabbi[]): JSX.Element => {
    const c = regionCentroid(region);
    const offsets = clusterOffsets(rabbis.length, c.x, c.y);
    const label =
      region === 'israel'
        ? `${t('geography.eretzYisrael')} · ${t('geography.cityUnknown')}`
        : `${t('geography.bavel')} · ${t('geography.cityUnknown')}`;
    return (
      <g opacity={0.85}>
        <For each={rabbis}>
          {(rabbi, i) => {
            const off = offsets[i()];
            return rabbiDot(rabbi, off.x, off.y, label);
          }}
        </For>
      </g>
    );
  };

  // One arrow segment of the trajectory path: a violet line + arrowhead, drawn
  // shape-local. Endpoints are pulled in by ENDR so they touch the badge edges,
  // not their centers.
  const arrowSeg = (a: { x: number; y: number }, b: { x: number; y: number }): JSX.Element => {
    const dx = b.x - a.x;
    const dy = b.y - a.y;
    const len = Math.hypot(dx, dy) || 1;
    const ux = dx / len;
    const uy = dy / len;
    const ENDR = 3.4; // stop short of the badge circle (r≈3.2)
    const sx = a.x + ux * ENDR;
    const sy = a.y + uy * ENDR;
    const ex = b.x - ux * ENDR;
    const ey = b.y - uy * ENDR;
    const h = 2.0; // arrowhead length
    const w = 1.2; // arrowhead half-width
    const ax1 = ex - ux * h - uy * w;
    const ay1 = ey - uy * h + ux * w;
    const ax2 = ex - ux * h + uy * w;
    const ay2 = ey - uy * h - ux * w;
    return (
      <g>
        <line
          x1={sx}
          y1={sy}
          x2={ex}
          y2={ey}
          stroke={TRAJ_COLOR}
          stroke-width={1.1}
          vector-effect="non-scaling-stroke"
          stroke-linecap="round"
          opacity={0.9}
        />
        <polygon
          points={`${ex},${ey} ${ax1},${ay1} ${ax2},${ay2}`}
          fill={TRAJ_COLOR}
          opacity={0.9}
        />
      </g>
    );
  };

  // The numbered path overlay for one region: arrows between consecutive
  // same-region stops, then a numbered badge at each positioned stop. Drawn on
  // top of the (dimmed) dots. Returns null when not drilling.
  const trajectoryOverlay = (region: 'israel' | 'bavel'): JSX.Element => {
    const all = placedStops();
    const segs: Array<{ a: { x: number; y: number }; b: { x: number; y: number } }> = [];
    for (let i = 0; i < all.length - 1; i++) {
      const a = all[i];
      const b = all[i + 1];
      if (a.pos && b.pos && a.stop.region === region && b.stop.region === region) {
        segs.push({ a: a.pos, b: b.pos });
      }
    }
    const badges = all.filter((p) => p.pos && p.stop.region === region);
    return (
      <g style={{ 'pointer-events': 'none' }}>
        <For each={segs}>{(s) => arrowSeg(s.a, s.b)}</For>
        <For each={badges}>
          {(p) => (
            <g>
              <circle
                cx={p.pos!.x}
                cy={p.pos!.y}
                r={3.2}
                fill={TRAJ_COLOR}
                stroke="#fff"
                stroke-width={0.9}
                vector-effect="non-scaling-stroke"
              />
              <text
                x={p.pos!.x}
                y={p.pos!.y}
                text-anchor="middle"
                dominant-baseline="central"
                font-size="3.4"
                font-weight="700"
                fill="#fff"
              >
                {p.num}
              </text>
            </g>
          )}
        </For>
      </g>
    );
  };

  const regionCard = (
    region: 'israel' | 'bavel',
    shape: GeoRegionShape,
    heading: string,
    headingColor: string,
    aria: string,
    extras?: JSX.Element,
  ): JSX.Element => (
    <div
      style={{
        flex: 1,
        border: props.layout === 'column' ? 'none' : '1px solid #e5e7eb',
        'border-radius': props.layout === 'column' ? '0' : '8px',
        background: props.layout === 'column' ? 'transparent' : '#fff',
        padding: '0.5rem 0.5rem 0.4rem',
        display: 'flex',
        'flex-direction': 'column',
        'align-items': 'center',
        'min-width': 0,
      }}
    >
      <div
        style={{
          'font-size': '0.8rem',
          'font-weight': 600,
          color: headingColor,
          'margin-bottom': '0.3rem',
        }}
      >
        {heading}
      </div>
      <svg
        viewBox={sharedViewBox(shape)}
        style={{ width: '100%', flex: 1, display: 'block', 'min-height': 0 }}
        preserveAspectRatio="xMidYMid meet"
        role="img"
        aria-label={aria}
      >
        {/* Invisible hit-box: a click anywhere in the card selects the region.
            Spans the full shared viewBox (not the tight shape bounds) so the
            padding around a narrow shape is still clickable. */}
        {/* biome-ignore lint/a11y/useSemanticElements: native <button> cannot be used inside an SVG map */}
        <rect
          x={-PAD - (SHARED_WIDTH - shape.width) / 2}
          y={-PAD - (SHARED_HEIGHT - shape.height) / 2}
          width={SHARED_WIDTH + PAD * 2}
          height={SHARED_HEIGHT + PAD * 2}
          fill="transparent"
          style={{ cursor: 'pointer' }}
          role="button"
          tabindex={0}
          aria-label={heading}
          onClick={() => onRegionClick(region)}
          onKeyDown={(e) => {
            if (e.key === 'Enter' || e.key === ' ') {
              e.preventDefault();
              onRegionClick(region);
            }
          }}
        />
        {/* Water under land: rivers as thin blue lines; closed rings (the
            Kinneret / Dead Sea) get a light fill. */}
        <For each={shape.riverPaths}>
          {(d) => (
            <path
              d={d}
              fill={d.endsWith('Z') ? WATER_FILL : 'none'}
              stroke={WATER_COLOR}
              stroke-width={RIVER_STROKE_PX}
              vector-effect="non-scaling-stroke"
              stroke-linecap="round"
              stroke-linejoin="round"
              opacity={0.75}
            />
          )}
        </For>
        <For each={shape.landPaths}>
          {(d) => (
            <path
              d={d}
              fill="none"
              stroke={LAND_COLOR}
              stroke-width={LAND_STROKE_PX}
              vector-effect="non-scaling-stroke"
              stroke-linecap="round"
              stroke-linejoin="round"
              opacity={0.85}
            />
          )}
        </For>
        {extras}
        {/* Dots dim while tracing one rabbi's path so the numbered trajectory
            (drawn on top) reads clearly. */}
        <g opacity={drilling() ? DIMMED_OPACITY : 1}>
          <For each={props.model.dots.filter((d) => d.city.region === region)}>
            {(d) => renderCityDot(d)}
          </For>
          {renderUnspecified(
            region,
            region === 'israel' ? props.model.unspecifiedIsrael : props.model.unspecifiedBavel,
          )}
        </g>
        <Show when={drilling()}>{trajectoryOverlay(region)}</Show>
      </svg>
    </div>
  );

  // River name labels for the Bavel card, positioned where the generated
  // paths enter the window (Tigris from the top edge, Euphrates from the
  // west edge) — eyeballed against the projected data, in viewBox units.
  const bavelLabels = (
    <>
      <text
        x={34}
        y={9}
        font-family="Georgia,serif"
        font-size="6.5"
        font-style="italic"
        fill="#1e40af"
        opacity={0.85}
      >
        {t('geography.tigris')}
      </text>
      <text
        x={5}
        y={60}
        font-family="Georgia,serif"
        font-size="6.5"
        font-style="italic"
        fill="#1e40af"
        opacity={0.85}
      >
        {t('geography.euphrates')}
      </text>
    </>
  );

  return (
    <section
      style={{
        padding: '0.75rem 0.75rem 0.5rem',
        border: '1px solid #eee',
        'border-radius': '6px',
        background: '#fcfcfa',
        'font-family': 'system-ui, -apple-system, sans-serif',
        'font-size': '0.8rem',
        color: '#555',
      }}
    >
      <div
        style={{
          color: '#999',
          'font-size': '0.72rem',
          'margin-bottom': '0.35rem',
          'text-transform': 'uppercase',
          'letter-spacing': '0.06em',
        }}
      >
        {t('geography.heading')}
      </div>

      <div
        style={{
          display: 'flex',
          'flex-direction': props.layout === 'column' ? 'column' : 'row',
          gap: '0.5rem',
          'align-items': 'stretch',
        }}
      >
        {regionCard(
          'israel',
          ISRAEL_SHAPE,
          t('geography.eretzYisrael'),
          '#1f2937',
          t('geography.eretzYisrael.aria'),
        )}
        {regionCard(
          'bavel',
          BAVEL_SHAPE,
          t('geography.bavel'),
          '#1e40af',
          t('geography.bavel.aria'),
          bavelLabels,
        )}
      </div>

      {/* Discovery hint — only when paths exist and none is being traced. */}
      <Show when={!drilling() && (props.model.trajectories?.length ?? 0) > 0}>
        <div
          style={{
            'margin-top': '0.3rem',
            'font-size': '0.68rem',
            'font-style': 'italic',
            color: '#999',
          }}
        >
          {t('geography.trajectory.hint')}
        </div>
      </Show>

      {/* Drill-down panel: the selected rabbi's numbered path as a list. The
          numbers match the badges on the maps above. */}
      <Show when={drilling()}>
        <div
          style={{
            'margin-top': '0.45rem',
            padding: '0.45rem 0.55rem',
            border: `1px solid ${TRAJ_COLOR}33`,
            'border-radius': '6px',
            background: `${TRAJ_COLOR}0d`,
          }}
        >
          <div
            style={{
              display: 'flex',
              'align-items': 'center',
              'justify-content': 'space-between',
              gap: '0.5rem',
              'margin-bottom': '0.35rem',
            }}
          >
            <span style={{ 'font-weight': 700, color: '#333', 'font-size': '0.84rem' }}>
              {selected()?.name}
            </span>
            <button
              type="button"
              onClick={() => setSelected(null)}
              style={{
                border: 'none',
                background: 'transparent',
                color: TRAJ_COLOR,
                cursor: 'pointer',
                'font-size': '0.72rem',
                'font-family': 'inherit',
                padding: '0.1rem 0.2rem',
              }}
            >
              ✕ {t('geography.trajectory.clear')}
            </button>
          </div>
          <ol
            style={{
              'list-style': 'none',
              margin: 0,
              padding: 0,
              display: 'flex',
              'flex-direction': 'column',
              gap: '0.25rem',
            }}
          >
            <For each={placedStops()}>
              {(p) => (
                <li style={{ display: 'flex', 'align-items': 'baseline', gap: '0.4rem' }}>
                  <span
                    style={{
                      'flex-shrink': 0,
                      width: '1.1rem',
                      height: '1.1rem',
                      'border-radius': '50%',
                      background: p.pos ? TRAJ_COLOR : '#cbd5e1',
                      color: '#fff',
                      'font-size': '0.62rem',
                      'font-weight': 700,
                      display: 'inline-flex',
                      'align-items': 'center',
                      'justify-content': 'center',
                    }}
                  >
                    {p.num}
                  </span>
                  <span style={{ 'font-size': '0.82rem' }}>
                    <span style={{ 'font-weight': 600, color: '#222' }}>{p.stop.place}</span>{' '}
                    <span style={{ color: regionTint(p.stop.region), 'font-size': '0.66rem' }}>
                      {t(`rabbi.places.kind.${p.stop.kind}`)}
                    </span>
                    <Show when={p.stop.detail}>
                      <span style={{ color: '#777', 'font-size': '0.74rem' }}>
                        {' · '}
                        {p.stop.detail}
                      </span>
                    </Show>
                  </span>
                </li>
              )}
            </For>
          </ol>
        </div>
      </Show>

      <div
        style={{
          display: 'flex',
          'justify-content': 'space-between',
          'align-items': 'center',
          'margin-top': '0.3rem',
          'font-size': '0.78rem',
          color: '#555',
        }}
      >
        <span>
          {t('geography.eretzYisrael')}:{' '}
          <strong style={{ color: '#1f2937' }}>{props.model.israelCount}</strong>
        </span>
        <span>
          {t('geography.bavel')}:{' '}
          <strong style={{ color: '#92400e' }}>{props.model.bavelCount}</strong>
        </span>
      </div>

      <Show when={props.model.moverRows.length > 0}>
        <div
          style={{
            'margin-top': '0.45rem',
            'padding-top': '0.4rem',
            'border-top': '1px dashed #e5e7eb',
            'font-size': '0.72rem',
            color: '#555',
            display: 'flex',
            'flex-direction': 'column',
            gap: '0.15rem',
          }}
        >
          <div
            style={{
              color: '#6b7280',
              'font-size': '0.64rem',
              'text-transform': 'uppercase',
              'letter-spacing': '0.06em',
              'margin-bottom': '0.15rem',
            }}
          >
            {t('geography.migration')}
          </div>
          <For each={props.model.moverRows}>
            {(row) => {
              const hovered = () => hoveredMoverRow() === row.name;
              const onEnter = () => {
                setHoveredMoverRow(row.name);
                props.onHoverRabbi?.(row.name);
              };
              const onLeave = () => {
                setHoveredMoverRow(null);
                props.onHoverRabbi?.(null);
              };
              // Single-letter region tags so the whole row fits on one line
              // in a ~220px strip. "B" = Bavel (amber), "E" = Eretz Yisrael
              // (gray). Full names live in the title attribute.
              const fromB = row.direction === 'bavel->israel';
              const fromLabel = fromB ? 'B' : 'E';
              const toLabel = fromB ? 'E' : 'B';
              const fromColor = fromB ? '#92400e' : '#1f2937';
              const toColor = fromB ? '#1f2937' : '#92400e';
              const fromFull = fromB ? t('geography.bavel') : t('geography.eretzYisrael');
              const toFull = fromB ? t('geography.eretzYisrael') : t('geography.bavel');
              const arrow: Record<MoveDirection, string> = {
                'bavel->israel': '→',
                'israel->bavel': '→',
                both: '↔',
              };
              return (
                // biome-ignore lint/a11y/useSemanticElements: a native <button> would inject UA layout/typography into this tightly inline-styled row; role+tabIndex+keydown give the same semantics
                <div
                  role="button"
                  onMouseEnter={onEnter}
                  onMouseLeave={onLeave}
                  onFocus={onEnter}
                  onBlur={onLeave}
                  onClick={() => pickRabbi(row.name, row.slug ?? undefined)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' || e.key === ' ') {
                      e.preventDefault();
                      pickRabbi(row.name, row.slug ?? undefined);
                    }
                  }}
                  tabIndex={0}
                  title={`${fromFull} ${arrow[row.direction]} ${toFull} — ${row.name}`}
                  style={{
                    display: 'flex',
                    'align-items': 'center',
                    gap: '0.3rem',
                    padding: '0.15rem 0.3rem',
                    'border-radius': '4px',
                    cursor: props.onHighlightSingleRabbi ? 'pointer' : 'default',
                    'background-color': hovered() ? 'rgba(234, 179, 8, 0.18)' : 'transparent',
                    transition: 'background-color 120ms',
                    'white-space': 'nowrap',
                    overflow: 'hidden',
                  }}
                >
                  <span
                    style={{
                      display: 'inline-flex',
                      'align-items': 'center',
                      gap: '0.15rem',
                      'font-family': 'ui-monospace, SFMono-Regular, monospace',
                      'font-size': '0.7rem',
                      'flex-shrink': 0,
                    }}
                  >
                    <span style={{ color: fromColor, 'font-weight': 700 }}>{fromLabel}</span>
                    <span style={{ color: '#111' }}>{arrow[row.direction]}</span>
                    <span style={{ color: toColor, 'font-weight': 700 }}>{toLabel}</span>
                  </span>
                  <span style={{ color: '#333', overflow: 'hidden', 'text-overflow': 'ellipsis' }}>
                    {row.name}
                  </span>
                </div>
              );
            }}
          </For>
        </div>
      </Show>
    </section>
  );
}
