/**
 * Whole-daf geography map — two region cards (Eretz Yisrael + Bavel) drawn
 * from REAL projected geography (see geoShapes.ts, generated by
 * scripts/build-geo-shapes.ts): Natural Earth coastline, rivers (the
 * Euphrates/Tigris for Bavel, the Jordan + Kinneret + Dead Sea for Israel),
 * with city dots projected from real lat/lon.
 *
 * Data comes in pre-assembled as a DafGeoModel (geographyData.ts):
 * cached-only per-rabbi geography + the daf's `places` mark mentions. This
 * component never fetches and never spins — the caller renders it only when
 * the model has content.
 *
 * Visual language: city dots are gray and sized by on-daf mention count;
 * rabbi markers are generation-colored (GENERATION_BY_ID, same palette as
 * the timeline) and cluster sunflower-style around their city.
 */

import { createSignal, For, type JSX, Show } from 'solid-js';
import { GENERATION_BY_ID, type GenerationId } from './generations';
import type { CityDot, DafGeoModel, GeoRabbi, MoveDirection } from './geographyData';
import { BAVEL_SHAPE, GEO_CITIES, type GeoRegionShape, ISRAEL_SHAPE } from './geoShapes';
import { t } from './i18n';

export interface GeographyMapProps {
  model: DafGeoModel;
  /** Active city/region key ('_Israel' / '_Bavel' / a city name) — drives
   *  the active ring on dots. */
  activeLocation: string | null;
  onHighlightLocation: (cityName: string | null, rabbiNames: string[]) => void;
  /** Clicking a single rabbi dot highlights that rabbi (instead of everyone
   *  at the city). The registry slug rides along when known so the handler
   *  can open the RIGHT same-name homonym. */
  onHighlightSingleRabbi?: (rabbiName: string, slug?: string) => void;
  /** Transient hover highlight — rabbi name on mouseenter, null on leave. */
  onHoverRabbi?: (rabbiName: string | null) => void;
  /** Rabbi → generation map (the timeline palette) for dot coloring. */
  generationByName?: Map<string, GenerationId> | null;
  /** Clicking a mentioned-city dot highlights its name in the daf body. */
  onHighlightPlace?: (cityName: string | null) => void;
  activePlace?: string | null;
  /** 'row' (default) puts Israel + Bavel side-by-side; 'column' stacks. */
  layout?: 'row' | 'column';
}

const GEN_FALLBACK_COLOR = '#9ca3af';
const LAND_COLOR = '#6b7280';
const WATER_COLOR = '#3b82f6';
const WATER_FILL = 'rgba(96, 165, 250, 0.25)';
const CITY_COLOR = '#6b7280';

/**
 * N points around (cx, cy) in a sunflower spiral so co-located rabbi dots
 * don't overlap. Ring starts OFF-center (the city dot owns the center).
 */
function clusterOffsets(n: number, cx: number, cy: number): Array<{ x: number; y: number }> {
  const out: Array<{ x: number; y: number }> = [];
  const GOLDEN = Math.PI * (3 - Math.sqrt(5));
  const scale = 2.6;
  for (let i = 1; i <= n; i++) {
    const r = scale * Math.sqrt(i);
    const theta = i * GOLDEN;
    out.push({ x: cx + r * Math.cos(theta), y: cy + r * Math.sin(theta) });
  }
  return out;
}

/** Centroid of a region's cities — where the "region known, city unknown"
 *  cluster lands. */
function regionCentroid(region: 'israel' | 'bavel'): { x: number; y: number } {
  const cities = GEO_CITIES.filter((c) => c.region === region);
  let x = 0;
  let y = 0;
  for (const c of cities) {
    x += c.x;
    y += c.y;
  }
  return { x: x / cities.length, y: y / cities.length };
}

export function GeographyMap(props: GeographyMapProps): JSX.Element {
  const [hoveredMoverRow, setHoveredMoverRow] = createSignal<string | null>(null);

  const onCityClick = (d: CityDot) => {
    const isActive = props.activeLocation === d.city.name;
    props.onHighlightLocation(
      isActive ? null : d.city.name,
      d.rabbis.map((r) => r.name),
    );
  };

  const onRegionClick = (region: 'israel' | 'bavel') => {
    const m = props.model;
    const list = m.dots
      .filter((d) => d.city.region === region)
      .flatMap((d) => d.rabbis.map((r) => r.name));
    list.push(
      ...(region === 'israel' ? m.unspecifiedIsrael : m.unspecifiedBavel).map((r) => r.name),
    );
    const key = region === 'israel' ? '_Israel' : '_Bavel';
    const isActive = props.activeLocation === key;
    props.onHighlightLocation(isActive ? null : key, list);
  };

  const rabbiDot = (rabbi: GeoRabbi, x: number, y: number, cityLabel: string): JSX.Element => {
    const name = rabbi.name;
    const gen = props.generationByName?.get(name);
    const genInfo = gen ? GENERATION_BY_ID[gen] : undefined;
    const activate = () => {
      if (props.onHighlightSingleRabbi) props.onHighlightSingleRabbi(name, rabbi.slug ?? undefined);
    };
    return (
      // biome-ignore lint/a11y/useSemanticElements: native <button> cannot be used inside an SVG map
      <circle
        cx={x}
        cy={y}
        r={2.6}
        fill={genInfo?.color ?? GEN_FALLBACK_COLOR}
        stroke="rgba(0,0,0,0.3)"
        stroke-width={0.3}
        style={{ cursor: props.onHighlightSingleRabbi ? 'pointer' : 'default' }}
        role="button"
        tabindex={0}
        onClick={(e) => {
          e.stopPropagation();
          activate();
        }}
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault();
            activate();
          }
        }}
        onMouseEnter={() => props.onHoverRabbi?.(name)}
        onMouseLeave={() => props.onHoverRabbi?.(null)}
      >
        <title>{`${name} · ${cityLabel}${genInfo ? ` · ${genInfo.label}` : ''}`}</title>
      </circle>
    );
  };

  const renderCityDot = (d: CityDot): JSX.Element => {
    const activeCity = () => props.activeLocation === d.city.name;
    // The daf's .city-marker spans carry the RAW mark name (data-city), so
    // active-state + click must use d.mentionNames, not the canonical name
    // (a daf saying "Sepphoris" lights the Tzipori dot).
    const activeMention = () =>
      props.activePlace !== null &&
      props.activePlace !== undefined &&
      d.mentionNames.includes(props.activePlace);
    const mentioned = d.mentions > 0;
    // City dot sized by on-daf mention count; a rabbi-only city gets a small
    // anchor dot.
    const r = mentioned ? 1.6 + 0.4 * Math.min(d.mentions, 6) : 1.3;
    const cityLabel = `${d.city.name} (${d.city.nameHe})${d.city.approx ? ' ~' : ''}`;
    const offsets = clusterOffsets(d.rabbis.length, d.city.x, d.city.y);
    const clickCity = () => {
      // A mentioned city's dot drives the in-text place highlight (the
      // rabbis at the city stay reachable through their own dots and the
      // region hit-box); a rabbi-only city highlights its rabbis.
      if (d.mentionNames.length > 0 && props.onHighlightPlace) {
        props.onHighlightPlace(activeMention() ? null : d.mentionNames[0]);
      } else {
        onCityClick(d);
      }
    };
    return (
      <g>
        {/* biome-ignore lint/a11y/useSemanticElements: native <button> cannot be used inside an SVG map */}
        <circle
          cx={d.city.x}
          cy={d.city.y}
          r={r}
          fill={mentioned ? CITY_COLOR : '#9ca3af'}
          stroke={activeCity() || activeMention() ? '#000' : 'rgba(0,0,0,0.25)'}
          stroke-width={activeCity() || activeMention() ? 0.7 : 0.3}
          style={{ cursor: 'pointer' }}
          role="button"
          tabindex={0}
          onClick={(e) => {
            e.stopPropagation();
            clickCity();
          }}
          onKeyDown={(e) => {
            if (e.key === 'Enter' || e.key === ' ') {
              e.preventDefault();
              clickCity();
            }
          }}
        >
          <title>{mentioned ? `${cityLabel} · ${t('geography.mentionedInDaf')}` : cityLabel}</title>
        </circle>
        <For each={d.rabbis}>
          {(rabbi, i) => {
            const off = offsets[i()];
            return rabbiDot(rabbi, off.x, off.y, cityLabel);
          }}
        </For>
      </g>
    );
  };

  const renderUnspecified = (region: 'israel' | 'bavel', rabbis: GeoRabbi[]): JSX.Element => {
    const c = regionCentroid(region);
    const offsets = clusterOffsets(rabbis.length, c.x, c.y);
    const label =
      region === 'israel'
        ? `${t('geography.eretzYisrael')} · ${t('geography.cityUnknown')}`
        : `${t('geography.bavel')} · ${t('geography.cityUnknown')}`;
    return (
      <g opacity={0.85}>
        <For each={rabbis}>
          {(rabbi, i) => {
            const off = offsets[i()];
            return rabbiDot(rabbi, off.x, off.y, label);
          }}
        </For>
      </g>
    );
  };

  const regionCard = (
    region: 'israel' | 'bavel',
    shape: GeoRegionShape,
    heading: string,
    headingColor: string,
    aria: string,
    extras?: JSX.Element,
  ): JSX.Element => (
    <div
      style={{
        flex: 1,
        border: props.layout === 'column' ? 'none' : '1px solid #e5e7eb',
        'border-radius': props.layout === 'column' ? '0' : '8px',
        background: props.layout === 'column' ? 'transparent' : '#fff',
        padding: '0.5rem 0.5rem 0.4rem',
        display: 'flex',
        'flex-direction': 'column',
        'align-items': 'center',
        'min-width': 0,
      }}
    >
      <div
        style={{
          'font-size': '0.8rem',
          'font-weight': 600,
          color: headingColor,
          'margin-bottom': '0.3rem',
        }}
      >
        {heading}
      </div>
      <svg
        viewBox={`-4 -4 ${shape.width + 8} ${shape.height + 8}`}
        style={{ width: '100%', flex: 1, display: 'block', 'min-height': 0 }}
        preserveAspectRatio="xMidYMid meet"
        role="img"
        aria-label={aria}
      >
        {/* Invisible hit-box: a click anywhere in the card selects the region. */}
        {/* biome-ignore lint/a11y/useSemanticElements: native <button> cannot be used inside an SVG map */}
        <rect
          x={-4}
          y={-4}
          width={shape.width + 8}
          height={shape.height + 8}
          fill="transparent"
          style={{ cursor: 'pointer' }}
          role="button"
          tabindex={0}
          aria-label={heading}
          onClick={() => onRegionClick(region)}
          onKeyDown={(e) => {
            if (e.key === 'Enter' || e.key === ' ') {
              e.preventDefault();
              onRegionClick(region);
            }
          }}
        />
        {/* Water under land: rivers as thin blue lines; closed rings (the
            Kinneret / Dead Sea) get a light fill. */}
        <For each={shape.riverPaths}>
          {(d) => (
            <path
              d={d}
              fill={d.endsWith('Z') ? WATER_FILL : 'none'}
              stroke={WATER_COLOR}
              stroke-width={0.7}
              stroke-linecap="round"
              stroke-linejoin="round"
              opacity={0.75}
            />
          )}
        </For>
        <For each={shape.landPaths}>
          {(d) => (
            <path
              d={d}
              fill="none"
              stroke={LAND_COLOR}
              stroke-width={1.1}
              stroke-linecap="round"
              stroke-linejoin="round"
              opacity={0.85}
            />
          )}
        </For>
        {extras}
        <For each={props.model.dots.filter((d) => d.city.region === region)}>
          {(d) => renderCityDot(d)}
        </For>
        {renderUnspecified(
          region,
          region === 'israel' ? props.model.unspecifiedIsrael : props.model.unspecifiedBavel,
        )}
      </svg>
    </div>
  );

  // River name labels for the Bavel card, positioned where the generated
  // paths enter the window (Tigris from the top edge, Euphrates from the
  // west edge) — eyeballed against the projected data, in viewBox units.
  const bavelLabels = (
    <>
      <text
        x={34}
        y={9}
        font-family="Georgia,serif"
        font-size="6.5"
        font-style="italic"
        fill="#1e40af"
        opacity={0.85}
      >
        {t('geography.tigris')}
      </text>
      <text
        x={5}
        y={60}
        font-family="Georgia,serif"
        font-size="6.5"
        font-style="italic"
        fill="#1e40af"
        opacity={0.85}
      >
        {t('geography.euphrates')}
      </text>
    </>
  );

  return (
    <section
      style={{
        padding: '0.75rem 0.75rem 0.5rem',
        border: '1px solid #eee',
        'border-radius': '6px',
        background: '#fcfcfa',
        'font-family': 'system-ui, -apple-system, sans-serif',
        'font-size': '0.8rem',
        color: '#555',
      }}
    >
      <div
        style={{
          color: '#999',
          'font-size': '0.72rem',
          'margin-bottom': '0.35rem',
          'text-transform': 'uppercase',
          'letter-spacing': '0.06em',
        }}
      >
        {t('geography.heading')}
      </div>

      <div
        style={{
          display: 'flex',
          'flex-direction': props.layout === 'column' ? 'column' : 'row',
          gap: '0.5rem',
          'align-items': 'stretch',
        }}
      >
        {regionCard(
          'israel',
          ISRAEL_SHAPE,
          t('geography.eretzYisrael'),
          '#1f2937',
          t('geography.eretzYisrael.aria'),
        )}
        {regionCard(
          'bavel',
          BAVEL_SHAPE,
          t('geography.bavel'),
          '#1e40af',
          t('geography.bavel.aria'),
          bavelLabels,
        )}
      </div>

      <div
        style={{
          display: 'flex',
          'justify-content': 'space-between',
          'align-items': 'center',
          'margin-top': '0.3rem',
          'font-size': '0.78rem',
          color: '#555',
        }}
      >
        <span>
          {t('geography.eretzYisrael')}:{' '}
          <strong style={{ color: '#1f2937' }}>{props.model.israelCount}</strong>
        </span>
        <span>
          {t('geography.bavel')}:{' '}
          <strong style={{ color: '#92400e' }}>{props.model.bavelCount}</strong>
        </span>
      </div>

      <Show when={props.model.moverRows.length > 0}>
        <div
          style={{
            'margin-top': '0.45rem',
            'padding-top': '0.4rem',
            'border-top': '1px dashed #e5e7eb',
            'font-size': '0.72rem',
            color: '#555',
            display: 'flex',
            'flex-direction': 'column',
            gap: '0.15rem',
          }}
        >
          <div
            style={{
              color: '#6b7280',
              'font-size': '0.64rem',
              'text-transform': 'uppercase',
              'letter-spacing': '0.06em',
              'margin-bottom': '0.15rem',
            }}
          >
            {t('geography.migration')}
          </div>
          <For each={props.model.moverRows}>
            {(row) => {
              const hovered = () => hoveredMoverRow() === row.name;
              const onEnter = () => {
                setHoveredMoverRow(row.name);
                props.onHoverRabbi?.(row.name);
              };
              const onLeave = () => {
                setHoveredMoverRow(null);
                props.onHoverRabbi?.(null);
              };
              // Single-letter region tags so the whole row fits on one line
              // in a ~220px strip. "B" = Bavel (amber), "E" = Eretz Yisrael
              // (gray). Full names live in the title attribute.
              const fromB = row.direction === 'bavel->israel';
              const fromLabel = fromB ? 'B' : 'E';
              const toLabel = fromB ? 'E' : 'B';
              const fromColor = fromB ? '#92400e' : '#1f2937';
              const toColor = fromB ? '#1f2937' : '#92400e';
              const fromFull = fromB ? t('geography.bavel') : t('geography.eretzYisrael');
              const toFull = fromB ? t('geography.eretzYisrael') : t('geography.bavel');
              const arrow: Record<MoveDirection, string> = {
                'bavel->israel': '→',
                'israel->bavel': '→',
                both: '↔',
              };
              return (
                // biome-ignore lint/a11y/useSemanticElements: a native <button> would inject UA layout/typography into this tightly inline-styled row; role+tabIndex+keydown give the same semantics
                <div
                  role="button"
                  onMouseEnter={onEnter}
                  onMouseLeave={onLeave}
                  onFocus={onEnter}
                  onBlur={onLeave}
                  onClick={() => props.onHighlightSingleRabbi?.(row.name, row.slug ?? undefined)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' || e.key === ' ') {
                      e.preventDefault();
                      props.onHighlightSingleRabbi?.(row.name, row.slug ?? undefined);
                    }
                  }}
                  tabIndex={0}
                  title={`${fromFull} ${arrow[row.direction]} ${toFull} — ${row.name}`}
                  style={{
                    display: 'flex',
                    'align-items': 'center',
                    gap: '0.3rem',
                    padding: '0.15rem 0.3rem',
                    'border-radius': '4px',
                    cursor: props.onHighlightSingleRabbi ? 'pointer' : 'default',
                    'background-color': hovered() ? 'rgba(234, 179, 8, 0.18)' : 'transparent',
                    transition: 'background-color 120ms',
                    'white-space': 'nowrap',
                    overflow: 'hidden',
                  }}
                >
                  <span
                    style={{
                      display: 'inline-flex',
                      'align-items': 'center',
                      gap: '0.15rem',
                      'font-family': 'ui-monospace, SFMono-Regular, monospace',
                      'font-size': '0.7rem',
                      'flex-shrink': 0,
                    }}
                  >
                    <span style={{ color: fromColor, 'font-weight': 700 }}>{fromLabel}</span>
                    <span style={{ color: '#111' }}>{arrow[row.direction]}</span>
                    <span style={{ color: toColor, 'font-weight': 700 }}>{toLabel}</span>
                  </span>
                  <span style={{ color: '#333', overflow: 'hidden', 'text-overflow': 'ellipsis' }}>
                    {row.name}
                  </span>
                </div>
              );
            }}
          </For>
        </div>
      </Show>
    </section>
  );
}
