// DO NOT HAND-EDIT — generated by scripts/build-geo-shapes.ts.
// Regenerate with: node scripts/build-geo-shapes.ts   (from packages/talmud)
//             or: pnpm --filter talmud rebuild-geo-shapes
//
// Real geography, projected: Natural Earth coastline/rivers/lakes clipped to
// two region windows and projected equirectangularly (x scaled by cos of the
// window mid-latitude) into local viewBox space. City dots are projected from
// real lat/lon by the same transform — see the city table in the script for
// coordinates, sources, and which identifications are approximate.
//
//   Israel window: lon 34..36.7, lat 29.4..33.6 (Natural Earth 10m)
//   Bavel window:  lon 40.8..48.8, lat 29.7..37.5 (Natural Earth 50m)
//
// landPaths are coastline strokes; riverPaths are rivers plus (Israel only)
// the Kinneret + Dead Sea outlines — closed water rings end with 'Z' so a
// renderer can fill them.

export type GeoRegionId = 'israel' | 'bavel';

export interface GeoRegionShape {
  width: number;
  height: number;
  landPaths: string[];
  riverPaths: string[];
}

export interface GeoCity {
  name: string;
  nameHe: string;
  /** Lowercase alias spellings — these drive matching of place strings from
   *  rabbi-places.json / rabbi.geography / the places mark. */
  aliases: string[];
  region: GeoRegionId;
  /** Projected local coordinates (0..width / 0..height of the region shape). */
  x: number;
  y: number;
  /** True when the ancient site's identification is uncertain — the dot is a
   *  reasoned guess near the attested neighborhood. */
  approx?: boolean;
}

export const ISRAEL_SHAPE: GeoRegionShape = {
  width: 98.7,
  height: 180.0,
  landPaths: [
    'M31.9,50.1L30.6,56.5L27.7,65.7L27.2,66.0L26.0,70.6L22.3,78.6L18.8,84.6L16.2,88.5L8.1,97.4L0.0,102.3',
    'M50.5,0.0L49.3,3.7L46.4,6.1L44.8,12.3L43.4,13.7L44.2,14.8L42.9,18.4L42.5,18.1L41.9,19.7L40.2,21.4L40.4,22.3L39.4,25.8L38.9,29.0L39.5,29.8L38.8,31.8L37.6,33.1L35.5,32.5L34.9,32.8L31.9,50.1',
  ],
  riverPaths: [
    'M52.0,97.5L53.1,94.2L54.1,83.9L55.8,79.9L57.0,78.6',
    'M57.6,37.7L56.9,39.4L57.7,44.5L57.2,45.2L57.0,44.9L57.2,46.0L56.7,46.3L57.7,47.5L57.0,48.1L57.4,49.0L56.7,49.9L57.0,50.8L56.4,51.0L57.2,52.8L56.7,52.8L57.4,57.8L57.0,58.4L57.4,58.4L57.0,61.9L56.1,63.8L56.4,64.8L55.6,66.1L56.5,70.9L55.7,72.0L57.0,78.6',
    'M58.4,30.0L58.3,35.7L57.6,37.7',
    'M68.1,0.2L66.4,2.0L65.9,3.8L62.7,6.2L60.8,9.0L58.2,17.9L57.9,25.9L58.4,30.0',
    'M55.2,102.9L55.9,104.2L54.9,105.5L55.5,106.7L53.9,107.7L51.2,107.1L49.8,103.9L50.1,101.3L51.2,101.6L51.9,100.6L55.2,102.9Z',
    'M57.0,78.6L58.0,79.2L58.0,80.1L56.8,88.4L57.4,91.4L56.6,97.2L55.3,98.4L54.9,97.8L55.2,95.7L54.5,95.7L52.7,97.6L51.7,97.4L50.9,89.4L51.7,87.2L51.5,85.1L54.0,80.1L55.1,79.0L57.0,78.6Z',
    'M59.9,32.1L59.7,36.3L58.4,37.8L57.6,37.7L57.2,36.1L55.4,33.4L55.7,32.1L58.2,30.1L59.6,30.7L59.9,32.1Z',
  ],
};

export const BAVEL_SHAPE: GeoRegionShape = {
  width: 153.8,
  height: 180.0,
  landPaths: [
    'M140.1,180.0L138.5,176.9L138.1,172.8L141.1,172.1L147.1,174.5L149.8,173.7L151.3,172.4L153.8,172.3',
    'M145.1,178.1L141.9,173.6L140.0,177.7L140.8,180.0',
  ],
  riverPaths: [
    'M0.0,64.7L2.5,67.4L2.8,70.2L3.7,70.9',
    'M128.2,150.7L130.4,153.9L132.7,155.7L134.3,160.1L135.4,161.3L139.7,162.5L141.2,163.5L142.7,165.7L144.8,166.5L146.1,168.7L146.1,170.5L146.7,172.2L148.9,173.9',
    'M20.1,0.0L20.8,1.4L22.7,1.5L27.4,4.1L29.1,6.2L30.3,10.1',
    'M3.7,70.9L6.1,71.8L7.2,71.7L7.8,70.8L9.1,70.5L13.5,70.7L19.7,69.0L22.9,70.5L25.4,73.8L28.6,74.0L28.9,73.1L30.1,73.2L29.4,75.4L30.2,76.0L30.3,78.1L32.9,80.8L33.9,83.8L36.0,83.3L37.1,83.9L37.4,84.9L37.0,86.5L37.8,88.4L39.9,90.5L42.9,92.2L44.3,91.7L47.8,93.4L48.7,93.1L54.8,95.0L57.2,96.7L59.1,99.3L62.1,100.2L63.9,102.6L66.4,107.8L66.4,115.5L67.7,118.9L69.0,125.3L70.1,127.4L70.6,132.4L72.0,135.0L76.3,138.9L81.5,139.8L86.4,142.6L89.7,143.0',
    'M30.3,10.1L32.9,12.9L32.9,14.4L33.8,15.4L36.8,16.5L38.0,17.7L37.7,18.0L40.3,18.7L40.4,19.3L38.7,20.6L37.9,22.2L39.3,23.6L42.9,24.8L45.5,26.9L47.3,29.9L48.9,35.9L48.9,37.9L48.0,40.0L48.3,41.1L47.3,42.5L47.3,46.9L53.2,57.5L52.6,58.7L57.4,70.3L58.7,76.3L60.7,78.5L66.0,79.6L69.3,81.4L69.7,82.9L69.2,86.1L69.5,86.8L67.5,91.6L69.1,97.1L69.8,97.1L72.0,100.9L74.5,103.3L78.2,105.6L81.2,106.4L82.3,108.4L85.0,109.0L86.5,111.6L88.1,113.0L96.3,115.3L100.5,112.6L102.6,112.3L103.8,113.4L113.3,116.7L114.1,119.5L113.5,121.2L113.6,123.5L115.8,125.1L118.0,128.8L119.3,130.0L120.9,130.0L121.8,130.9L122.0,132.7L123.4,135.5L126.1,139.4L127.5,143.4L127.7,150.0',
    'M89.6,143.0L91.1,144.7L102.3,148.0L109.2,152.2L117.0,150.9L125.5,150.8L127.7,149.9L128.2,150.7',
    'M96.3,115.3L98.0,117.0L98.9,120.8L99.7,121.9L99.7,128.7L100.8,129.6L101.7,132.2L102.9,139.5L103.9,141.5L107.1,145.3L107.7,147.4L107.0,150.8',
  ],
};

export const GEO_CITIES: GeoCity[] = [
  {
    name: 'Tyre',
    nameHe: 'צור',
    aliases: ['tyre', 'tzor', 'sor'],
    region: 'israel',
    x: 44.0,
    y: 14.1,
  },
  {
    name: 'Gush Halav',
    nameHe: 'גוש חלב',
    aliases: ['gush halav', 'gush chalav', 'giscala', 'gischala'],
    region: 'israel',
    x: 52.9,
    y: 24.8,
  },
  {
    name: "Peki'in",
    nameHe: 'פקיעין',
    aliases: ['pekiin', "peki'in"],
    region: 'israel',
    x: 48.6,
    y: 26.7,
  },
  {
    name: 'Akko',
    nameHe: 'עכו',
    aliases: ['akko', 'acre', 'acco', 'ptolemais'],
    region: 'israel',
    x: 39.5,
    y: 28.8,
  },
  {
    name: 'Sikhnin',
    nameHe: 'סכנין',
    aliases: ['sikhnin', 'sakhnin', 'sogane'],
    region: 'israel',
    x: 47.4,
    y: 31.5,
  },
  {
    name: 'Arbel',
    nameHe: 'ארבל',
    aliases: ['arbel'],
    region: 'israel',
    x: 54.8,
    y: 33.8,
    approx: true,
  },
  {
    name: "Shefar'am",
    nameHe: 'שפרעם',
    aliases: ['shefaram', "shefar'am", 'shfaram'],
    region: 'israel',
    x: 42.8,
    y: 34.0,
  },
  { name: 'Usha', nameHe: 'אושא', aliases: ['usha'], region: 'israel', x: 42.8, y: 34.3 },
  {
    name: 'Tiberias',
    nameHe: 'טבריה',
    aliases: ['tiberias', 'teveria', 'tiberya'],
    region: 'israel',
    x: 55.9,
    y: 34.5,
  },
  {
    name: 'Tzipori',
    nameHe: 'ציפורי',
    aliases: ['tzipori', 'tzippori', 'sepphoris', 'zippori', 'sippori'],
    region: 'israel',
    x: 46.7,
    y: 36.3,
  },
  {
    name: "Beit She'arim",
    nameHe: 'בית שערים',
    aliases: ['beit shearim', "beit she'arim", 'bet shearim', 'besara'],
    region: 'israel',
    x: 41.3,
    y: 38.5,
  },
  {
    name: 'Caesarea',
    nameHe: 'קיסריה',
    aliases: ['caesarea', 'kisrin', 'kisarya'],
    region: 'israel',
    x: 32.6,
    y: 47.1,
  },
  {
    name: "Beit She'an",
    nameHe: 'בית שאן',
    aliases: ["beit she'an", 'beit shean', 'beit shan', 'beth shan', 'scythopolis'],
    region: 'israel',
    x: 54.7,
    y: 47.3,
  },
  {
    name: 'Shechem',
    nameHe: 'שכם',
    aliases: ['shechem', 'nablus'],
    region: 'israel',
    x: 45.8,
    y: 59.1,
  },
  {
    name: 'Bnei Brak',
    nameHe: 'בני ברק',
    aliases: ['bnei brak', 'bene berak', 'benei berak'],
    region: 'israel',
    x: 30.5,
    y: 65.1,
  },
  {
    name: 'Lod',
    nameHe: 'לוד',
    aliases: ['lod', 'lydda', 'lud'],
    region: 'israel',
    x: 32.7,
    y: 70.7,
  },
  {
    name: 'Yavneh',
    nameHe: 'יבנה',
    aliases: ['yavneh', 'jamnia', 'yavne', 'jabneh'],
    region: 'israel',
    x: 27.0,
    y: 73.8,
  },
  {
    name: 'Jerusalem',
    nameHe: 'ירושלים',
    aliases: ['jerusalem', 'yerushalayim', 'yerushalaim'],
    region: 'israel',
    x: 45.1,
    y: 78.1,
  },
  {
    name: 'Ashkelon',
    nameHe: 'אשקלון',
    aliases: ['ashkelon', 'ascalon', 'ashqelon'],
    region: 'israel',
    x: 20.9,
    y: 82.8,
  },
  {
    name: 'Tekoa',
    nameHe: 'תקוע',
    aliases: ['tekoa'],
    region: 'israel',
    x: 47.2,
    y: 84.2,
    approx: true,
  },
  {
    name: 'Hebron',
    nameHe: 'חברון',
    aliases: ['hebron', 'chevron'],
    region: 'israel',
    x: 40.0,
    y: 88.6,
  },
  {
    name: 'Nisibis',
    nameHe: 'נציבין',
    aliases: ['nisibis', 'netzivin'],
    region: 'bavel',
    x: 8.0,
    y: 9.8,
  },
  {
    name: 'Nehardea',
    nameHe: 'נהרדעא',
    aliases: ['nehardea', 'nehardeah', "neharde'a"],
    region: 'bavel',
    x: 48.1,
    y: 94.6,
    approx: true,
  },
  {
    name: 'Pumbedita',
    nameHe: 'פומבדיתא',
    aliases: ['pumbedita', 'pumbeditha', 'pumbedisa'],
    region: 'bavel',
    x: 57.3,
    y: 95.8,
  },
  {
    name: 'Baghdad',
    nameHe: 'בגדאד',
    aliases: ['baghdad', 'bagdad'],
    region: 'bavel',
    x: 68.4,
    y: 96.7,
  },
  {
    name: 'Sichra',
    nameHe: 'שיכרא',
    aliases: ['sichra', 'sikra', 'shikra'],
    region: 'bavel',
    x: 75.0,
    y: 99.2,
    approx: true,
  },
  {
    name: 'Mehoza',
    nameHe: 'מחוזא',
    aliases: ['mehoza', 'mahoza', 'machuza', 'mechuza', 'maḥoza'],
    region: 'bavel',
    x: 72.1,
    y: 101.5,
    approx: true,
  },
  {
    name: 'Ctesiphon',
    nameHe: 'קטיספון',
    aliases: ['ctesiphon', 'qtesiphon'],
    region: 'bavel',
    x: 72.7,
    y: 101.7,
  },
  {
    name: 'Pum Nahara',
    nameHe: 'פום נהרא',
    aliases: ['pum nahara', 'pum nehara'],
    region: 'bavel',
    x: 65.4,
    y: 110.8,
    approx: true,
  },
  {
    name: 'Shekanziv',
    nameHe: 'שקנציב',
    aliases: ['shekanziv', 'shikanzib'],
    region: 'bavel',
    x: 78.8,
    y: 113.1,
    approx: true,
  },
  {
    name: 'Hutzal',
    nameHe: 'הוצל',
    aliases: ['hutzal', 'huzal', 'hutsal'],
    region: 'bavel',
    x: 69.2,
    y: 115.4,
    approx: true,
  },
  { name: 'Nippur', nameHe: 'ניפור', aliases: ['nippur'], region: 'bavel', x: 85.2, y: 123.9 },
  {
    name: 'Hini',
    nameHe: 'היני',
    aliases: ['hini', 'hene'],
    region: 'bavel',
    x: 73.0,
    y: 125.8,
    approx: true,
  },
  {
    name: 'Mata Mehasya',
    nameHe: 'מתא מחסיא',
    aliases: ['mata mehasya', 'mata mahasya', 'mata meḥasya'],
    region: 'bavel',
    x: 71.1,
    y: 129.2,
    approx: true,
  },
  { name: 'Sura', nameHe: 'סורא', aliases: ['sura'], region: 'bavel', x: 70.2, y: 129.7 },
  {
    name: 'Naresh',
    nameHe: 'נרש',
    aliases: ['naresh', 'narash'],
    region: 'bavel',
    x: 72.1,
    y: 135.0,
    approx: true,
  },
  {
    name: 'Kafri',
    nameHe: 'כפרי',
    aliases: ['kafri', 'kufri'],
    region: 'bavel',
    x: 65.4,
    y: 137.3,
    approx: true,
  },
];
