/**
 * Hebrew labels for the short coded values on a sage's record: the academy,
 * orientation, role tags and place names. The record stores English slugs;
 * the sages page shows these in Hebrew when the app is in Hebrew. A value with
 * no entry here shows as stored, so a new tag never disappears.
 */

const ACADEMY_HE: Record<string, string> = {
  pumbedita: 'פומבדיתא',
  tiberias: 'טבריה',
  sura: 'סורא',
  yavneh: 'יבנה',
  usha: 'אושא',
  sepphoris: 'צפורי',
  nehardea: 'נהרדעא',
  caesarea: 'קיסריה',
  lod: 'לוד',
  mehoza: 'מחוזא',
  'mata-mehasya': 'מתא מחסיא',
  jerusalem: 'ירושלים',
  'bnei-brak': 'בני ברק',
  nisibis: 'נציבין',
  naresh: 'נרש',
};

const ORIENTATION_HE: Record<string, string> = {
  practical: 'מעשי',
  mystical: 'מיסטי',
  mixed: 'משולב',
  unknown: 'לא ידוע',
};

const ROLE_HE: Record<string, string> = {
  halakhist: 'פוסק הלכה',
  aggadist: 'בעל אגדה',
  exegete: 'מפרש מקרא',
  'communal-leader': 'מנהיג קהילה',
  'head-of-academy': 'ראש ישיבה',
  ascetic: 'פרוש',
  judge: 'דיין',
  mystic: 'מקובל',
  tanna: 'תנא',
  amora: 'אמורא',
  'miracle-worker': 'עושה ניסים',
  martyr: 'קדוש מעונה',
  priest: 'כהן',
  kohen: 'כהן',
  levite: 'לוי',
  transmitter: 'מוסר מסורות',
  'baraita-transmitter': 'מוסר ברייתות',
  teacher: 'מורה',
  pious: 'חסיד',
  hasid: 'חסיד',
  pietist: 'חסיד',
  wealthy: 'עשיר',
  poor: 'עני',
  poet: 'פייטן',
  emigrant: 'עולה מבבל',
  polemicist: 'בעל פולמוס',
  preacher: 'דרשן',
  'talmid-chacham': 'תלמיד חכם',
  'descendant-of-eli': 'מצאצאי עלי',
  traveler: 'נוסע',
  blind: 'סגי נהור',
  'elder-sage': 'זקן החכמים',
  attendant: 'משרת',
  interpreter: 'מתורגמן',
  translator: 'מתרגם',
  farmer: 'עובד אדמה',
  'temple-functionary': 'משרת בבית המקדש',
  editor: 'עורך',
  'student-of-shmuel': 'תלמיד שמואל',
  scribe: 'סופר',
  longevity: 'אריכות ימים',
};

const PLACE_HE: Record<string, string> = {
  Acre: 'עכו',
  Akko: 'עכו',
  Artivna: 'ארטיבנא',
  Atush: 'אטוש',
  Babylonia: 'בבל',
  Baghdad: 'בגדאד',
  'Beit Guvrin': 'בית גוברין',
  "Beit She'arim": 'בית שערים',
  'Beit Shearim': 'בית שערים',
  'Bnei Brak': 'בני ברק',
  Bostra: 'בצרה',
  Caesarea: 'קיסריה',
  Dalton: 'דלתון',
  Damascus: 'דמשק',
  'Eretz Yisrael': 'ארץ ישראל',
  Galilee: 'הגליל',
  Hadid: 'חדיד',
  Haifa: 'חיפה',
  "Har ha-Moda'i": 'הר המודעי',
  Hauran: 'חורן',
  Jerusalem: 'ירושלים',
  Kabul: 'כבול',
  Kafri: 'כפרי',
  Kartignin: 'קרטיגנין',
  'Kfar Tamarta': 'כפר תמרתא',
  'Khirbat Atusha': 'חורבת אטושא',
  Lod: 'לוד',
  'Lower Galilee': 'גליל תחתון',
  Lydda: 'לוד',
  Mahoza: 'מחוזא',
  Mechoza: 'מחוזא',
  Mechuza: 'מחוזא',
  Mehuza: 'מחוזא',
  'Mata Mehasia': 'מתא מחסיא',
  'Mata Mehasya': 'מתא מחסיא',
  Naresh: 'נרש',
  'Nehar Pakod': 'נהר פקוד',
  Nehardea: 'נהרדעא',
  Nisibis: 'נציבין',
  Ono: 'אונו',
  Pafonya: 'פפוניא',
  Paphunya: 'פפוניא',
  Pumbedita: 'פומבדיתא',
  Radun: 'רדון',
  Rome: 'רומי',
  Sakhnin: 'סכנין',
  Sikhnin: 'סכנין',
  Sepphoris: 'צפורי',
  Tzipori: 'צפורי',
  Tzippori: 'צפורי',
  Zippori: 'צפורי',
  Shefaram: 'שפרעם',
  Shekhantziv: 'שכנציב',
  Shilhi: 'שילחי',
  Shunem: 'שונם',
  Sura: 'סורא',
  'Tel Beit Tzaida': 'תל בית צידא',
  Tiberias: 'טבריה',
  Tyre: 'צור',
  Tzidon: 'צידון',
  Usha: 'אושא',
  'Western Galilee': 'גליל מערבי',
  Yavneh: 'יבנה',
};

type Lang = 'en' | 'he';

const pick = (map: Record<string, string>, v: string, lang: Lang): string =>
  lang === 'he' ? (map[v] ?? v) : v;

export const academyLabel = (v: string, lang: Lang): string => pick(ACADEMY_HE, v, lang);
export const orientationLabel = (v: string, lang: Lang): string => pick(ORIENTATION_HE, v, lang);
export const roleLabel = (v: string, lang: Lang): string => pick(ROLE_HE, v, lang);
export const placeLabel = (v: string, lang: Lang): string => pick(PLACE_HE, v, lang);
