# Findings for challenge-16. Every exact_quote is copied from a saved source; build_dossier.py adds source hashes.


def body_with(E):
    findings = [
        {
            "finding_id": "F1",
            "claim": "The printed Aramaic names a regular attendee in two reported forms, Rav Shimi bar Ukva or 'Mar Ukva', introduced by ואמרי לה ('and some say'). It says he was regularly before Rabbi Shimon ben Pazi. The verb is הוה שכיח קמיה ('was regularly present before'). Neither the verb nor its context names a formal teacher-student bond. The word 'study' in the William Davidson English, and ללמוד in its Hebrew version, are plain-text additions by the editors.",
            "kind": "textual",
            "evidence": [
                E("S1", "רַב שִׁימִי בַּר עוּקְבָא וְאָמְרִי לַהּ מָר עוּקְבָא, הֲוָה שְׁכִיחַ קַמֵּיהּ דְּרַבִּי שִׁמְעוֹן בֶּן פַּזִּי", "Rav Shimi bar Ukva, and some say Mar Ukva, was regularly before Rabbi Shimon ben Pazi"),
                E("S5", "רב שימי בר עוקבא ואמרי לה מר עוקבא הוה שכיח קמיה דר' שמעון בן פזי"),
                E("S1", "<b>Rav Shimi bar Ukva, and some say Mar Ukva, would regularly</b> study <b>before Rabbi Shimon ben Pazi,</b>"),
                E("S2", "הוה שכיח קמיה</b> <small>[היה מצוי,</small> ללמוד <small>לפני]</small>"),
                E("S6", "was frequently in the company of R. Simeon b. Pazzi"),
            ],
            "reasoning": "ואמרי לה introduces a second name for one role. It does not put two people in the scene. In the English, 'study' is outside the bold text, so it is the editors' explanation. In the Steinsaltz Hebrew, ללמוד sits outside the bracketed gloss of the Aramaic. Cohen 1921 has only 'in the company of'. Frequent presence is a scene relation, not a teacher or student edge.",
            "confidence": "high",
            "graph_effect": "Keep c5 and c6 as a two-branch group on one role. Keep the predicate as attendance or presence, with no student_of edge. The earlier reading already does this.",
        },
        {
            "finding_id": "F2",
            "claim": "The Hebrew Wikisource explained edition gives manuscript variants for the name line. Its template page says the variants come mainly from Dikdukei Soferim or the Hachi Garsinan project. As this dossier parses the note, it reports three variants. (a) One manuscript, marked א, reads 'bar Akaviah' for 'bar Ukva'. (b) The manuscripts lack the words ואמרי לה מר עוקבא ('and some say Mar Ukva'). (c) The manuscripts marked מ' and פ' add בשמעתתא, giving 'was regularly present at the discourses' before R. Shimon ben Pazi.",
            "kind": "textual",
            "evidence": [
                E("S15", "רב שימי בר עוקבא{{דקס|בכת\"י א|בר עקביה. {{ק|ובכתה\"י ליתא}} ואמרי לה מר עוקבא}}", "Rav Shimi bar Ukva [variant: in MS A: 'bar Akaviah'. (small type:) and in the MSS it is absent: 'and some say Mar Ukva']"),
                E("S15", "הוה שכיח{{דקס|בכת\"י מ' ופ' נוסף|בשמעת[ת]א}}", "was regularly present [variant: in MSS M and P added: 'at the discourses']"),
                E("S16", "כתיבת שינויי נוסחאות (בעיקר מדקדוקי סופרים, או מפרוייקט \"הכי גרסינן\") בגמרא המבוארת.", "Writing textual variants (mainly from Dikdukei Soferim, or from the 'Hachi Garsinan' project) in the explained Gemara."),
            ],
            "reasoning": "These are secondhand reports. No manuscript image or transcription was viewed. The template renders the first argument as the witness and the second as the reading. The small-type ובכתה\"י ליתא ('and in the manuscripts it is absent') seems to apply to the words that follow it. That parse is this dossier's; the note is compressed. The page does not expand the sigla. Reading מ' as Munich matches Cohen's 'M.' and Soncino's 'MS.M.', but this dossier has not verified it. It does not say which manuscripts 'the manuscripts' covers.",
            "confidence": "medium",
            "graph_effect": "Do not delete the Mar Ukva branch. Label its support as printed-edition text, and record that one secondary source reports it absent from the manuscripts. Add 'Shimi bar Akaviah' as a name-form variant for the same name slot, not a new person. The father slot's name form then varies (Ukva/Akaviah), but the child_of relation stays. The בשמעתתא addition, reported for two manuscripts, would make the setting discourse sessions; attach it to c5/c6 as a variant, not as the base text.",
        },
        {
            "finding_id": "F3",
            "claim": "The printed text says וַהֲוָה מְסַדַּר ('and he used to arrange'), which leaves open who arranged the aggadah. Three secondary sources report that manuscripts read דהוה ('who used to'), which makes R. Shimon ben Pazi the arranger: Cohen 1921 (Munich), Soncino (MS.M.) and the Wikisource explained edition ('the manuscripts').",
            "kind": "textual",
            "evidence": [
                E("S1", "וַהֲוָה מְסַדַּר אַגָּדָתָא קַמֵּיהּ דְּרַבִּי יְהוֹשֻׁעַ בֶּן לֵוִי", "and [he] used to arrange aggadah before Rabbi Yehoshua ben Levi"),
                E("S7", "Reading with M. דהוה \"who used\" instead of edd. והוה \"and he used\"; i.e. the subject of the verb is Simeon b. Pazzi."),
                E("S8", "Reading [H] with MS.M."),
                E("S15", "והוה{{דקס|בכתה\"י|דהוה}} מסדר אגדתא", "and he used [variant: in the MSS: 'who used'] to arrange aggadah"),
            ],
            "reasoning": "All three are reports about manuscripts, not manuscripts. They may share one origin: the Wikisource page says its notes come mainly from Dikdukei Soferim, which is built on the Munich manuscript. So they are not three independent witnesses. The Soncino site replaces the Hebrew word with [H], so which word it reads is inferred from its translation 'who'. This is a source variant, not a later emendation.",
            "confidence": "medium",
            "graph_effect": "For the arranger group (c7/c8/c9), attach the reported manuscript reading דהוה as source-variant support for branch_shimon_arranges. The printed והוה supports neither branch.",
        },
        {
            "finding_id": "F4",
            "claim": "Translators and commentators disagree on who arranged the aggadah before R. Yehoshua ben Levi. Most sources consulted say R. Shimon ben Pazi: Cohen 1921, Soncino, the William Davidson English and the Steinsaltz Hebrew. Seder HaDorot places 'arranged aggadah before R. Yehoshua ben Levi' under its entry for Mar Ukva, so it takes the attendee as the arranger. The Wikisource editor (signed נ.ו.) says it is unclear and leans tentatively toward Rav Shimi.",
            "kind": "interpretation",
            "evidence": [
                E("S6", "R. Simeon b. Pazzi who used to arrange the Aggadah in the presence of R. Joshua b. Levi"),
                E("S8", "R. Shimi b. 'Ukba (others say, Mar 'Ukba) was often in the company of R. Simeon b. Pazzi, who"),
                E("S2", "<b>ר' שמעון בן פזי</b> שהיה בקי באגדה, שכן <b>הוה</b> <small>[היה]</small> <b>מסדר אגדתא קמיה</b>", "R. Shimon ben Pazi, who was expert in aggadah, for he used to arrange aggadah before..."),
                E("S1", "who was well versed in <i>aggada</i> and <b>would arrange the <i>aggada</i> before Rabbi Yehoshua ben Levi.</b>"),
                E("S9", "קמי' ריב\"ל מסדר אגדתא ברכות (י' ע\"א)", "[under the entry Mar Ukva:] before R. Yehoshua ben Levi arranged aggadah, Berakhot 10a"),
                E("S15", "לא ברור לי מי היה מסדר אגדתא לפני ריב\"ל: רשב\"ע או רשב\"פ, ומי שאל את מי. וצ\"ע.", "It is not clear to me who arranged aggadah before R. Yehoshua ben Levi, R. Shimi bar Ukva or R. Shimon ben Pazi, and who asked whom. This needs study."),
            ],
            "reasoning": "The William Davidson English and the Steinsaltz Hebrew come from one editorial project, so they count as one voice. Cohen and Soncino may lean on the Munich reading (F3). Seder HaDorot is a prosopographic compiler, and its entry is a filing decision rather than an argued reading. This finding records interpretations. It does not settle the question.",
            "confidence": "medium",
            "graph_effect": "Keep branch_visitor_arranges and branch_shimon_arranges both open. Record the sources for each branch by type: modern translations and commentaries, plus the reported manuscript variant (F3), for Shimon; a compiler's filing, plus one editor's tentative lean, for the attendee.",
        },
        {
            "finding_id": "F5",
            "claim": "In 10a:21 the William Davidson English makes R. Shimon ben Pazi the asker and Rav Shimi the one who answers 'Come and see'. The same project contradicts this twice. Its Steinsaltz Hebrew has the attendee address R. Shimon ben Pazi. Its own English for 10a:24 has Rav Shimi restate what he 'meant', which only the asker can do, and has R. Shimon ben Pazi answer. All the names are in plain text; the Aramaic names no speaker.",
            "kind": "textual",
            "evidence": [
                E("S1", "אֲמַר לֵיהּ: מַאי דִּכְתִיב, ״בָּרְכִי נַפְשִׁי אֶת ה׳ וְכָל קְרָבַי אֶת שֵׁם קָדְשׁוֹ״? אֲמַר לֵיהּ: בֹּא וּרְאֵה", "He said to him: What is that which is written, 'Bless the Lord, my soul, and all my inward parts His holy name'? He said to him: Come and see"),
                E("S1", "<br>Once, Rabbi Shimon ben Pazi <b>said to him: What is</b>"),
                E("S1", "<br>Rav Shimi bar Ukva <b>said to</b> Rabbi Shimon ben Pazi: <b>Come and see"),
                E("S1", "This did not satisfy Rav Shimi bar Ukva, who <b>said to</b> Rabbi Shimon ben Pazi: <b>I</b> meant to <b>say to you as follows:"),
                E("S2", "פעם <b>אמר ליה</b> <small>[לו]</small> לר' שמעון בן פזי:", "Once he said to R. Shimon ben Pazi:"),
            ],
            "reasoning": "In the English of 10a:21, 'Rabbi Shimon ben Pazi' and 'Rav Shimi bar Ukva' are both outside the bold. The 10a:24 English implies the reverse roles. The Hebrew of the same edition names only the addressee, R. Shimon ben Pazi. So the 10a:21 English assignment is an editorial reading that its own edition contradicts, and it is not text. The earlier reading rightly did not use it.",
            "confidence": "high",
            "graph_effect": "Do not build asks or answers claims from the plain-text names in the 10a:21 English. If this translation is cited, flag its internal inconsistency. Do not count it with the Steinsaltz Hebrew as two witnesses.",
        },
        {
            "finding_id": "F6",
            "claim": "Most readers consulted take the attendee as the asker and R. Shimon ben Pazi as the one who answers. The attendee then restates his question in 10a:24. Rashi's comment on the first answer (the answerer 'thought' this was the question) implies the first answer misread the question. That is why the asker clarifies.",
            "kind": "interpretation",
            "evidence": [
                E("S3", "בא וראה וכו' – הוא סבר דהכי בעי מאי שנא קרבים דנקט:", "Come and see etc.: he thought that this is what he was asking: why did it mention 'inward parts'"),
                E("S6", "He asked him :  What means"),
                E("S8", "R. Shimi or Mar 'Ukba."),
                E("S8", "R. Shimi to R. Simeon b. Pazzi."),
                E("S7", "Rab Shimi to R. Simeon b. Pazzi. What follows is an alternative explanation of the fivefold \"Bless the Lord, O my soul\" as given in the last paragraph but one."),
                E("S2", "דברים אלה לא סיפקו את רב שימי בר עוקבא, ולכך <b>אמר ליה</b>", "These words did not satisfy Rav Shimi bar Ukva, and so he said to him"),
            ],
            "reasoning": "Rashi names no one. His comment only establishes that the answerer misunderstood the asker, so the clarifier in 10a:24 is the original asker. The names come from translators: Soncino notes 26 and 29, Cohen note 15, and the Steinsaltz Hebrew. Soncino note 26 keeps both name forms. Cohen note 15, Soncino note 29 and Steinsaltz name only Rav Shimi, which quietly drops the Mar Ukva branch. On the text alone, the addressee of the first ליה could also be R. Yehoshua ben Levi, the nearest named person (see F7).",
            "confidence": "medium",
            "graph_effect": "Add branch-scoped claims marked as interpretations: the attendee (Rav Shimi or Mar Ukva) asks R. Shimon ben Pazi, R. Shimon ben Pazi answers, and the attendee clarifies in 10a:24. Keep these distinct from explicit text. Any Rav-Shimi-only naming must be applied to both branches, not only branch_shimi_report.",
        },
        {
            "finding_id": "F7",
            "claim": "The Wikisource editor offers a tentative other scenario, marked 'it seems slightly'. Rav Shimi arranged aggadah before R. Yehoshua ben Levi and asked him the question. After R. Yehoshua ben Levi answered, Rav Shimi passed on to him what he had heard from R. Shimon ben Pazi. On this reading, R. Yehoshua ben Levi becomes a speech participant.",
            "kind": "uncertainty",
            "evidence": [
                E("S15", "וקצת נראה שרשב\"ע היה מסדר אגדתא לפני ריב\"ל, ורשב\"ע שאל את ריב\"ל, וכשהשיב ריב\"ל לרשב\"ע, מסר רשב\"ע לריב\"ל את מה ששמע מרשב\"פ. נ.ו.", "And it seems slightly that R. Shimi b. Ukva arranged aggadah before R. Yehoshua b. Levi, and R. Shimi asked R. Yehoshua b. Levi; and when R. Yehoshua b. Levi answered R. Shimi, R. Shimi transmitted to R. Yehoshua b. Levi what he had heard from R. Shimon b. Pazi."),
                E("S15", "אמר ליה: אנא הכי קא אמינא לך{{דקס|בכת\"י א'|אנא הכי שמיע לי}}", "He said to him: I was saying thus to you [variant, MS A: 'I heard thus']"),
            ],
            "reasoning": "This is a modern editor's conjecture, openly tentative. It is not a source reading. It shows that the grammar does not rule out R. Yehoshua ben Levi as addressee. The reported MS A variant 'I heard thus' (F8) fits a transmission reading, but the editor does not cite it. No other source consulted assigns a speech turn to R. Yehoshua ben Levi.",
            "confidence": "low",
            "graph_effect": "Keep yehoshua among the coreference candidates for the unnamed speech turns, as low-support and conjecture-only. Add no claim for it.",
        },
        {
            "finding_id": "F8",
            "claim": "In 10a:24, one manuscript (marked א) reportedly reads אנא הכי שמיע לי ('I heard thus') instead of אנא הכי קא אמינא לך ('I was saying thus to you'). The manuscripts marked מ' and פ' reportedly read 'only about the attributes of the Holy One' for 'only about the Holy One and the soul'.",
            "kind": "textual",
            "evidence": [
                E("S1", "אֲמַר לֵיהּ, אֲנָא הָכִי קָא אָמֵינָא לָךְ", "He said to him: I was saying thus to you"),
                E("S15", "אנא הכי קא אמינא לך{{דקס|בכת\"י א'|אנא הכי שמיע לי}}"),
                E("S15", "וכנגד נשמה{{דקס|בכת\"י מ' ופ'|אלא כנגד מידותיו של הקב\"ה.", "and about the soul [variant, MSS M and P: 'only about the attributes of the Holy One']"),
            ],
            "reasoning": "In the printed text the speaker restates his question. In the reported MS A variant the speaker reports a tradition he received, from an unnamed source. The two readings are different speech acts. Both reports are secondhand.",
            "confidence": "medium",
            "graph_effect": "Add a source-variant branch to c15: 'clarifies own question' (printed) or 'reports a heard tradition, source unnamed' (reported MS A). Neither branch names the source of the tradition. Do not create a transmission edge to any named person.",
        },
        {
            "finding_id": "F9",
            "claim": "No new 'he said to him' marks who says 'He said them only about the Holy One and the soul', or the five comparisons that follow. The Steinsaltz Hebrew and the William Davidson English add 'he answered him' in plain text; they are one project. Cohen 1921 and Soncino mark no change of speaker.",
            "kind": "uncertainty",
            "evidence": [
                E("S1", "הָנֵי חֲמִשָּׁה ״בָּרְכִי נַפְשִׁי״ כְּנֶגֶד מִי אֲמָרָן דָּוִד? לֹא אֲמָרָן אֶלָּא כְּנֶגֶד הַקָּדוֹשׁ בָּרוּךְ הוּא וּכְנֶגֶד נְשָׁמָה.", "These five 'Bless my soul': about whom did David say them? He said them only about the Holy One and about the soul."),
                E("S2", "ענה לו: <b>לא אמרן אלא כנגד הקדוש ברוך הוא, וכנגד</b>", "He answered him: He said them only about the Holy One, and about..."),
                E("S1", "He answered him: <b>He said them about none other than the Holy One, Blessed be He, and corresponding to the soul,</b>"),
                E("S6", "He composed them with reference to none other than the Holy One, blessed be He, and the soul."),
                E("S8", "What I meant to tell you is this: To whom did David refer in these five verses beginning with 'Bless the Lord, O my soul'? He was alluding only to the Holy One, blessed be He, and to the soul."),
            ],
            "reasoning": "The Aramaic can be read as the speaker asking and answering his own question in one turn. It can also be read as an unmarked reply by the other party. Soncino's 'What I meant to tell you' even suggests the speaker is teaching rather than asking. Only one editorial project, in its plain text, supplies a second speaker.",
            "confidence": "medium",
            "graph_effect": "Keep the earlier reading's open question. The answer and the comparisons have an unresolved voice: the clarifier continuing, or R. Shimon ben Pazi answering. Do not attach 'holds_view' for the soul–God comparison to any named person.",
        },
        {
            "finding_id": "F10",
            "claim": "The manuscripts marked מ', פ' and א' reportedly read the closing line as 'David said: let the soul that has [these five things] come…'. This matches the parallel in Midrash Tehillim 103, where the closing exhortation is also given to David. The printed Bavli line has no speaker.",
            "kind": "textual",
            "evidence": [
                E("S1", "יָבֹא מִי שֶׁיֵּשׁ בּוֹ חֲמִשָּׁה דְבָרִים הַלָּלוּ וִישַׁבֵּחַ לְמִי שֶׁיֵּשׁ בּוֹ חֲמִשָּׁה דְבָרִים הַלָּלוּ.", "Let the one who has these five things come and praise the One who has these five things."),
                E("S15", "יבא מי שיש בו{{דקס|בכת\"י מ', פ' וא'|אמר דוד: תבא נשמה שיש בה}}", "Let the one who has [variant, MSS M, P and A: 'David said: let the soul that has'] come"),
                E("S11", "אמר דוד תבוא הנפש שיש בה כל המדות הללו ותהלל להקב\"ה שיש בו כל המדות הללו", "David said: let the soul that has all these attributes come and praise the Holy One who has all these attributes"),
            ],
            "reasoning": "This is a reported source variant (secondhand) plus a parallel in a separate work. The parallel is not a witness to the Bavli's wording. In the variant, David is a scriptural figure given a line, not a participant in the sages' scene.",
            "confidence": "medium",
            "graph_effect": "For c17, add a variant branch in which the closing exhortation is voiced as David's (reported manuscripts). In the printed branch, keep the voice unknown or the continuing speaker. Create no sage-to-David interaction.",
        },
        {
            "finding_id": "F11",
            "claim": "Two attribution variants are reported around R. Yehuda bar Menasya. (a) After 'there is no artist like our God', the Munich manuscript (marked מ') reportedly adds 'Rav Yehuda bar Menash[ya] said: do not read tzur but tzayyar'. That attributes a line the printed text leaves anonymous. (b) The manuscripts reportedly spell his father's name מנשיא or מנשה. The printed 10a:23 attributes the 'none outlasts You' reading to him explicitly.",
            "kind": "textual",
            "evidence": [
                E("S1", "מַאי ״אֵין צוּר כֵּאלֹהֵינוּ״ — אֵין צַיָּיר כֵּאלֹהֵינוּ.", "What is 'there is no rock like our God'? There is no artist like our God."),
                E("S15", "אין צייר כאלהינו.{{דקס|בכת\"י מ'|אמר רב יהודה בר מנש': אל תקרי צור אלא צייר.}}", "There is no artist like our God. [variant, MS M: 'Rav Yehuda bar Menash(ya) said: do not read tzur but tzayyar.']"),
                E("S1", "אָמַר רַבִּי יְהוּדָה בַּר מְנַסְיָא: אַל תִּקְרֵי", "Rabbi Yehuda bar Menasya said: do not read"),
                E("S15", "אמר רבי יהודה בר מנסיא{{דקס|בכתה\"י|מנשיא, {{ק|או}} מנשה}}", "Rabbi Yehuda bar Menasya said [variant, in the MSS: Menashya, or Menashe]"),
                E("S2", "<b>מאי</b> <small>[מה,</small> משמעות<small>]</small> הכתוב <b>\"כי אין בלתך\"? אמר ר' יהודה בן מנסיא:", "What is the meaning of 'for there is none like You'? R. Yehuda ben Menasya said:"),
            ],
            "reasoning": "In MS M the title is 'Rav', in print 'Rabbi', and the name is abbreviated מנש'. Whether it is the same slot as 10a:23's Rabbi Yehuda bar Menasya is a local-reading question. It is likely in context, since the next line is his, but the title differs. Steinsaltz writes בן where the vocalized text has בר; the patronymic relation is the same.",
            "confidence": "medium",
            "graph_effect": "Keep c14 (the teaching explicitly attributed to R. Yehuda bar Menasya) and c4 (child_of Menasya, with the father slot's name-form variants Menashya/Menashe). For c13 (10a:22, voice unknown), add a source-variant branch attributing it to 'Rav Yehuda bar Menash[ya]' (reported MS M), marked as a variant rather than printed text.",
        },
        {
            "finding_id": "F12",
            "claim": "In the wider context, 'these five Bless my soul' (10a:24) points back to 10a:12-20. There R. Yohanan, in the name of R. Shimon ben Yohai, lists the five 'worlds' in which David said song. Rashi says so ('he counted them above'), and Cohen calls the soul–God reading an alternative explanation to that one.",
            "kind": "textual",
            "evidence": [
                E("S1", "אָמַר רַבִּי יוֹחָנָן מִשּׁוּם רַבִּי שִׁמְעוֹן בֶּן יוֹחַי.", "Rabbi Yohanan said in the name of Rabbi Shimon ben Yohai."),
                E("S1", "לֹא אֲמָרוֹ אֶלָּא כְּנֶגֶד דָּוִד אָבִיו, שֶׁדָּר בַּחֲמִשָּׁה עוֹלָמִים, וְאָמַר שִׁירָה.", "He said it only about David his father, who lived in five worlds and said song."),
                E("S3", "חמשה ברכי נפשי – לעיל חשיב להו:", "Five 'Bless my soul': he counted them above."),
                E("S7", "What follows is an alternative explanation of the fivefold \"Bless the Lord, O my soul\""),
            ],
            "reasoning": "The link is between teachings on the same verses. Nothing says the speakers met or answered each other. The job's context window (10a:21-25) did not include 10a:12-20, so the earlier reading could not see it.",
            "confidence": "high",
            "graph_effect": "Add a teaching-to-teaching link: the soul–God explanation (10a:24-25) is an alternative to the five-worlds explanation (10a:12, R. Yohanan in the name of R. Shimon ben Yohai). Add no person-to-person edge. Note that the five-worlds passage names Solomon and 'David his father'.",
        },
        {
            "finding_id": "F13",
            "claim": "The Soncino translation says R. Shimon ben Pazi 'used to arrange aggadahs [and recite them] before R. Johanan'. Every Hebrew text consulted, and Cohen 1921, have R. Yehoshua ben Levi. The Soncino notes saved here give no reason for the change.",
            "kind": "uncertainty",
            "evidence": [
                E("S8", "used to arrange aggadahs [and recite them] before R. Johanan. He"),
                E("S1", "קַמֵּיהּ דְּרַבִּי יְהוֹשֻׁעַ בֶּן לֵוִי", "before Rabbi Yehoshua ben Levi"),
                E("S5", "והוה מסדר אגדתא קמיה דר' יהושע בן לוי"),
                E("S6", "in the presence of R. Joshua b. Levi"),
            ],
            "reasoning": "Soncino note 25 covers only the word for 'who'. The Wikisource variant notes for this sentence give no alternative for the name. This dossier checked only that page and did not view the manuscripts. So the Soncino rendering may be an error or an unexplained reading, and neither can be confirmed here. R. Yohanan does appear two sugyot earlier (10a:12), but that is no evidence of this variant.",
            "confidence": "medium",
            "graph_effect": "Do not add R. Yohanan to this scene. If the Soncino translation is ingested, flag its 'R. Johanan' as an unexplained divergence rather than a witness.",
        },
        {
            "finding_id": "F14",
            "claim": "Parallel midrashim give related material to other speakers. In Midrash Tehillim 103, R. Yehoshua ben Levi reads the five 'Bless my soul' as the five books of the Torah, and R. Yohanan reads them as five worlds. The painter comparison is 'R. Levi in the name of R. Huna', and the soul comparisons are spoken by David. Devarim Rabbah gives the soul comparisons to 'the Rabbis' (רבנן). The saved Vayikra Rabbah segment opens its soul comparisons with no named speaker.",
            "kind": "textual",
            "evidence": [
                E("S11", "אמר רבי יהושע בן לוי חמשה פעמים כתיב כאן ברכי נפשי כנגד חמשה חומשי תורה", "R. Yehoshua ben Levi said: five times 'Bless my soul' is written here, corresponding to the five books of the Torah"),
                E("S11", "רבי יוחנן אמר כנגד חמשה עולמות שהוא רואה", "R. Yohanan said: corresponding to the five worlds that he sees"),
                E("S11", "א\"ר לוי בשם רבי הונא הצייר הזה צר איקונין", "R. Levi said in the name of R. Huna: this painter draws an image"),
                E("S12", "רַבָּנָן אָמְרֵי בּוֹא וּרְאֵה הַקָּדוֹשׁ בָּרוּךְ הוּא מְמַלֵּא אֶת עוֹלָמוֹ", "The Rabbis say: come and see, the Holy One fills His world"),
                E("S13", "וְכִי מָה רָאָה דָּוִד לִהְיוֹת מְקַלֵּס בְּנַפְשׁוֹ לְהַקָּדוֹשׁ בָּרוּךְ הוּא", "And what did David see to praise the Holy One with his soul?"),
            ],
            "reasoning": "These are separate works with their own attributions. They do not confirm that R. Shimon ben Pazi, or the attendee, said the Bavli's lines, and they do not contradict it. A teaching credited to different people in different works is a transmission difference, not proof of who historically said it. For Vayikra Rabbah only the saved segment was read.",
            "confidence": "high",
            "graph_effect": "Do not transfer the Midrash Tehillim attributions into the Berakhot scene. R. Yehoshua ben Levi's view on the five 'Bless my soul' in Midrash Tehillim is a separate claim in a separate work. It is not a speech turn in Berakhot 10a and creates no link to Rav Shimi.",
        },
        {
            "finding_id": "F15",
            "claim": "Seder HaDorot files this report under two entries: 'Mar Ukva', which it describes as head of the court in Shmuel's time, and 'Rav Shimi bar Ukva'. Filing the Mar Ukva branch under Shmuel's contemporary is a historical identification by name. The Berakhot text does not establish it.",
            "kind": "interpretation",
            "evidence": [
                E("S9", "<b>מר עוקבא</b> אב\"ד בימי שמואל", "Mar Ukva, head of the court in the days of Shmuel"),
                E("S9", "הוה שכיח קמי ר' שמעון בן פזי", "was regularly before R. Shimon ben Pazi"),
                E("S10", "<b>רב שימי בר עוקבא</b> <small>ואמרי לה מר עוקבא הוה שכיח קמיה דר' שמעון בן פזי"),
            ],
            "reasoning": "A shared name does not establish identity. The compiler groups every 'Mar Ukva' citation under one entry. That is a prosopographic hypothesis to be scored separately, not a reading of this passage.",
            "confidence": "low",
            "graph_effect": "Keep 'Mar Ukva' in this passage as a local person placeholder in branch_mar_report. Do not merge it with the court head of Shmuel's era or with any other Mar Ukva without separate evidence. Do not treat 'Mar Ukva' in branch 2 as the father 'Ukva' in branch 1.",
        },
        {
            "finding_id": "F16",
            "claim": "The patronymics are explicit: Rav Shimi bar Ukva (in one branch), R. Shimon ben Pazi, R. Yehoshua ben Levi and R. Yehuda bar Menasya. 'Mar Ukva' has no patronymic; מר is a title. The explicitly quoted or named biblical figures are Hannah (1 Samuel 2:2) and David (composer of the five 'Bless my soul').",
            "kind": "textual",
            "evidence": [
                E("S1", "רַב שִׁימִי בַּר עוּקְבָא", "Rav Shimi son of Ukva"),
                E("S1", "דְּרַבִּי שִׁמְעוֹן בֶּן פַּזִּי", "of Rabbi Shimon son of Pazi"),
                E("S1", "דְּרַבִּי יְהוֹשֻׁעַ בֶּן לֵוִי", "of Rabbi Yehoshua son of Levi"),
                E("S1", "וְהַיְינוּ דְּאָמְרָה חַנָּה", "and this is what Hannah said"),
                E("S17", "{{אמורא|רב שימי בר עוקבא}} ואמרי לה {{אמורא|מר עוקבא}} הוה שכיח קמיה ד{{אמורא|ר' שמעון בן פזי}}"),
            ],
            "reasoning": "By project rule, each patronymic keeps a child_of relation and a local parent placeholder, even though no parent acts. Whether 'bar Ukva' or 'ben Levi' is literal parentage or a conventional name can only be a later identity question; the text gives no reason to doubt it here. The Wikisource tags mark both name forms as amoraim. That is the editors' classification, not a claim that they are two people present.",
            "confidence": "high",
            "graph_effect": "Keep c1-c4 with local parent placeholders. Keep c12 (Hannah) and c16 (David). Do not add a family relation between Ukva (father slot, branch 1) and Mar Ukva (branch 2).",
        },
        {
            "finding_id": "F17",
            "claim": "The earlier reading and review have minor contract problems. (a) The earlier reading has 'Generic human artist' as a person entity. It stands for the 'flesh and blood' class in a comparison, not a person. (b) As the review noted, the same אמר ליה occurrences are each saved under three mention IDs (m15/m27/m30, m16/m28/m31). (c) The review's pass verdict does not note that any named assignment of the asker comes only from translators, and that the known variants were outside the job's sources.",
            "kind": "interpretation",
            "evidence": [
                E("S0b", "Generic human artist"),
                E("S0c", "The same two אמר ליה occurrences are duplicated as m15/m27/m30 and m16/m28/m31."),
                E("S0b", "Does the final answer come from the earlier respondent or belong to the same speaker who reformulates the question?"),
            ],
            "reasoning": "A generic 'flesh and blood' is a category in a teaching. Making it a person node would add a false person to a people graph. The review was scored against the job's own sources, so it could not see the variants in F2, F3, F8, F10 and F11. Its pass verdicts are right within that scope.",
            "confidence": "medium",
            "graph_effect": "Retype 'mortal' as a generic or class referent that is not eligible as a graph person. Collapse the duplicate mentions onto one ID per occurrence. Keep the review's verdicts, with the scope note above.",
        },
    ]

    alternative_readings = [
        {"id": "A1", "scope": "Name of the attendee (10a:21)",
         "readings": ["Rav Shimi bar Ukva (printed; also 'bar Akaviah' reported for MS A)",
                      "Mar Ukva (printed as 'some say'; reported absent in the manuscripts per the Wikisource explained edition)"],
         "status": "open", "evidence_findings": ["F1", "F2"]},
        {"id": "A2", "scope": "Who arranged aggadah before R. Yehoshua ben Levi",
         "readings": ["R. Shimon ben Pazi (reported manuscript reading דהוה; Cohen, Soncino, William Davidson English/Steinsaltz)",
                      "The attendee (printed והוה read with the attendee as subject; Seder HaDorot filing; Wikisource editor's tentative lean)"],
         "status": "open", "evidence_findings": ["F3", "F4", "F7"]},
        {"id": "A3", "scope": "Asker and answerer in 10a:21",
         "readings": ["Attendee asks R. Shimon ben Pazi, who answers (Cohen, Soncino notes, Steinsaltz Hebrew; fits Rashi)",
                      "R. Shimon ben Pazi asks and the attendee answers (William Davidson English 10a:21 only; its own 10a:24 contradicts it)",
                      "Attendee asks R. Yehoshua ben Levi (Wikisource editor's tentative conjecture)"],
         "status": "open; the first has the most support among interpretations, and none is explicit", "evidence_findings": ["F5", "F6", "F7"]},
        {"id": "A4", "scope": "Speech act in 10a:24",
         "readings": ["Restates his own question (printed אנא הכי קא אמינא לך)",
                      "Reports a tradition he heard, source unnamed (reported MS A אנא הכי שמיע לי)"],
         "status": "open", "evidence_findings": ["F8"]},
        {"id": "A5", "scope": "Voice of the answer and the five comparisons (10a:24-25)",
         "readings": ["R. Shimon ben Pazi answers (Steinsaltz/William Davidson plain text)",
                      "The clarifying speaker continues (no turn marker; Cohen and Soncino mark none)",
                      "Closing exhortation voiced as David's (reported MSS M, P, A)"],
         "status": "open", "evidence_findings": ["F9", "F10"]},
        {"id": "A6", "scope": "Attribution of 'there is no artist like our God' (10a:22)",
         "readings": ["Anonymous (printed)", "Rav Yehuda bar Menash[ya] (reported MS M)"],
         "status": "open", "evidence_findings": ["F11"]},
    ]

    unresolved = [
        "No manuscript image or transcription was viewed. Every manuscript reading here is secondhand, from the Wikisource explained edition (mainly Dikdukei Soferim or Hachi Garsinan), Cohen 1921 or Soncino, and these may share one origin.",
        "The Wikisource page does not expand its sigla (מ', פ', א', בו', ס\"פ). Reading מ' as Munich rests on agreement with Cohen's 'M.' and Soncino's 'MS.M.'. Which manuscripts 'the manuscripts' covers was not established.",
        "The parse of the compressed note on the name line (that 'and some say Mar Ukva' is absent in the manuscripts) is this dossier's reading of the template arguments.",
        "Why Soncino has 'R. Johanan' for R. Yehoshua ben Levi was not established.",
        "Who says the answer and the five comparisons in 10a:24-25 remains open.",
        "Only the saved segment of Vayikra Rabbah 4:8 was read; any attribution in the preceding segment was not checked. Pesikta Rabbati 10:1, a Sefaria link for 10a:24-25, was fetched, but the parallel was not located in the saved text, and nothing is claimed from it.",
        "No historical identity for Rav Shimi bar Ukva, Mar Ukva, R. Shimon ben Pazi or R. Yehuda bar Menasya is established here.",
    ]

    proposed_corrections = [
        {"existing_claim_id": "reading group 'visitor' (c1, c5, c6)",
         "change": "Keep both branches. Add witness-type metadata: the Mar Ukva branch is printed-edition text and is reported absent in the manuscripts. Add 'bar Akaviah' (reported MS A) as a name-form variant in the Shimi branch. Record the reported בשמעתתא addition (MSS M, P) as a variant on the attendance claims.",
         "why": "F1, F2"},
        {"existing_claim_id": "reading group 'arranger' (c7, c8, c9)",
         "change": "Keep both branches. Attach the reported manuscript reading דהוה as source-variant support for branch_shimon_arranges. Attach Seder HaDorot's filing and the Wikisource editor's lean as interpretation-level support for branch_visitor_arranges.",
         "why": "F3, F4"},
        {"existing_claim_id": "c10, c11, c15 and coreference candidates m27-m32",
         "change": "Add branch-scoped interpretation claims: the attendee asks R. Shimon ben Pazi, R. Shimon ben Pazi answers, and the attendee clarifies. Mark them basis=interpretation, medium, not explicit. Keep yehoshua as a low-support, conjecture-only candidate. Collapse the duplicate mention IDs.",
         "why": "F5, F6, F7, F17"},
        {"existing_claim_id": "c15",
         "change": "Add a source-variant branch for the speech act: 'I heard thus' (reported MS A), a report of an unnamed tradition, as against the printed restatement of the question.",
         "why": "F8"},
        {"existing_claim_id": "c17 and open_questions",
         "change": "Keep the voice open. Add a variant branch in which the closing exhortation is voiced as David's (reported MSS M, P, A).",
         "why": "F9, F10"},
        {"existing_claim_id": "c13",
         "change": "Add a source-variant attribution of 10a:22 to Rav Yehuda bar Menash[ya] (reported MS M). Keep the printed branch anonymous.",
         "why": "F11"},
        {"existing_claim_id": "c4",
         "change": "Record the father-slot name-form variants: Menasya (print), Menashya or Menashe (reported MSS). Record the title Rav in the MS M line at 10a:22.",
         "why": "F11"},
        {"existing_claim_id": "entity 'mortal'",
         "change": "Retype it as a generic or class referent, not a person.",
         "why": "F17"},
        {"existing_claim_id": "episode.needed_context",
         "change": "Add 10a:12-20 as required context. It holds the five-worlds teaching (R. Yohanan in the name of R. Shimon ben Yohai) that 10a:24 answers. Add a teaching-to-teaching 'alternative explanation' link, with no person edge.",
         "why": "F12"},
    ]

    ontology_lessons = [
        "One editorial project can contradict itself on who speaks (William Davidson English 10a:21 against 10a:24 and its Hebrew). Store translator-supplied speaker names as interpretations, check them for consistency, and never pool them with the same project's other outputs.",
        "Manuscript readings reported by later works (Dikdukei Soferim through a wiki page, Cohen's 'M.', Soncino's 'MS.M.') are their own evidence type. They may share one origin and should not be counted as independent witnesses.",
        "A reported-alternative name (ואמרי לה X) can itself be a printed-edition element that manuscripts lack. Branch groups need witness-type metadata, not only branch labels.",
        "Variants can change the speech act, not only the speaker: 'I was saying to you' against 'I heard thus'. Speech claims need a speech-act field that can branch.",
        "A manuscript can attribute a line that the print leaves anonymous, as here, or can give a closing line to a scriptural figure. Attribution should be branchable per witness.",
        "Generic comparison figures ('flesh and blood', 'the soul') are not persons and should be kept out of person nodes.",
        "A modern editor's conjecture is its own evidence type, below a commentary and far below the text.",
    ]

    return {
        "status": "researched",
        "question": "In Berakhot 10a:21-25, who are the people and how are they related? Who arranges aggadah before R. Yehoshua ben Levi, who asks and who answers, and which speech turns and attributions are explicit, interpreted or variant?",
        "scope_note": "Checked: the Sefaria William Davidson Aramaic, English and Hebrew; the Wikisource Hebrew; Rashi; Maharsha (skimmed, not cited); Cohen 1921 and its footnotes; Soncino via halakhah.com; the Hebrew Wikisource explained edition with variant notes; Seder HaDorot; Mevo HaTalmud (Chajes); Midrash Tehillim 103; Devarim Rabbah 2:37; and a Vayikra Rabbah 4:8 segment. Manuscripts were not viewed. Conclusions are scoped to these sources.",
        "findings": findings,
        "alternative_readings": alternative_readings,
        "unresolved": unresolved,
        "proposed_corrections": proposed_corrections,
        "ontology_lessons": ontology_lessons,
        "graph_status": "All graph proposals are provisional. No historical identity or date is asserted.",
    }
