# Dossier content for challenge-10. Executed by build_dossier.py, which supplies ev(), vis() and the source table.
STATUS = "researched"
QUESTION = ("Who speaks, acts, is named or is cited in Menachot 29b:3 (with its continuation 29b:4-5)? Which graph "
            "claims are explicit, which rest on interpretation, and which alternatives must stay open when the first "
            "reading is checked against wider context, translations, commentaries, a manuscript and an early print?")
SCOPE = ("Menachot 29a (end) and 29b (Sefaria: Wikisource, William Davidson Aramaic, vocalized and English, Sefaria "
         "Community Translation); Rashi; Steinsaltz Hebrew; Maharsha (Chidushei Agadot); Ben Yehoyada; Petach Einayim; "
         "Marit HaAyin; parallels Shabbat 89a, Sanhedrin 111a, Berakhot 61b; Sefer Tagin introduction (Otzar Midrashim); "
         "Seder HaDorot; Ein Yaakov (Daat vocalized Hebrew; Glick 1916 Hebrew and English); Munich Cod. hebr. 95 page image 0834; Bomberg "
         "1523 page image. Not checked: other manuscripts (for example Vatican or Florence), Hachi Garsinan variant "
         "apparatus, Dikdukei Soferim, and the academic studies the Wikipedia article cites.")

FINDINGS = [
 {"finding_id": "F1",
  "claim": "The whole story is one report: Rav Yehuda states it in Rav's name. Every event and speech inside it is part of what Rav is reported to have said. Neither Rav Yehuda nor Rav appears as a participant in the scenes.",
  "kind": "textual",
  "evidence": [
   ev("men29b", "אמר רב יהודה אמר רב בשעה שעלה משה למרום", "Rav Yehuda said, Rav said: When Moses went up on high", "Wikisource 29b:3"),
   ev("men29b", "§ <b>Rav Yehuda says</b> that <b>Rav says: When Moses ascended on High,", None, "William Davidson English 29b:3"),
   ev("men29a", "אמר רב יהודה אמר רב לא נצרכה אלא לקוצה של יוד", "Rav Yehuda said, Rav said: it was needed only for the thorn of a yod", "Wikisource 29a:17"),
  ],
  "reasoning": "The chain opens the story and is never resumed, so it governs 29b:3-5. The same chain is used just before, at 29a:17, for a ruling about the thorn (קוץ) of a yod; the story's 'each and every thorn' picks up that word. That placement is a literary link inside the sugya. It gives no evidence that Rav Yehuda heard Rav tell this particular story on a particular occasion, and it says nothing about when either of them lived.",
  "confidence": "high",
  "graph_effect": "Keep c1 (reports_in_name_of Rav Yehuda to Rav) as the only link between the two amoraim. Do not add direct hearing, co-presence or life order. All story claims carry voice = Rav, as transmitted by Rav Yehuda."},
 {"finding_id": "F2",
  "claim": "In my visual reading, the Munich 95 manuscript has the same chain, 'Rav Yehuda said, Rav said'.",
  "kind": "textual",
  "evidence": [
   vis("munich95_834", "[א'] רב יהודה א' רב בשעה שע[לה]", "[said] Rav Yehuda, said Rav: at the time that [Moses] went up", "Munich 95 page 0834, end of line 2 of the main text"),
  ],
  "reasoning": "The abbreviation is written as רב יהודה, not ר' יהודה, so it does not point to a tanna. This is one witness only, and I have not checked any others.",
  "confidence": "medium",
  "graph_effect": "Supports keeping the chain as printed. No alternative attribution for the story was found in the witnesses checked."},
 {"finding_id": "F3",
  "claim": "Akiva son of Yosef is named only inside God's answer to Moses, as a person who will exist 'at the end of several generations'. The patronymic names Yosef as his father. The Hebrew never gives him the title Rabbi. The students call him 'רבי' (my teacher) when they speak to him. The title 'Rabbi Akiva' appears only in the editors' plain-text explanation in the William Davidson English and in Steinsaltz.",
  "kind": "textual",
  "evidence": [
   ev("men29b", "אדם אחד יש שעתיד להיות בסוף כמה דורות ועקיבא בן יוסף שמו", "There is one man who will be at the end of several generations, and Akiva son of Yosef is his name", "Wikisource 29b:3"),
   ev("men29b", "Moses <b>went and sat at the end of the eighth row</b> in Rabbi Akiva’s study hall", None, "William Davidson English 29b:4 (plain words are editorial)"),
   ev("steinsaltz", "<b>אמר לו: אדם אחד יש שעתיד להיות בסוף כמה דורות ועקיבא בן יוסף שמו,</b> ר' עקיבא,", "Steinsaltz adds, outside the bold text: Rabbi Akiva", "Steinsaltz 29b:3"),
  ],
  "reasoning": "The father–son relation is written in the name itself (בן יוסף), so it is explicit and stays in the graph with a local placeholder for Yosef, even though Yosef never acts. The whole statement is a prediction spoken by God inside Rav's story. Identifying this Akiva with the tanna Rabbi Akiva is clearly the storyteller's intent and is what the commentators assume. It is still a separate identity decision; the text does not state it. The William Davidson English and Steinsaltz come from the same editorial project, so they count as one editorial voice, not two witnesses.",
  "confidence": "high",
  "graph_effect": "Keep c2 (Akiva child_of Yosef) with modality prediction, voice God, and literal kinship. Keep Yosef as a local placeholder. Record the identification with the historical Rabbi Akiva as a separate, pending identity decision whose support comes from commentary."},
 {"finding_id": "F4",
  "claim": "In 29b:4 the teacher is never named. The Hebrew says someone 'reached one matter' and 'his students' asked him. It is story coreference that makes this teacher Akiva: Moses has just asked to be shown 'him'. The William Davidson English writes 'Rabbi Akiva' three times in 29b:4, always in plain editorial text.",
  "kind": "interpretation",
  "evidence": [
   ev("men29b", "אמר לפניו רבש\"ע הראהו לי", "He said before Him: Master of the Universe, show him to me", "Wikisource 29b:4"),
   ev("men29b", "כיון שהגיע לדבר אחד אמרו לו תלמידיו רבי מנין לך אמר להן הלכה למשה מסיני", "When he reached one matter, his students said to him: My master, from where do you have this? He said to them: A law to Moses from Sinai", "Wikisource 29b:4"),
   ev("men29b", "<b>When</b> Rabbi Akiva <b>arrived at</b> the discussion of <b>one matter, his students said to him: My teacher, from where do you</b> derive this?", None, "William Davidson English 29b:4"),
   ev("ein_yaakov_glick", "Moses went back eight rows, but he could not understand what they (R. Akiba and his associates) were arguing.", None, "Glick 1916 English; the parenthesis is the translator's"),
  ],
  "reasoning": "The coreference is secure within the story: God agrees to show 'him', and Moses is taken to a teacher and his students. The link is still a reading of pronouns and possessives, and the graph should mark it that way. The Glick translation (1916, a different editorial line) makes the same identification with the translator's own parenthesis, and it also names 'associates' for 'they'.",
  "confidence": "high",
  "graph_effect": "c12, c13 and c14 are right to use basis local_coreference. Add a note that the teacher is unnamed in 29b:4 and that 'Rabbi Akiva' there is editorial. The students stay an unnamed local group, scoped to the depicted scene."},
 {"finding_id": "F5",
  "claim": "The witnesses disagree on the number of rows. The Vilna-based texts, the Bomberg 1523 print and the Glick Ein Yaakov (its Hebrew and its English) read 'eight rows'. The Daat Ein Yaakov on Sefaria prints 'eight (teen) rows', with עשרה in parentheses. In my visual reading, Munich 95 reads 'eighteen rows'. Ben Yehoyada says the Ein Yaakov reads 'eighteen rows', and Seder HaDorot paraphrases the passage with eighteen.",
  "kind": "textual",
  "evidence": [
   ev("men29b", "הלך וישב בסוף שמונה שורות ולא היה יודע מה הן אומרים", "He went and sat at the end of eight rows and did not know what they were saying", "Wikisource 29b:4"),
   ev("ein_yaakov_glick", "הלך וישב לסוף שמונה שורות ולא היה יודע מה הם אומרים", None, "Glick Ein Yaakov, Hebrew text, Menachot"),
   ev("ein_yaakov_daat", exact("ein_yaakov_daat", "הלך וישב לסוף שמונה (עשרה) שורות, ולא היה יודע מה הם אומרים"), "He went and sat at the end of eight (teen) rows, and did not know what they were saying", "Ein Yaakov (Daat), vocalized; the parenthesis is the edition's"),
   vis("bomberg", "בסוף שמונה שורות ולא היה יודע מה הן או'", "at the end of eight rows and did not know what they were saying", "Bomberg 1523, main text"),
   vis("munich95_834", "שמונה עשר שורות ולא היה יודע מה הם או'", "eighteen rows, and he did not know what they were saying", "Munich 95 page 0834, start of line 5"),
   ev("ben_yehoyada", exact("ben_yehoyada", "הלך וישב לסוף שמונה עשרה שורות.</b> כן הגירסא בעין יעקב."), "He went and sat at the end of eighteen rows. This is the reading in Ein Yaakov.", "Ben Yehoyada 29b:2"),
   ev("seder_hadorot", "והלך וישב לסוף י\"ח שורות ושמע דבריו", "and he went and sat at the end of eighteen rows and heard his words", "Seder HaDorot, Tanaim and Amoraim 2917:11"),
  ],
  "reasoning": "This is a real source variant. The Munich reading is my own visual reading and needs checking. Ben Yehoyada's report matches the Daat Ein Yaakov, where 'עשרה' is present in parentheses. That edition's parentheses may mark a word it doubts or an alternative; its note policy was not checked. The Glick Ein Yaakov Hebrew reads eight, so the Ein Yaakov editions themselves differ. The count changes no person or relation. It matters for a faithful statement label and as a reminder that the printed text is one witness.",
  "confidence": "medium",
  "graph_effect": "No person or edge changes. Store 'eighteen rows' as a variant reading on c10, typed as a manuscript/edition variant, separate from any emendation."},
 {"finding_id": "F6",
  "claim": "The witnesses also disagree on the verb 'reached'. The printed text has singular שהגיע ('he reached'), which suits the teacher. The Bomberg print has plural שהגיעו ('they reached'), which suits the whole class, and Maharsha's gloss is also plural.",
  "kind": "textual",
  "evidence": [
   ev("men29b", "כיון שהגיע לדבר אחד", "when he reached one matter", "Wikisource 29b:4"),
   vis("bomberg", "תשש כחו כיון שהגיעו לדבר אחד אמרו לו תלמידיו רבי מנין לך", "his strength failed; when they reached one matter his students said to him: my master, from where do you have this", "Bomberg 1523, main text"),
   ev("maharsha", "כיון שהגיעו לדבר אחד דהיינו מסופן לראשן עד הא' שהוא מורה על אחד", "when they reached 'one matter', that is, from the end [of the letters] to their start, up to the alef, which points to One", "Maharsha on 29b"),
  ],
  "reasoning": "With the singular, the teacher is the one who reaches the matter. With the plural, the group does. In both, the students ask and the teacher answers. So the speech turns stay the same, but the actor of 'reaching' should not be fixed as Akiva alone. Maharsha's plural is part of his own gloss, not a quoted lemma, so it is weaker evidence of the text he read.",
  "confidence": "medium",
  "graph_effect": "Do not create a claim that Akiva alone 'reached' the matter. If this action is modelled, give it a reading branch: teacher (printed text) or class (Bomberg)."},
 {"finding_id": "F7",
  "claim": "The printed text does not say whose mind was put at ease. Rashi says it was Moses's, because Akiva was speaking in Moses's name. The William Davidson English adds 'When Moses heard this' in plain text. In my tentative visual reading, Munich 95 names Moses explicitly at this point.",
  "kind": "interpretation",
  "evidence": [
   ev("men29b", "אמר להן הלכה למשה מסיני נתיישבה דעתו", "He said to them: a law to Moses from Sinai. His mind was settled.", "Wikisource 29b:4"),
   ev("rashi", "נתיישבה דעתו - של משה הואיל ומשמו אומר אע\"פ שעדיין לא קיבלה:", "his mind was settled - Moses's, since he [Akiva] was saying it in his name, although he had not yet received it", "Rashi 29b:4:2"),
   ev("men29b", "When Moses heard this, <b>his mind was put at ease,</b>", None, "William Davidson English 29b:4 (plain words are editorial)"),
   vis("munich95_834", "כיון ששמע משה כך נתישבה דעתו", "once Moses heard this, his mind was settled", "Munich 95 page 0834, end of line 5 to start of line 6; letters uncertain"),
  ],
  "reasoning": "In the printed text, 'his mind' most naturally belongs to Moses, whose weakness was just described. Rashi's reason is itself a claim that Akiva quotes Moses. If my reading of the Munich wording is right, that witness makes Moses explicit. The printed text relies on coreference; that manuscript, as I read it, states the name.",
  "confidence": "medium",
  "graph_effect": "Keep c16 on Moses. Add Rashi as commentary support and the Munich wording as a separate evidence type (visual manuscript reading). Mark the basis as coreference for the printed text."},
 {"finding_id": "F8",
  "claim": "Akiva's answer 'a law to Moses from Sinai' uses a fixed category name to say where a teaching comes from. It is not a speech by Moses and it does not show that Akiva heard Moses. Translations differ on Moses's role: the William Davidson English says 'to Moses', the Community Translation says 'taught to Moshe', and Glick says 'delivered by Moses'.",
  "kind": "interpretation",
  "evidence": [
   ev("men29b", "Rabbi Akiva <b>said to them:</b> It is <b>a <i>halakha</i></b> transmitted <b>to Moses from Sinai.</b>", None, "William Davidson English 29b:4"),
   ev("men29b", "He said to them, \"It is a law [that was taught] to Moshe at Sinai.\"", None, "Sefaria Community Translation 29b:4"),
   ev("ein_yaakov_glick", "'This law,' replied R. Akiba, 'is a tradition delivered by Moses on Sinai.\"", None, "Glick 1916"),
   ev("rashi", "הואיל ומשמו אומר", "since he says it in his name", "Rashi 29b:4:2"),
  ],
  "reasoning": "The Hebrew הלכה למשה מסיני literally means 'a law to Moses from Sinai'. This names Moses as the one who received it at Sinai, and each translator fills in the role differently. Rashi calls it speaking 'in his name', which is a citation. The irony of the story is that Moses has not yet received it, as Rashi says. So there is no meeting, no hearing and no teaching link between Moses and Akiva.",
  "confidence": "high",
  "graph_effect": "Keep c15 as a source attribution with voice = Akiva, inside Rav's story. Model it as citing the Sinai tradition, with Moses as recipient; do not model it as a speech act by Moses. Keep the earlier note that denies hearing. Do not add teacher/student or transmission edges between Moses and Akiva."},
 {"finding_id": "F9",
  "claim": "No one who harms Akiva is named. The Hebrew says only that 'they were weighing his flesh in the meat market'. The Romans, torture and death appear only in the editors' explanations: the William Davidson English plain text and the Steinsaltz Hebrew. Rashi links the scene to Berakhot 61b, where Akiva's flesh is combed with iron combs. The Community Translation renders the phrase itself as 'flaying his flesh with [iron] combs', which is Rashi's gloss rather than the words of the text.",
  "kind": "interpretation",
  "evidence": [
   ev("men29b", "חזר לאחוריו ראה ששוקלין בשרו במקולין", "He turned back and saw that they were weighing his flesh in the meat market", "Wikisource 29b:5"),
   ev("men29b", "<b>flesh in a butcher shop [<i>bemakkulin</i>],</b> as Rabbi Akiva was tortured to death by the Romans.", None, "William Davidson English 29b:5 (plain words are editorial)"),
   ev("steinsaltz", "שנהרג ביסורים על ידי הרומאים", "who was killed with torments by the Romans", "Steinsaltz 29b:5 (outside bold text)"),
   ev("rashi", "במקולין - מקום הקצבין שוקלין בשרו כדאמר בברכות (דף סא:) שסרקו בשרו במסרקות ברזל:", "in the meat market - the butchers' place; they weigh his flesh, as it says in Berakhot (61b) that they combed his flesh with iron combs", "Rashi 29b:5:1"),
   ev("men29b", "and saw that they were flaying his flesh with [iron] combs.", None, "Sefaria Community Translation 29b:5"),
   ev("ein_yaakov_glick", "he noticed that his flesh is being marketed in meat markets", None, "Glick 1916"),
  ],
  "reasoning": "'בשרו' (his flesh) refers to Akiva through 'his Torah … his reward'. The people weighing are an unnamed plural. Glick stays with the market image. The Community Translation follows Rashi's cross-reference. Only the Koren/Steinsaltz editorial layer names Rome, and that is one editorial voice.",
  "confidence": "high",
  "graph_effect": "Keep c22 and c23 as a depicted future scene with unnamed weighers. Do not add a Roman agent, a 'killed_by' edge or an execution date from this passage. A later link to Berakhot 61b should be recorded as Rashi's cross-reference, not as the words of this passage."},
 {"finding_id": "F10",
  "claim": "A different passage, Berakhot 61b, tells of Akiva's execution. There his students address him, and the ministering angels, not Moses, say 'This is Torah and this its reward?'. The two passages share wording but are separate stories.",
  "kind": "textual",
  "evidence": [
   ev("berakhot61b", "בשעה שהוציאו את ר' עקיבא להריגה זמן ק\"ש היה והיו סורקים את בשרו במסרקות של ברזל", "When they took Rabbi Akiva out to be killed it was the time of Shema, and they were combing his flesh with iron combs", "Wikisource Berakhot 61b:9"),
   ev("berakhot61b", "<b>The ministering angels said before the Holy One, Blessed be He: This is Torah and this its reward?</b>", None, "William Davidson English Berakhot 61b:10"),
   ev("seder_hadorot", "ובברכות (שם) אמרו מלאכי השרת זו תורה וזו שכרה והשיב הקב\"ה ממתים ידך ה' ממתים מחלד. ולא השיב להם כמו למשה שתוק", "In Berakhot the ministering angels said 'this is Torah and this its reward', and God answered … and did not answer them as He answered Moses, 'be silent'", "Seder HaDorot 2917:11"),
  ],
  "reasoning": "Seder HaDorot sets the two passages side by side and notes that God answers them differently. That makes them related tellings with different speakers. This passage cannot be treated as a second observation of the Berakhot scene.",
  "confidence": "high",
  "graph_effect": "Do not merge speech claims across the two passages. The angels' question belongs to Berakhot 61b; Moses's question belongs to Menachot 29b. Any cross-passage link is a commentary-based relation."},
 {"finding_id": "F11",
  "claim": "The opening scene, Moses finding God tying crowns on the letters, also appears at Shabbat 89a, but there Rabbi Yehoshua ben Levi tells it and the dialogue is different. Sanhedrin 111a has a baraita with a similar opening, in which God is writing 'slow to anger'.",
  "kind": "textual",
  "evidence": [
   ev("shabbat89a", "וא\"ר יהושע בן לוי בשעה שעלה משה למרום מצאו להקב\"ה שהיה קושר כתרים לאותיות אמר לו משה אין שלום בעירך", "And Rabbi Yehoshua ben Levi said: When Moses went up on high he found the Holy One tying crowns to letters. He said to him: Moses, is there no greeting in your town?", "Wikisource Shabbat 89a:5"),
   ev("sanhedrin111a", "כשעלה משה למרום מצאו להקב\"ה שיושב וכותב ארך אפים", "When Moses went up on high he found the Holy One sitting and writing 'slow to anger'", "Wikisource Sanhedrin 111a:12"),
  ],
  "reasoning": "These are separate stories that share a stock opening. They are not rival attributions of the Menachot story, which in every witness checked has Rav Yehuda reporting in Rav's name. The Sefaria link index connects Menachot 29b:3 to both as Mesorat HaShas parallels.",
  "confidence": "high",
  "graph_effect": "Do not add Rabbi Yehoshua ben Levi to this passage's graph. Do not treat Shabbat 89a as a textual alternative for c1. Keep each opening scene's claims with its own passage."},
 {"finding_id": "F12",
  "claim": "Commentators disagree about what kind of event the classroom visit is. The editorial translation treats it as a future classroom that Moses is shown. Ben Yehoyada says Moses saw the souls of Akiva and his students before they were born. Maharsha reads the rows and the 'one matter' as hints about the order of the letters.",
  "kind": "interpretation",
  "evidence": [
   ev("ben_yehoyada", "עדיין לא בא רבי עקיבה לעולם הזה והוא מצא את נשמת רבי עקיבה ונשמות תלמידיו לומדים תורה לפני ה'", "Rabbi Akiva had not yet come to this world; he found the soul of Rabbi Akiva and the souls of his students studying Torah before God", "Ben Yehoyada 29b:2"),
   ev("ben_yehoyada", "ודע דהליכה וישיבה זו היא בהבטת השכל", "Know that this going and sitting is by the mind's gaze", "Ben Yehoyada 29b:2"),
   ev("maharsha", "וז\"ש שישב משה לסוף ח' שורות דהיינו שיש ח' שורות א\"ב משונות לפי הנקודות", "This is why Moses sat at the end of eight rows: there are eight rows of alphabet that differ by vowel points", "Maharsha on 29b"),
  ],
  "reasoning": "All three readings agree that Moses and Akiva do not share a historical time. The text itself marks the scene as a showing: God says 'turn back', and the scene sits inside a heavenly ascent. The first reading's time_scope 'Future classroom shown inside the story' is right as far as it goes. Whether the scene is a vision, a meeting of souls or an allegory is commentary and should not be decided in the graph.",
  "confidence": "high",
  "graph_effect": "Keep the vision/depicted-scene modality on c10, c12-c16, c22 and c23. Never output historical co-presence or a Moses–Akiva teacher/student edge. Store the soul and allegory readings as commentary alternatives, not branches of the text."},
 {"finding_id": "F13",
  "claim": "Later kabbalistic commentaries say Akiva was a spark of the patriarch Jacob, or that he came from the soul-root of Issachar and of Cain. These are claims about souls, not family relations, and they do not come from this passage.",
  "kind": "interpretation",
  "evidence": [
   ev("marit_haayin", "במ\"ש גורי האר\"י ז\"ל שהיה ניצוץ יעקב אבינו ע\"ה ורמוז בשמו עקיבא אותיות יעקב", "as the Ari's disciples wrote, that he was a spark of Jacob our father, hinted in his name Akiva, the letters of Yaakov", "Marit HaAyin on 29b:1"),
   ev("petach_einayim", "פירש הרב מהרח\"ו זצ\"ל דע כי רבי עקיבא משרש יששכר", "Rabbi Chaim Vital explained: know that Rabbi Akiva is from the root of Issachar", "Petach Einayim on 29b:2"),
  ],
  "reasoning": "A spark or soul-root claim is not kinship and is not evidence about the historical Akiva. It sits in a separate interpretive layer.",
  "confidence": "high",
  "graph_effect": "Do not create family, descent or identity edges from these claims. If they are kept at all, they belong in a commentary-reception layer outside the person graph."},
 {"finding_id": "F14",
  "claim": "The first reading captured all twelve speech turns in 29b:3-5: five from Moses to God, five from God to Moses, one from the students to the teacher and one from the teacher back. It did miss some mentions: Moses is named inside the teacher's answer, and Akiva is referred to by the descriptions 'one man' and 'such a man', by 'him' in 'show him to me', and by the possessives 'his Torah' and 'his reward'. The first reading attaches Moses's weakness to Moses only through the pronoun in 'his strength'; Munich 95, in my reading, may add 'of Moses' here, but I could not read it with confidence.",
  "kind": "textual",
  "evidence": [
   ev("pilot_input", "אמר לו אדם אחד יש שעתיד להיות", "He said to him: there is one man who will be", "s1"),
   ev("pilot_input", "יש לך אדם כזה ואתה נותן תורה ע\"י", "You have such a man and You give the Torah through me?", "s3"),
   ev("pilot_input", "הראיתני תורתו הראני שכרו", "You showed me his Torah; show me his reward", "s3"),
   ev("pilot_input", "הלכה למשה מסיני", "a law to Moses from Sinai", "s2"),
  ],
  "reasoning": "Speech turns in the listed claims: Moses to God, c5, c8, c18, c20 and c24 (5). God to Moses, c6, c9, c19, c21 and c25 (5). Students to teacher, c13 (1). Teacher to students, c14 (1). That makes 12, matching the text. The mention list has no entry for the Moses inside 'הלכה למשה מסיני' (claim c15 uses it as an object) and none for the descriptive references to Akiva. 'ע\"י' (through me) refers to Moses.",
  "confidence": "high",
  "graph_effect": "Add mentions: Moses inside Akiva's answer (s2), and 'אדם אחד', 'אדם כזה', 'הראהו', 'תורתו' and 'שכרו' for Akiva. No new person entities are needed."},
 {"finding_id": "F15",
  "claim": "The text says 'turn back' (חזור לאחורך) twice, and the witnesses differ on whether the second one has the word 'behind you'. Wikisource prints it in brackets, the William Davidson Aramaic leaves it out, and both Ein Yaakov texts have it. Munich 95, in my visual reading, has it too.",
  "kind": "textual",
  "evidence": [
   ev("men29b", "אמר לו חזור [לאחורך] חזר לאחוריו", None, "Wikisource 29b:5"),
   ev("men29b", "אמר לו חזור חזר לאחוריו ראה ששוקלין בשרו במקולין", None, "William Davidson Aramaic 29b:5"),
   ev("ein_yaakov_glick", "א״ל חזור לאחוריך חזר לאחוריו ראה ששוקלין בשרו במקולין", None, "Glick Ein Yaakov, Hebrew text"),
   ev("ein_yaakov_daat", exact("ein_yaakov_daat", "אמר לו: חזר לאחוריך. חזר לאחוריו, וראה ששוקלין בשרו במקולין"), None, "Ein Yaakov (Daat), vocalized"),
   vis("munich95_834", "א\"ל חזור לאחוריך חזר לאחוריו וראה שהין שוקלין בשרו במקולין", "He said to him: turn behind you. He turned behind him and saw that they were weighing his flesh in the meat market", "Munich 95 page 0834, line 7"),
  ],
  "reasoning": "The bracket marks an editorial addition in the Wikisource text, and the first reading quoted it as part of the evidence for c21. The wording affects no person. The evidence quote should nonetheless keep the bracket visible and note that the word is absent from the William Davidson Aramaic.",
  "confidence": "medium",
  "graph_effect": "c21: keep, and add a variant note on the bracketed word. No change to people."},
]

ALTERNATIVES = [
 {"id": "A1", "topic": "Number of rows", "readings": [
   {"reading": "eight rows", "supported_by": ["men29b (Wikisource, William Davidson)", "bomberg (visual)", "ein_yaakov_glick (Hebrew and English)"]},
   {"reading": "eight (teen) rows, with עשרה in parentheses", "supported_by": ["ein_yaakov_daat"]},
   {"reading": "eighteen rows", "supported_by": ["munich95_834 (visual, tentative)", "ben_yehoyada (reports Ein Yaakov)", "seder_hadorot (paraphrase)"]}],
  "status": "open; no person effect"},
 {"id": "A2", "topic": "Who 'reached one matter'", "readings": [
   {"reading": "the teacher (singular שהגיע)", "supported_by": ["men29b", "ein_yaakov_daat"]},
   {"reading": "the class (plural שהגיעו)", "supported_by": ["bomberg (visual)", "maharsha (gloss)"]}],
  "status": "open"},
 {"id": "A3", "topic": "Whose mind was put at ease", "readings": [
   {"reading": "Moses", "supported_by": ["rashi", "William Davidson English plain text", "munich95_834 (visual, tentative, names Moses)"]},
   {"reading": "unspecified in the printed Hebrew (pronoun only)", "supported_by": ["men29b Wikisource"]}],
  "status": "Moses strongly supported; keep the basis as coreference for the printed text"},
 {"id": "A4", "topic": "What kind of event the classroom visit is", "readings": [
   {"reading": "a future classroom Moses is shown", "supported_by": ["William Davidson English", "Steinsaltz"]},
   {"reading": "a meeting with the souls of Akiva and his students before birth, seen by the mind", "supported_by": ["ben_yehoyada"]},
   {"reading": "an allegory of letter order and vowel rows", "supported_by": ["maharsha"]}],
  "status": "commentary alternatives; all deny historical co-presence"},
 {"id": "A5", "topic": "Moses's role in 'a law to Moses from Sinai'", "readings": [
   {"reading": "Moses as recipient ('to Moses', 'taught to Moshe')", "supported_by": ["William Davidson English", "Sefaria Community Translation"]},
   {"reading": "Moses as the one who passed it on ('delivered by Moses')", "supported_by": ["ein_yaakov_glick"]},
   {"reading": "Akiva speaks in Moses's name", "supported_by": ["rashi"]}],
  "status": "translation choices; the Hebrew formula is fixed; model as a source attribution, never as Moses speaking"},
 {"id": "A6", "topic": "What is done to Akiva's flesh, and by whom", "readings": [
   {"reading": "unnamed people weigh it in a meat market", "supported_by": ["men29b Hebrew", "ein_yaakov_glick"]},
   {"reading": "combed with iron combs (by reference to Berakhot 61b)", "supported_by": ["rashi", "Sefaria Community Translation"]},
   {"reading": "tortured to death by the Romans", "supported_by": ["William Davidson English plain text", "Steinsaltz (same editorial project)"]}],
  "status": "the agent is not named in this passage"},
]

UNRESOLVED = [
 "The Munich 95 readings ('eighteen rows'; a possible explicit 'Moses' at the calming, and possibly 'of Moses' after 'his strength failed') are my visual readings and need to be checked against a transcription or variant apparatus.",
 "Other manuscripts of Menachot (for example the Vatican and Florence manuscripts) and the Hachi Garsinan apparatus were not checked. So the spread of 'eight' versus 'eighteen' and of singular versus plural 'reached' is unknown beyond the witnesses listed.",
 "The Ein Yaakov edition Ben Yehoyada relied on is not identified. The Daat Ein Yaakov puts 'עשרה' in parentheses and the Glick Ein Yaakov Hebrew lacks it; what the Daat parentheses mean was not checked.",
 "The text never says which 'one matter' the students asked about.",
 "Identifying 'Akiva son of Yosef' with the tanna Rabbi Akiva is a separate identity decision. It is supported by commentary and by the story's intent, not by an explicit statement here.",
 "Academic studies of this story (Rubenstein 2010; Yadin-Israel 2014, cited by Wikipedia) were not read; any claims they make about the story's composition or its links to the sugya are unchecked.",
 "The steinsaltz.org page was fetched, but its static HTML contained no article text, so it was not used.",
]

CORRECTIONS = [
 {"claim_id": "c10", "change": "Add a variant note: 'eighteen rows' (Munich 95 visual reading; reported for Ein Yaakov by Ben Yehoyada; Seder HaDorot). Leave the claim's participants unchanged.", "why": "F5"},
 {"claim_id": "c12", "change": "Add a note that the teacher is unnamed in 29b:4. The link to Akiva is story coreference, and 'Rabbi Akiva' in the English is editorial. Scope the student relation to the depicted scene.", "why": "F4, F12"},
 {"claim_id": "c13", "change": "Same note as c12. If the 'reaching' action is ever modelled, add a branch for the Bomberg plural reading.", "why": "F4, F6"},
 {"claim_id": "c14", "change": "Same note as c12 on the unnamed teacher.", "why": "F4"},
 {"claim_id": "c15", "change": "Rephrase as citing the Sinai tradition, with Moses as the recipient named in the formula. Add Rashi's 'ומשמו אומר' as commentary. Record that translations differ on whether Moses received or delivered it. Keep the note denying hearing.", "why": "F8"},
 {"claim_id": "c16", "change": "Add Rashi 29b:4:2 as commentary evidence that the calmed mind is Moses's. Add the Munich 95 wording as a separate manuscript-variant evidence item (visual reading). Keep the basis as local coreference for the printed text.", "why": "F7"},
 {"claim_id": "c21", "change": "Keep the bracket in the quote, and note that 'לאחורך' is absent from the William Davidson Aramaic but present in both Ein Yaakov texts and, by visual reading, in Munich 95.", "why": "F15"},
 {"claim_id": "c22", "change": "Add a note that no agent is named in the Hebrew. The Romans and the killing come from the editors' plain text. The link to Berakhot 61b is Rashi's.", "why": "F9, F10"},
 {"claim_id": "c23", "change": "Keep 'weighers' as an unnamed group. Do not relabel them as Romans.", "why": "F9"},
 {"claim_id": "c2", "change": "Keep as explicit literal kinship inside a divine prediction. Add a note that identifying him with the tanna Rabbi Akiva is a separate pending decision.", "why": "F3"},
 {"claim_id": None, "change": "Add mentions for Moses inside 'הלכה למשה מסיני' (s2) and for the descriptions and pronouns referring to Akiva ('אדם אחד', 'אדם כזה', 'הראהו', 'תורתו', 'שכרו').", "why": "F14"},
 {"claim_id": None, "change": "Previous review: its passes stand. It did not note the unnamed teacher, the source variants, or that the Roman agent is editorial only; add those points.", "why": "F4, F5, F6, F9"},
]

LESSONS = [
 "A scene someone is shown inside a story (vision, heavenly ascent) needs its own modality. Relations inside it, such as students of the teacher, must be scoped to that scene and must never produce historical co-presence or cross-era teaching edges.",
 "'הלכה למשה מסיני' is a formula naming a legal category and where it comes from. Model it as a source attribution with Moses as the named recipient, not as a speech turn or a hearing.",
 "Agents added in editorial plain text (here 'the Romans') must not become entities. The William Davidson English and Steinsaltz Hebrew are one editorial voice.",
 "A translation can take in a commentator's gloss (the Community Translation's 'iron combs' comes from Rashi). Treat a translation's wording as that translator's reading, not as a text variant.",
 "Kabbalistic spark or soul-root identifications are not kinship and not historical identity. Keep them outside the person graph.",
 "The same stock opening told by a different sage in another tractate (Shabbat 89a, Rabbi Yehoshua ben Levi) is a parallel story, not an alternative attribution of this one.",
 "The contract needs a way to type God as a speaker without typing God as a human person, as the earlier review noted.",
 "Store manuscript and print variants (eight or eighteen; שהגיע or שהגיעו) as a source-variant evidence type, separate from later emendations and from translation choices.",
]
